import { AccessLevel } from "../enum/AccessLevel";
import { Asset } from "../interface/Asset";
import { Component } from "../interface/Component";
import { Object } from "../interface/Object";
import { Resource } from "../interface/Resource";

// This file is autogenerated - Please do not edit 

export interface AccessZone extends Asset, Resource, Object, Component {
  /** Maximum capacity or occupancy limit */
  capacity?: number;
  /** Account Access Level */
  accessLevel?: AccessLevel;
  /** The external ID that defines this object for joining purposes */
  site?: string;
  /** The external ID that defines this object for joining purposes */
  schedules?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  visitors?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  app?: string;
  /** The external ID that defines this object for joining purposes */
  entries?: string | Array<string>;
}
