import { AccessCredential_level } from "../enum/AccessCredential_level";
import { AccessCredential_type } from "../enum/AccessCredential_type";
import { Asset } from "../interface/Asset";
import { Component } from "../interface/Component";
import { Object } from "../interface/Object";
import { Principal } from "../interface/Principal";

// This file is autogenerated - Please do not edit 

export interface AccessCredential extends Asset, Principal, Object, Component {
  /** The type or category of access credential */
  credentialType?: AccessCredential_type;
  /** Level of access permissions granted by the credential */
  accessLevel?: AccessCredential_level;
  /** Whether this access credential is currently active and can be used for authentication */
  isActive?: boolean;
  /** The start date */
  validFrom?: Date;
  /** The end date */
  validUntil?: Date;
  /** The external ID that defines this object for joining purposes */
  principal?: string;
  /** The external ID that defines this object for joining purposes */
  schedules?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  app?: string;
  /** The external ID that defines this object for joining purposes */
  visitor?: string;
}
