import { Email } from "@zerobias-org/types-core-js";
import { PermissionSet, T3_PermissionSet } from "../document/PermissionSet";
import { AccessLevel } from "../enum/AccessLevel";
import { AccountStatus } from "../enum/AccountStatus";
import { AccountType } from "../enum/AccountType";
import { AuthType } from "../enum/AuthType";
import { Object } from "../interface/Object";
import { Principal } from "../interface/Principal";

// This file is autogenerated - Please do not edit 

export interface Account extends Principal, Object {
  /** A valid email */
  email?: Email | Array<Email>;
  /** Type of a user or system account inside an application */
  type?: AccountType;
  /** Authentication Mechanism */
  authType?: AuthType | Array<AuthType>;
  /** A user that is authorized (and therefore, trusted) to perform security-relevant functions that ordinary users are not authorized to perform. */
  privileged?: boolean;
  /** True if the user has enabled multi-factor authentication */
  mfaEnabled?: boolean;
  /** Status of a user or system account inside an application */
  status?: AccountStatus;
  /** Account Access Level */
  accessLevel?: AccessLevel;
  /** The login for the entity */
  login?: string;
  /** List of permissions for a given principal and resource */
  permission?: PermissionSet;
  /** List of permissions for a given principal and resource */
  app?: string | Array<string> | T3_PermissionSet | Array<T3_PermissionSet>;
  /** The external ID that defines this object for joining purposes */
  person?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  identity?: string | Array<string>;
}
