import { Object } from "../interface/Object";

// This file is autogenerated - Please do not edit 

export interface Action extends Object {
  /** The external ID that defines this object for joining purposes */
  accessRules?: string | Array<string>;
}
