import { Compute } from "../document/Compute";
import { Filesystem } from "../document/Filesystem";
import { InstalledApp } from "../document/InstalledApp";
import { NetworkInterface } from "../document/NetworkInterface";
import { Object } from "../interface/Object";

// This file is autogenerated - Please do not edit 

export interface AppEnvironment extends Object {
  /** A software mechanism that defines the way that files are named, stored, organized, and accessed on logical volumes of partitioned memory */
  filesystem?: Filesystem | Array<Filesystem>;
  /** Application installed within Application Environment */
  app?: InstalledApp | Array<InstalledApp>;
  /** Compute attributes */
  compute?: Compute;
  /** Operating System Name */
  osName?: string;
  /** Operating System Version */
  osVersion?: string;
  /** Operating System Edition */
  osEdition?: string;
  /** A network interface is the point of interconnection between a computer and a private or public network. A network interface is generally a network interface card (NIC), but does not have to have a physical form. Instead, the network interface can be implemented in software virtualization */
  networkInterface?: NetworkInterface | Array<NetworkInterface>;
  /** The external ID that defines this object for joining purposes */
  osCpeProduct?: string;
  /** The external ID that defines this object for joining purposes */
  machine?: string;
}
