import { AppEnvironment } from "../interface/AppEnvironment";
import { Baseline } from "../interface/Baseline";
import { Object } from "../interface/Object";

// This file is autogenerated - Please do not edit 

export interface AppEnvironmentBaseline extends Baseline, AppEnvironment, Object {
}
