import { PasswordPolicy } from "../document/PasswordPolicy";
import { T3_PermissionSet } from "../document/PermissionSet";
import { Asset } from "../interface/Asset";
import { Component } from "../interface/Component";
import { Object } from "../interface/Object";

// This file is autogenerated - Please do not edit 

export interface Application extends Asset, Component, Object {
  /** Describes how a system manages and checks passwords */
  passwordPolicy?: PasswordPolicy;
  /** List of permissions for a given principal and resource */
  groups?: string | Array<string> | T3_PermissionSet | Array<T3_PermissionSet>;
  /** The external ID that defines this object for joining purposes */
  roles?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  serviceEndpoints?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  accessRules?: string | Array<string>;
  /** List of permissions for a given principal and resource */
  accounts?: string | Array<string> | T3_PermissionSet | Array<T3_PermissionSet>;
}
