import { T3_IssuedDate } from "../document/IssuedDate";
import { NetworkInterface } from "../document/NetworkInterface";
import { Asset_criticality } from "../enum/Asset_criticality";
import { Asset_status } from "../enum/Asset_status";
import { Asset_type } from "../enum/Asset_type";
import { OscalAssetType } from "../enum/OscalAssetType";
import { Component } from "../interface/Component";
import { Object } from "../interface/Object";

// This file is autogenerated - Please do not edit 

export interface Asset extends Component, Object {
  /** Asset Type */
  assetType?: Asset_type;
  /** Asset Criticality */
  businessCriticality?: Asset_criticality;
  /** Asset Criticality */
  complianceCriticality?: Asset_criticality;
  /** Asset Criticality */
  securityCriticality?: Asset_criticality;
  /** Asset Criticality */
  safetyCriticality?: Asset_criticality;
  /** Asset Criticality */
  sustainabilityCriticality?: Asset_criticality;
  /** The number of days to retain backups of this Asset */
  backupRetentionDays?: number;
  /** Amount of time a product is covered by warranty */
  warrantyMonths?: number;
  /** OSCAL Asset Type as defined by NIST */
  oscalAssetType?: OscalAssetType;
  /** Boolean value indicating whether or not the asset is virtual */
  virtual?: boolean;
  /** Boolean value indicating whether or not the asset allows for authenticated vulnerability scans */
  allowsAuthenticatedScan?: boolean;
  /** The date when a component was purchased */
  purchaseDate?: Date;
  /** Timestamp of when the warranty expires */
  warrantyExpires?: Date;
  /** A network interface is the point of interconnection between a computer and a private or public network. A network interface is generally a network interface card (NIC), but does not have to have a physical form. Instead, the network interface can be implemented in software virtualization */
  network?: NetworkInterface | Array<NetworkInterface>;
  /** Asset Status */
  assetStatus?: Asset_status;
  /** An organizationally specific identifier that is used to uniquely identify a logical or tangible item by the organization that owns the item */
  assetId?: string;
  /** An asset tag assigned by the organization responsible for maintaining the logical or tangible item */
  assetTag?: string;
  /** Name of baseline configuration of an asset */
  baselineConfigurationName?: string;
  /** The time when the Database should be backed up */
  preferredBackupWindow?: string;
  /** The time when the Asset should be maintained */
  preferredMaintenanceWindow?: string;
  /** The master account name for this Asset */
  adminUsername?: string;
  /** The serial number for an asset */
  serialNumber?: string;
  /** The manufacturer of an asset */
  manufacturer?: string;
  /** The model or part number of an asset */
  model?: string;
  /** A broadcast domain that is partitioned and isolated within a network at the data link layer. A single physical local area network (LAN) can be logically partitioned into multiple, independent VLANs; a group of devices on one or more physical LANs can be configured to communicate within the same VLAN, as if they were attached to the same physical LAN. */
  vlanId?: number | Array<number>;
  /** The external ID that defines this object for joining purposes */
  configuration?: string | Array<string>;
  /** Issued Date */
  assignedTo?: string | T3_IssuedDate;
  /** The external ID that defines this object for joining purposes */
  runtime?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  inventoryItems?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  cpeProduct?: string;
  /** The external ID that defines this object for joining purposes */
  assetHistory?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  location?: string;
  /** The external ID that defines this object for joining purposes */
  itamApp?: string;
}
