import { AssetHistory_operation } from "../enum/AssetHistory_operation";
import { Object } from "../interface/Object";

// This file is autogenerated - Please do not edit 

export interface AssetHistory extends Object {
  /** Asset History operation */
  operation?: AssetHistory_operation;
  /** The external ID that defines this object for joining purposes */
  assignedTo?: string;
  /** The external ID that defines this object for joining purposes */
  asset?: string;
}
