import { CloudAvailabilityZoneDef, CloudRegionDef } from "@zerobias-org/types-core-js";
import { OperationalStatus } from "../enum/OperationalStatus";
import { Object } from "../interface/Object";

// This file is autogenerated - Please do not edit 

export interface AvailabilityZone extends Object {
  /** A Cloud Availaility Zone Code */
  zoneId?: CloudAvailabilityZoneDef;
  /** Current operational state of a resource or interface. */
  status?: OperationalStatus;
  /** A Cloud Region Code */
  region?: CloudRegionDef;
  /** The external ID that defines this object for joining purposes */
  networks?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  service?: string;
  /** The external ID that defines this object for joining purposes */
  inventoryItems?: string | Array<string>;
}
