import { BackupLocationType } from "../enum/BackupLocationType";
import { BackupType } from "../enum/BackupType";
import { Backup_mediaType } from "../enum/Backup_mediaType";
import { Object } from "../interface/Object";

// This file is autogenerated - Please do not edit 

export interface Backup extends Object {
  /** The generation of the backup. 0 = full, 1 = child, 2 = grandchild, etc. */
  generation?: number;
  /** Boolean value to determine if encryption is enabled or not */
  encryption?: boolean;
  /** Date of Creation */
  created?: Date;
  /** Backup location type */
  backupLocationType?: BackupLocationType | Array<BackupLocationType>;
  /** The size of the capacity, in Bytes */
  backupSize?: number;
  /** Backup file(s) location */
  backupLocation?: string | Array<string>;
  /** Backup source file(s) location */
  sourceLocation?: string | Array<string>;
  /** Type of backup */
  backupType?: BackupType;
  /** Backup media type */
  mediaType?: Backup_mediaType;
  /** The external ID that defines this object for joining purposes */
  backupJob?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  parentBackup?: string;
  /** The external ID that defines this object for joining purposes */
  childBackup?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  sourceComponent?: string | Array<string>;
}
