import { Application } from "../interface/Application";
import { Asset } from "../interface/Asset";
import { Component } from "../interface/Component";
import { CryptoDevice } from "../interface/CryptoDevice";
import { Object } from "../interface/Object";

// This file is autogenerated - Please do not edit 

export interface BackupApplication extends Application, CryptoDevice, Asset, Component, Object {
  /** The external ID that defines this object for joining purposes */
  backupProfile?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  backupJobs?: string | Array<string>;
}
