import { BackupState } from "../enum/BackupState";
import { Object } from "../interface/Object";

// This file is autogenerated - Please do not edit 

export interface BackupJob extends Object {
  /** Timestamp in RFC339/ISO8601 date-time string */
  started?: Date;
  /** Timestamp in RFC339/ISO8601 date-time string */
  stopped?: Date;
  /** Backup job state */
  backupState?: BackupState;
  /** The external ID that defines this object for joining purposes */
  profile?: string;
  /** The external ID that defines this object for joining purposes */
  backup?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  app?: string;
}
