import { Duration } from "@zerobias-org/types-core-js";
import { CryptoModule } from "../document/CryptoModule";
import { BackupType } from "../enum/BackupType";
import { Object } from "../interface/Object";

// This file is autogenerated - Please do not edit 

export interface BackupProfile extends Object {
  /** Type of backup */
  backupType?: BackupType;
  /** The frequency of backups expressed in ISO 8601 duration format */
  backupFrequency?: Duration;
  /** A set of hardware, software, and/or firmware that implements approved security functions (including cryptographic algorithms and key generation). */
  cryptoModule?: CryptoModule;
  /** The external ID that defines this object for joining purposes */
  backupJobs?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  backupApp?: string;
}
