import { Object } from "../interface/Object";

// This file is autogenerated - Please do not edit 

export interface Baseline extends Object {
  /** The external ID that defines this object for joining purposes */
  standard?: string;
  /** The external ID that defines this object for joining purposes */
  baselineElements?: string | Array<string>;
}
