import { URL } from "@zerobias-org/types-core-js";
import { Object } from "../interface/Object";

// This file is autogenerated - Please do not edit 

export interface Branch extends Object {
  /** SHA digest ID for SCM object */
  sha?: string;
  /** URL for commiting to a branch */
  commitsUrl?: URL;
  /** URL for protecting a branch */
  protectionUrl?: URL;
  /** Boolean value indicating whether branch protection is enabled */
  protected?: boolean;
  /** The external ID that defines this object for joining purposes */
  outPullRequest?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  owner: string;
  /** The external ID that defines this object for joining purposes */
  repo: string;
  /** The external ID that defines this object for joining purposes */
  protection?: string;
  /** The external ID that defines this object for joining purposes */
  findings?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  inPullRequest?: string | Array<string>;
}
