import { Object } from "../interface/Object";

// This file is autogenerated - Please do not edit 

export interface BranchProtection extends Object {
  /** The number of approving reviews required */
  requiredApprovingReviewCount?: number;
  /** Whether or not the code owner reviews are required */
  requireCodeOwnerReviews?: boolean;
  /** Whether or not the stale reviews are dismissed */
  dismissStaleReviews?: boolean;
  /** Whether or not the protection is enabled */
  enabled?: boolean;
  /** Required signatures setting */
  requiredSignatures?: string;
  /** Required conversation resolution setting */
  requiredConversationResolution?: string;
  /** Block creations setting */
  blockCreations?: string;
  /** Allow deletions setting */
  allowDeletions?: string;
  /** Allow force pushes setting */
  allowForcePushes?: string;
  /** Required linear history setting */
  requiredLinearHistory?: string;
  /** Enforce admins setting */
  enforceAdmins?: string;
  /** Lock Branch */
  lockBranch?: string;
  /** Allow Fork Syncing */
  allowForkSyncing?: string;
  /** The external ID that defines this object for joining purposes */
  bypassPullRequestAllowances?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  restrictions?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  branches?: string | Array<string>;
}
