import { CloudRegionDef } from "@zerobias-org/types-core-js";
import { BucketGrant } from "../document/BucketGrant";
import { BucketLifecycleRule } from "../document/BucketLifecycleRule";
import { CorsRule } from "../document/CorsRule";
import { Component } from "../interface/Component";
import { CryptoDevice } from "../interface/CryptoDevice";
import { Object } from "../interface/Object";

// This file is autogenerated - Please do not edit 

export interface Bucket extends Component, CryptoDevice, Object {
  /** A Cloud Region Code */
  region?: CloudRegionDef;
  /** Enables a different account/user to access a bucket */
  grants?: BucketGrant | Array<BucketGrant>;
  /** Rules that govern when to delete or migrate bucket content */
  lifecycleRules?: BucketLifecycleRule | Array<BucketLifecycleRule>;
  /** A rule that supports a Cross-Origin Resource Sharing (CORS) configuration */
  corsRules?: CorsRule | Array<CorsRule>;
  /** true if versioning is enabled, otherwise false */
  versioning?: boolean;
  /** Whether public access is disabled for this bucket */
  publicAccessDisabled?: boolean;
  /** The external ID that defines this object for joining purposes */
  objectStorage?: string;
}
