import { TlsAsymmetricKeyInfo, TlsSignatureAlgorithmDef, TlsX509Subject } from "@zerobias-org/types-core-js";
import { CertificateStatus } from "../enum/CertificateStatus";
import { Asset } from "../interface/Asset";
import { Component } from "../interface/Component";
import { Object } from "../interface/Object";

// This file is autogenerated - Please do not edit 

export interface Certificate extends Asset, Component, Object {
  /** Certificate Thumbprint */
  thumbprint?: string;
  /** A x509 subject */
  subject?: TlsX509Subject;
  /** A x509 subject */
  issuer?: TlsX509Subject;
  /** Subject alternative name */
  subjectAltName?: string | Array<string>;
  /** An asymmetric key info, including an algorithm, number of bits, and possibly the keys themselves */
  asymmetricKey?: TlsAsymmetricKeyInfo;
  /** A TLS signature algorithm */
  signatureAlgorithm?: TlsSignatureAlgorithmDef;
  /** Enumeration store for the current status of an Certificate */
  status?: CertificateStatus;
  /** The time at which the certificate was issued */
  timeIssued?: Date;
  /** Validity start date-time */
  validFrom?: Date;
  /** Validity end date-time */
  validTo?: Date;
  /** The external ID that defines this object for joining purposes */
  issuerCert?: string;
}
