import { ChangeType } from "../enum/ChangeType";
import { Object } from "../interface/Object";
import { Ticket } from "../interface/Ticket";
import { WorkflowStepTicket } from "../interface/WorkflowStepTicket";

// This file is autogenerated - Please do not edit 

export interface ChangeStepTicket extends WorkflowStepTicket, Ticket, Object {
  /** Type of change as defined by the Information Technology Infrastructure Library (ITIL) verison 3 (ITIL v3) Service Transition best practices */
  changeType?: ChangeType;
  /** placeholder for future work filEds, unit32's, and other typos smiley face. No regerts. */
  testPlan?: string;
  /** The external ID that defines this object for joining purposes */
  changeTicket?: string;
}
