import { ChangeApprovalType } from "../enum/ChangeApprovalType";
import { ChangeType } from "../enum/ChangeType";
import { Object } from "../interface/Object";
import { Ticket } from "../interface/Ticket";
import { WorkflowTicket } from "../interface/WorkflowTicket";

// This file is autogenerated - Please do not edit 

export interface ChangeTicket extends WorkflowTicket, Ticket, Object {
  /** Type of change as defined by the Information Technology Infrastructure Library (ITIL) verison 3 (ITIL v3) Service Transition best practices */
  changeType?: ChangeType;
  /** placeholder for future work filEds, unit32's, and other typos smiley face. No regerts. */
  testPlan?: string;
  /** Change Approval Type of roles required to approve a change in a given workflow */
  requiredApproval?: ChangeApprovalType | Array<ChangeApprovalType>;
  /** Change Approval Type of roles required to approve a change in a given workflow */
  approval?: ChangeApprovalType | Array<ChangeApprovalType>;
  /** The external ID that defines this object for joining purposes */
  ticketingSystem?: string;
  /** The external ID that defines this object for joining purposes */
  changeStep?: string | Array<string>;
}
