import { CloudProviderDef } from "@zerobias-org/types-core-js";
import { Application } from "../interface/Application";
import { Asset } from "../interface/Asset";
import { Component } from "../interface/Component";
import { Object } from "../interface/Object";

// This file is autogenerated - Please do not edit 

export interface CloudService extends Application, Asset, Component, Object {
  /** A Cloud Provider */
  provider?: CloudProviderDef;
  /** The external ID that defines this object for joining purposes */
  availabilityZones?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  objectStorage?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  environments?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  inventoryItems?: string | Array<string>;
}
