import { Asset } from "../interface/Asset";
import { Component } from "../interface/Component";
import { Environment } from "../interface/Environment";
import { Location } from "../interface/Location";
import { Object } from "../interface/Object";

// This file is autogenerated - Please do not edit 

export interface CloudEnvironment extends Environment, Asset, Location, Object, Component {
  /** The external ID that defines this object for joining purposes */
  cloudService?: string;
  /** The external ID that defines this object for joining purposes */
  elasticAddress?: string;
}
