import { CloudProviderDef } from "@zerobias-org/types-core-js";
import { Component } from "../interface/Component";
import { Object } from "../interface/Object";
import { ObjectStorage } from "../interface/ObjectStorage";

// This file is autogenerated - Please do not edit 

export interface CloudObjectStorage extends ObjectStorage, Component, Object {
  /** A Cloud Provider */
  provider?: CloudProviderDef;
  /** The external ID that defines this object for joining purposes */
  service?: string;
}
