import { Comment } from "../document/Comment";
import { Object } from "../interface/Object";

// This file is autogenerated - Please do not edit 

export interface CodeReview extends Object {
  /** Boolean value indicating whether or not a CodeReview has been approved */
  approved?: boolean;
  /** SHA digest ID for SCM object */
  commitId?: string;
  /** A generic comment document */
  comments?: Comment | Array<Comment>;
  /** The external ID that defines this object for joining purposes */
  pullRequest: string;
  /** The external ID that defines this object for joining purposes */
  reviewer: string;
}
