import { CompetencyTerm } from "../enum/CompetencyTerm";
import { CompetencyType } from "../enum/CompetencyType";
import { Object } from "../interface/Object";

// This file is autogenerated - Please do not edit 

export interface Competency extends Object {
  /** Competency Type as prescribed by DoD 8570 for Information Assurance (IA) or the Office of Personnel Management (OPM) */
  competencyType?: CompetencyType | Array<CompetencyType>;
  /** Competency Term */
  baseTerm?: CompetencyTerm;
  /** Competency Term */
  ceTerm?: CompetencyTerm;
  /** Number of base term credits or continuous education term credits required to obtain or maintain a comptenency */
  baseCredits?: number;
  /** Number of base term credits or continuous education term credits required to obtain or maintain a comptenency */
  ceTermCredits?: number;
  /** The external ID that defines this object for joining purposes */
  module?: string | Array<string>;
}
