import { T3_ComponentRole } from "../document/ComponentRole";
import { OscalComponentType } from "../enum/OscalComponentType";
import { Object } from "../interface/Object";

// This file is autogenerated - Please do not edit 

export interface Component extends Object {
  /** Component Version */
  version?: string;
  /** Component Type as defined by OSCAL */
  componentType?: OscalComponentType;
  /** Whether or not a component is a boundary component. */
  boundaryComponent?: boolean;
  /** Date of enablement */
  releaseDate?: Date;
  /** Organization defined purpose for a given Component. */
  purpose?: string;
  /** The external ID that defines this object for joining purposes */
  validations?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  backup?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  associatedTickets?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  proofOfCompliance?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  tests?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  findings?: string | Array<string>;
  /** Role and role type(s) responsible for a component */
  responsible?: string | Array<string> | T3_ComponentRole | Array<T3_ComponentRole>;
  /** The external ID that defines this object for joining purposes */
  cpeProduct?: string;
  /** The external ID that defines this object for joining purposes */
  product?: string;
}
