import { Parameter } from "../document/Parameter";
import { Object } from "../interface/Object";

// This file is autogenerated - Please do not edit 

export interface Configuration extends Object {
  /** A configuration parameter, registy key, environment variable, etc. */
  parameters?: Parameter | Array<Parameter>;
  /** The external ID that defines this object for joining purposes */
  assets?: string | Array<string>;
}
