import { Email, LanguageDef } from "@zerobias-org/types-core-js";
import { MailInfo } from "../document/MailInfo";
import { PhoneInfo } from "../document/PhoneInfo";
import { Location } from "../interface/Location";
import { Object } from "../interface/Object";

// This file is autogenerated - Please do not edit 

export interface Contact extends Location, Object {
  /** A persons preferred spoken and written language */
  preferredLanguage?: LanguageDef | Array<LanguageDef>;
  /** A valid email */
  email?: Email | Array<Email>;
  /** Mail Info */
  mailInfo?: MailInfo | Array<MailInfo>;
  /** Prefix name for a person */
  prefix?: string;
  /** The first name of a person */
  firstName?: string;
  /** The middle name for a person */
  middleName?: string;
  /** The last name of a person */
  lastName?: string;
  /** Maiden name for a person */
  maidenName?: string;
  /** Suffix name for a person. */
  suffix?: string;
  /** A persons prefered pronoun - Sir, Miss, Mr., He/Him, She/Her, etc. */
  pronoun?: string;
  /** The legal (government ID) name for a person. */
  legalName?: string | Array<string>;
  /** The job title for the person */
  jobTitle?: string | Array<string>;
  /** The title of the position for an employee */
  positionTitle?: string | Array<string>;
  /** Name of a department for a business, or other entity */
  department?: string;
  /** Object store for a phone number: includes the number and phone type */
  phoneInfo?: PhoneInfo | Array<PhoneInfo>;
}
