import { Application } from "../interface/Application";
import { Asset } from "../interface/Asset";
import { Component } from "../interface/Component";
import { Object } from "../interface/Object";

// This file is autogenerated - Please do not edit 

export interface CRMApplication extends Application, Asset, Component, Object {
  /** The external ID that defines this object for joining purposes */
  customers?: string | Array<string>;
}
