import { CryptoModule } from "../document/CryptoModule";
import { Object } from "../interface/Object";

// This file is autogenerated - Please do not edit 

export interface CryptoDevice extends Object {
  /** Indicates whether the component is encrypted */
  cryptoEnabled?: boolean;
  /** A set of hardware, software, and/or firmware that implements approved security functions (including cryptographic algorithms and key generation). */
  cryptoModule?: CryptoModule;
}
