import { Backup } from "../interface/Backup";
import { Object } from "../interface/Object";

// This file is autogenerated - Please do not edit 

export interface DatabaseSnapshot extends Backup, Object {
  /** The external ID that defines this object for joining purposes */
  database?: string;
  /** The external ID that defines this object for joining purposes */
  cluster?: string;
  /** The external ID that defines this object for joining purposes */
  dbms?: string;
}
