import { Asset } from "../interface/Asset";
import { Component } from "../interface/Component";
import { NetworkService } from "../interface/NetworkService";
import { Object } from "../interface/Object";

// This file is autogenerated - Please do not edit 

export interface Database extends Asset, NetworkService, Component, Object {
  /** The external ID that defines this object for joining purposes */
  snapshots?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  cluster?: string;
  /** The external ID that defines this object for joining purposes */
  dbms?: string;
}
