import { Application } from "../interface/Application";
import { Asset } from "../interface/Asset";
import { Component } from "../interface/Component";
import { Object } from "../interface/Object";

// This file is autogenerated - Please do not edit 

export interface DBMS extends Application, Asset, Component, Object {
  /** The external ID that defines this object for joining purposes */
  databases?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  snapshots?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  databaseClusters?: string | Array<string>;
}
