import { IpAddress } from "@zerobias-org/types-core-js";
import { IpRoute } from "../document/IpRoute";
import { NetBiosNodeType } from "../enum/NetBiosNodeType";
import { Object } from "../interface/Object";

// This file is autogenerated - Please do not edit 

export interface DhcpOptions extends Object {
  /** the offset of the client's subnet in seconds from Coordinated Universal Time (UTC) */
  timeOffset?: number;
  /** An item in an IP routing table */
  staticRoutes?: IpRoute | Array<IpRoute>;
  /** The subnet mask option specifies the client's subnet mask as per RFC 950 */
  netmask?: IpAddress;
  /** IP addresses for routers on the client's subnet */
  routers?: IpAddress | Array<IpAddress>;
  /** IP addresses for time servers */
  timeServers?: IpAddress | Array<IpAddress>;
  /** IP addresses for DNS name servers */
  dnsNameServers?: IpAddress | Array<IpAddress>;
  /** IP addresses for UDP log servers available to the client */
  logServers?: IpAddress | Array<IpAddress>;
  /** IP addresses for TFTP servers available to the client */
  tftpServer?: IpAddress;
  /** IP addresses for NETBIOS name servers */
  netBiosNameServers?: IpAddress | Array<IpAddress>;
  /** The domain name that client should use when resolving hostnames via DNS */
  domainName?: string | Array<string>;
  /** Specifies the Network Basic Input/Output System (NetBIOS) node type */
  netBiosNodeType?: NetBiosNodeType;
  /** The external ID that defines this object for joining purposes */
  dhcpNetworks?: string | Array<string>;
}
