import { MacAddress } from "@zerobias-org/types-core-js";
import { OperationalStatus } from "../enum/OperationalStatus";
import { Object } from "../interface/Object";

// This file is autogenerated - Please do not edit 

export interface ElasticInterface extends Object {
  /** A hardware MAC address */
  macAddress?: MacAddress;
  /** Current operational state of a resource or interface. */
  operationalStatus?: OperationalStatus;
  /** The external ID that defines this object for joining purposes */
  elasticAddresses?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  virtualMachines?: string | Array<string>;
}
