import { IpAddress } from "@zerobias-org/types-core-js";
import { Object } from "../interface/Object";

// This file is autogenerated - Please do not edit 

export interface ElasticAddress extends Object {
  /** An IPv4 or IPv6 Address */
  ipAddress?: IpAddress;
  /** The external ID that defines this object for joining purposes */
  elasticInterface?: string;
  /** The external ID that defines this object for joining purposes */
  environment?: string;
}
