import { Object } from "../interface/Object";

// This file is autogenerated - Please do not edit 

export interface Element extends Object {
  /** An identifier for an object as seen from the external point of view */
  externalId?: string;
  /** A relatively unique identifier for an object */
  code?: string;
  /** The version of an element */
  version?: string;
  /** Markdown text of the background for this test case */
  background?: string;
  /** The external ID that defines this object for joining purposes */
  baselineElements?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  parent?: string;
  /** The external ID that defines this object for joining purposes */
  subElements?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  standard?: string;
  /** The external ID that defines this object for joining purposes */
  elementType?: string;
  /** The external ID that defines this object for joining purposes */
  testCases?: string | Array<string>;
}
