import { Email } from "@zerobias-org/types-core-js";
import { EndUserDeviceEnrollmentType } from "../enum/EndUserDeviceEnrollmentType";
import { EndUserDeviceOwnerType } from "../enum/EndUserDeviceOwnerType";
import { EndUserDeviceRegistrationState } from "../enum/EndUserDeviceRegistrationState";
import { EndUserDeviceType } from "../enum/EndUserDeviceType";
import { OscalComponentType } from "../enum/OscalComponentType";
import { AppEnvironment } from "../interface/AppEnvironment";
import { Asset } from "../interface/Asset";
import { Component } from "../interface/Component";
import { Object } from "../interface/Object";

// This file is autogenerated - Please do not edit 

export interface EndUserDevice extends AppEnvironment, Asset, Component, Object {
  /** A valid email */
  userEmail?: Email | Array<Email>;
  /** The possible values for an end user device registration */
  registrationState?: EndUserDeviceRegistrationState;
  /** True if device complies with all MDM/RMM requirements */
  isCompliant?: boolean;
  /** True if device complies with all MDM/RMM requirements */
  bootstrapTokenEscrowed?: boolean;
  /** True if device complies with all MDM/RMM requirements */
  complianceGracePeriodExpiration?: boolean;
  /** Boolean value indicating whether or not the asset is virtual */
  virtual?: boolean;
  /** True if more than one person uses this device */
  isSharedDevice?: boolean;
  /** True if this device is supervised */
  isSupervised?: boolean;
  /** True if this device is rooted / jail broken */
  isJailBroken?: boolean;
  /** True if this device is reported lost */
  isLost?: boolean;
  /** Device Type */
  deviceType?: EndUserDeviceType;
  /** Device Ownerhip Types */
  ownerType?: EndUserDeviceOwnerType;
  /** Possible ways of adding an end-user device to management */
  enrollmentType?: EndUserDeviceEnrollmentType;
  /** Date and time when device was registered/enrolled */
  enrollmentDate?: Date;
  /** Date and time when certificate or enrollment expires */
  expirationDate?: Date;
  /** Component Type as defined by OSCAL */
  componentType?: OscalComponentType;
  /** The full name of a person */
  userDescription?: string;
  /** The number of active malware infestations detected on the device */
  activeMalwareCount?: number;
  /** The number of inactive/remediated malware infestations detected on the device */
  remediatedMalwareCount?: number;
  /** The external ID that defines this object for joining purposes */
  user?: string;
  /** The external ID that defines this object for joining purposes */
  deviceManagementApp?: string;
}
