import { Email, LanguageDef } from "@zerobias-org/types-core-js";
import { AuthType } from "../enum/AuthType";
import { Object } from "../interface/Object";
import { Principal } from "../interface/Principal";

// This file is autogenerated - Please do not edit 

export interface FederatedIdentity extends Principal, Object {
  /** The login for the entity */
  login?: string;
  /** A valid email */
  email?: Email | Array<Email>;
  /** Authentication Mechanism */
  authType?: AuthType | Array<AuthType>;
  /** The job title for the person */
  jobTitle?: string | Array<string>;
  /** A persons preferred spoken and written language */
  preferredLanguage?: LanguageDef | Array<LanguageDef>;
  /** Indicates if an e-mail address has been verified */
  emailVerified?: boolean;
  /** The subject of an OAUTH claim or user */
  sub?: string;
  /** The external ID that defines this object for joining purposes */
  idp: string;
  /** The external ID that defines this object for joining purposes */
  person?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  account?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  devices?: string | Array<string>;
}
