import { Finding_state } from "../enum/Finding_state";
import { Object } from "../interface/Object";

// This file is autogenerated - Please do not edit 

export interface Finding extends Object {
  /** State of the finding */
  state?: Finding_state;
  /** The external ID that defines this object for joining purposes */
  resolved?: string;
  /** The external ID that defines this object for joining purposes */
  discovered: string;
  /** The external ID that defines this object for joining purposes */
  ongoing?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  components?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  testCase: string;
  /** The external ID that defines this object for joining purposes */
  subjects?: string | Array<string>;
}
