import { Firewall_rule } from "../document/Firewall_rule";
import { T3_RouterAssociation } from "../document/RouterAssociation";
import { Asset } from "../interface/Asset";
import { Component } from "../interface/Component";
import { Object } from "../interface/Object";

// This file is autogenerated - Please do not edit 

export interface Firewall extends Asset, Component, Object {
  /** Firewall Rule */
  inRules?: Firewall_rule | Array<Firewall_rule>;
  /** Firewall Rule */
  outRules?: Firewall_rule | Array<Firewall_rule>;
  /** Describes relationship between a Router and Network */
  networks?: string | Array<string> | T3_RouterAssociation | Array<T3_RouterAssociation>;
  /** The external ID that defines this object for joining purposes */
  environment?: string;
}
