import { Email } from "@zerobias-org/types-core-js";
import { PermissionSet, T3_PermissionSet } from "../document/PermissionSet";
import { AccessLevel } from "../enum/AccessLevel";
import { AccountStatus } from "../enum/AccountStatus";
import { Object } from "../interface/Object";
import { Principal } from "../interface/Principal";

// This file is autogenerated - Please do not edit 

export interface Group extends Principal, Object {
  /** List of permissions for a given principal and resource */
  permission?: PermissionSet | Array<PermissionSet>;
  /** A valid email */
  email?: Email | Array<Email>;
  /** Account Access Level */
  accessLevel?: AccessLevel;
  /** Status of a user or system account inside an application */
  status?: AccountStatus;
  /** List of permissions for a given principal and resource */
  app?: string | T3_PermissionSet;
  /** List of permissions for a given principal and resource */
  members?: string | Array<string> | T3_PermissionSet | Array<T3_PermissionSet>;
}
