import { IpProtocol } from "../enum/IpProtocol";
import { Object } from "../interface/Object";

// This file is autogenerated - Please do not edit 

export interface IANAProtocol extends Object {
  /** The port number of a OSI layer 4 socket address */
  port?: number | Array<number>;
  /** IANA protocol numbers for IP traffic */
  transportProtocol?: IpProtocol | Array<IpProtocol>;
}
