import { URL } from "@zerobias-org/types-core-js";
import { IdpProtocolType } from "../enum/IdpProtocolType";
import { Application } from "../interface/Application";
import { Asset } from "../interface/Asset";
import { Component } from "../interface/Component";
import { Object } from "../interface/Object";

// This file is autogenerated - Please do not edit 

export interface IdentityProvider extends Application, Asset, Component, Object {
  /** Protocol used by Identity Provider */
  protocol?: IdpProtocolType | Array<IdpProtocolType>;
  /** Identity Provider (IdP) Service Endpoint URL */
  serviceEndpoint?: URL;
  /** Identity Provider (IdP) Login Screen URL */
  loginScreen?: URL;
  /** The URL to initiate an authenticated user session */
  loginUrl?: string;
  /** The URL to terminate a user session */
  logoutUrl?: string;
  /** Certificate thumbprint that is associated with a specified OIDC */
  thumbprint?: string | Array<string>;
  /** The audience that is associated with a specified OIDC */
  audience?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  identity?: string | Array<string>;
}
