import { IncidentPhase } from "../enum/IncidentPhase";
import { IncidentType } from "../enum/IncidentType";
import { Object } from "../interface/Object";
import { Ticket } from "../interface/Ticket";

// This file is autogenerated - Please do not edit 

export interface Incident extends Ticket, Object {
  /** Incident Type as defined by the Chairman of the Joint Chiefs of Staff Manual (CJCSM) 6510.01B and DoD */
  incidentType?: IncidentType;
  /** Incident Response Lifecycle as defined by NIST */
  phase?: IncidentPhase;
  /** The external ID that defines this object for joining purposes */
  ticketingSystem?: string;
}
