import { Asset_type } from "../enum/Asset_type";
import { Object } from "../interface/Object";

// This file is autogenerated - Please do not edit 

export interface InventoryItem extends Object {
  /** Asset Type */
  assetType?: Asset_type;
  /** The quantity */
  qty?: number;
  /** The external ID that defines this object for joining purposes */
  app?: string;
  /** The external ID that defines this object for joining purposes */
  cloudService?: string;
  /** The external ID that defines this object for joining purposes */
  location?: string;
  /** The external ID that defines this object for joining purposes */
  assets?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  environment?: string;
  /** The external ID that defines this object for joining purposes */
  availabilityZone?: string;
}
