import { T3_IpRoute } from "../document/IpRoute";
import { Asset } from "../interface/Asset";
import { Component } from "../interface/Component";
import { Object } from "../interface/Object";

// This file is autogenerated - Please do not edit 

export interface IpGateway extends Asset, Component, Object {
  /** The external ID that defines this object for joining purposes */
  environment?: string;
  /** An item in an IP routing table */
  routers?: string | Array<string> | T3_IpRoute | Array<T3_IpRoute>;
}
