import { T3_IssuedDate } from "../document/IssuedDate";
import { Account } from "../interface/Account";
import { Object } from "../interface/Object";
import { Principal } from "../interface/Principal";

// This file is autogenerated - Please do not edit 

export interface ITAssetManagementUser extends Account, Principal, Object {
  /** The external ID that defines this object for joining purposes */
  assetHistory?: string | Array<string>;
  /** Issued Date */
  assets?: string | Array<string> | T3_IssuedDate | Array<T3_IssuedDate>;
  /** The external ID that defines this object for joining purposes */
  itAssetManager?: string;
}
