import { ItsmServiceType } from "../enum/ItsmServiceType";
import { Application } from "../interface/Application";
import { Asset } from "../interface/Asset";
import { Component } from "../interface/Component";
import { Object } from "../interface/Object";

// This file is autogenerated - Please do not edit 

export interface ITSMApplication extends Application, Asset, Component, Object {
  /** ITSM Services implemented by Organization */
  service?: ItsmServiceType | Array<ItsmServiceType>;
  /** The external ID that defines this object for joining purposes */
  incidentTickets?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  providesWorkflow?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  changeTickets?: string | Array<string>;
}
