import { Object } from "../interface/Object";

// This file is autogenerated - Please do not edit 

export interface Label extends Object {
  /** The color for a Label */
  color?: string;
  /** True whe a Label is present by default */
  isDefault?: boolean;
}
