import { LocationInfo } from "../document/LocationInfo";
import { Object } from "../interface/Object";

// This file is autogenerated - Please do not edit 

export interface Location extends Object {
  /** Location code */
  code?: string;
  /** Physical Location */
  locations?: LocationInfo | Array<LocationInfo>;
  /** The external ID that defines this object for joining purposes */
  assets?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  inventoryItems?: string | Array<string>;
}
