import { Element } from "../interface/Element";
import { Object } from "../interface/Object";

// This file is autogenerated - Please do not edit 

export interface Mitigation extends Element, Object {
  /** The external ID that defines this object for joining purposes */
  countermeasures?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  techniques?: string | Array<string>;
}
