import { Endpoint } from "../document/Endpoint";
import { Component } from "../interface/Component";
import { Object } from "../interface/Object";

// This file is autogenerated - Please do not edit 

export interface NetworkService extends Component, Object {
  /** Network Service Endpoint (Listening Socket) */
  endpoints?: Endpoint | Array<Endpoint>;
}
