import { Cidr } from "@zerobias-org/types-core-js";
import { T3_RouterAssociation } from "../document/RouterAssociation";
import { OperationalStatus } from "../enum/OperationalStatus";
import { Object } from "../interface/Object";

// This file is autogenerated - Please do not edit 

export interface Network extends Object {
  /** The network/supernet that contains all subnets for this environment */
  cidr?: Cidr;
  /** Current operational state of a resource or interface. */
  status?: OperationalStatus;
  /** Describes relationship between a Router and Network */
  firewalls?: string | Array<string> | T3_RouterAssociation | Array<T3_RouterAssociation>;
  /** The external ID that defines this object for joining purposes */
  dhcpOptions?: string;
  /** The external ID that defines this object for joining purposes */
  availabilityZone?: string;
  /** Describes relationship between a Router and Network */
  router: string | T3_RouterAssociation;
  /** The external ID that defines this object for joining purposes */
  environment?: string;
}
