import { Component } from "../interface/Component";
import { Object } from "../interface/Object";

// This file is autogenerated - Please do not edit 

export interface ObjectStorage extends Component, Object {
  /** The external ID that defines this object for joining purposes */
  buckets?: string | Array<string>;
}
