import { GeoCountryDef } from "@zerobias-org/types-core-js";
import { OrganizationEntityType } from "../enum/OrganizationEntityType";
import { Contact } from "../interface/Contact";
import { Location } from "../interface/Location";
import { Object } from "../interface/Object";
import { Party } from "../interface/Party";

// This file is autogenerated - Please do not edit 

export interface Organization extends Party, Contact, Location, Object {
  /** Types of business/provider entities */
  entityType?: OrganizationEntityType;
  /** Organization DNS Domain */
  domain?: string | Array<string>;
  /** Country of an Organization */
  nationality?: GeoCountryDef | Array<GeoCountryDef>;
}
