import { T3_ComponentRole } from "../document/ComponentRole";
import { T3_PartyRole } from "../document/PartyRole";
import { PartyType } from "../enum/PartyType";
import { Contact } from "../interface/Contact";
import { Location } from "../interface/Location";
import { Object } from "../interface/Object";

// This file is autogenerated - Please do not edit 

export interface Party extends Contact, Location, Object {
  /** Types of responsible parties */
  partyType?: PartyType;
  /** Role and role type(s) responsible for a component */
  responsibleForComponent?: string | Array<string> | T3_ComponentRole | Array<T3_ComponentRole>;
  /** The external ID that defines this object for joining purposes */
  itamApp?: string;
  /** Compliance role expressed in responsibility matrix assignments responsbility to processes */
  workflowStep?: string | T3_PartyRole;
}
