import { GeoCountryDef } from "@zerobias-org/types-core-js";
import { BackgroundCheck } from "../document/BackgroundCheck";
import { EmploymentStatus } from "../enum/EmploymentStatus";
import { EmploymentType } from "../enum/EmploymentType";
import { Contact } from "../interface/Contact";
import { Location } from "../interface/Location";
import { Object } from "../interface/Object";
import { Party } from "../interface/Party";

// This file is autogenerated - Please do not edit 

export interface Person extends Party, Contact, Location, Object {
  /** Country of a person's citizenship */
  citizenship?: GeoCountryDef | Array<GeoCountryDef>;
  /** Start date for an employee or contractor */
  dateOfHire?: Date;
  /** Date of exit or termination for an employee or contractor */
  dateOfExit?: Date;
  /** Enumeration store for the type of employment */
  employmentType?: EmploymentType;
  /** Identifier for an employee. */
  employeeId?: string;
  /** Enumeration store for the current status of an employee */
  employmentStatus?: EmploymentStatus;
  /** A background check performed on a person */
  backgroundCheck?: BackgroundCheck | Array<BackgroundCheck>;
  /** The external ID that defines this object for joining purposes */
  employer?: string;
  /** The external ID that defines this object for joining purposes */
  training?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  identity?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  account?: string | Array<string>;
}
