import { CampaignStatus } from "../enum/CampaignStatus";
import { Campaign } from "../interface/Campaign";
import { Object } from "../interface/Object";

// This file is autogenerated - Please do not edit 

export interface PhishingCampaign extends Campaign, Object {
  /** Enumeration store for the current status of an Campaign */
  status?: CampaignStatus;
  /** The date when the event, ticket, or task started */
  startDate?: Date;
  /** Date of Completion expressed according ISO 8601/RFC 3339 */
  endDate?: Date;
  /** The external ID that defines this object for joining purposes */
  groups?: string | Array<string>;
}
