import { Application } from "../interface/Application";
import { Asset } from "../interface/Asset";
import { Component } from "../interface/Component";
import { Object } from "../interface/Object";

// This file is autogenerated - Please do not edit 

export interface PhysicalAccessManagementApp extends Application, Asset, Component, Object {
  /** The external ID that defines this object for joining purposes */
  zones?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  credentials?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  entries?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  schedules?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  visitors?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  sites?: string | Array<string>;
}
