import { Account } from "../interface/Account";
import { Object } from "../interface/Object";
import { Principal } from "../interface/Principal";

// This file is autogenerated - Please do not edit 

export interface PhysicalAccessManagementAccount extends Account, Principal, Object {
  /** The external ID that defines this object for joining purposes */
  hostedVisitors?: string | Array<string>;
}
