import { TimeZoneDef } from "@zerobias-org/types-core-js";
import { Location } from "../interface/Location";
import { Object } from "../interface/Object";

// This file is autogenerated - Please do not edit 

export interface PhysicalSite extends Location, Object {
  /** A time zone name */
  timeZone?: TimeZoneDef;
  /** The external ID that defines this object for joining purposes */
  zones?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  app?: string;
  /** The external ID that defines this object for joining purposes */
  entries?: string | Array<string>;
}
