import { PhysicalEntry_status } from "../enum/PhysicalEntry_status";
import { PhysicalEntry_type } from "../enum/PhysicalEntry_type";
import { Asset } from "../interface/Asset";
import { Component } from "../interface/Component";
import { Object } from "../interface/Object";
import { Resource } from "../interface/Resource";

// This file is autogenerated - Please do not edit 

export interface PhysicalEntry extends Asset, Resource, Object, Component {
  /** Type or category of physical entry point */
  entryType?: PhysicalEntry_type;
  /** Current status of the physical entry point */
  state?: PhysicalEntry_status;
  /** Maximum capacity or occupancy limit */
  capacity?: number;
  /** The external ID that defines this object for joining purposes */
  schedules?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  app?: string;
  /** The external ID that defines this object for joining purposes */
  zone?: string;
  /** The external ID that defines this object for joining purposes */
  site?: string;
}
