import { Component } from "../interface/Component";
import { Object } from "../interface/Object";

// This file is autogenerated - Please do not edit 

export interface ProofOfCompliance extends Component, Object {
  /** A pointer to a validation record (e.g., FIPS 140-2) or other compliance information */
  body?: string;
  /** The external ID that defines this object for joining purposes */
  covers?: string | Array<string>;
}
