import { Contact } from "../interface/Contact";
import { Location } from "../interface/Location";
import { Object } from "../interface/Object";
import { Organization } from "../interface/Organization";
import { Party } from "../interface/Party";

// This file is autogenerated - Please do not edit 

export interface Provider extends Organization, Party, Contact, Location, Object {
  /** The external ID that defines this object for joining purposes */
  employees?: string | Array<string>;
}
