import { URL } from "@zerobias-org/types-core-js";
import { PullRequestState } from "../enum/PullRequestState";
import { Object } from "../interface/Object";

// This file is autogenerated - Please do not edit 

export interface PullRequest extends Object {
  /** Pull Request Status */
  state?: PullRequestState;
  /** HTML / Human URL for viewing an SCM object */
  htmlUrl?: URL;
  /** URL for retrieving a diff for an SCM object */
  diffUrl?: URL;
  /** URL for patches of an SCM object */
  patchUrl?: URL;
  /** URL for related issues of an SCM object */
  issuesUrl?: URL;
  /** URL for commiting to a branch */
  commitsUrl?: URL;
  /** URL for reviewing comments of an SCM object */
  reviewCommentsUrl?: URL;
  /** URL for commiting to a branch */
  commentsUrl?: URL;
  /** URL for the status(es) of an SCM object */
  statusUrl?: URL;
  /** Whether a Pull Request is locked or not */
  locked?: boolean;
  /** Whether auto-merge is enabled for a Pull Request */
  autoMerge?: boolean;
  /** Whether a Pull Request is a draft */
  draft?: boolean;
  /** Timestamp in RFC339/ISO8601 date-time string when a PR closed */
  dateClosed?: Date;
  /** Timestamp in RFC339/ISO8601 date-time string when a PR was merged */
  dateMerged?: Date;
  /** Reason why a Pull Request is locked */
  lockReason?: string;
  /** SHA digest ID for SCM object */
  mergeCommitSha?: string;
  /** The external ID that defines this object for joining purposes */
  labels?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  reviews?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  assignee?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  repo: string;
  /** The external ID that defines this object for joining purposes */
  target: string;
  /** The external ID that defines this object for joining purposes */
  source: string;
  /** The external ID that defines this object for joining purposes */
  findings?: string;
  /** The external ID that defines this object for joining purposes */
  group?: string;
  /** The external ID that defines this object for joining purposes */
  reviewer?: string | Array<string>;
}
