import { Application } from "../interface/Application";
import { Asset } from "../interface/Asset";
import { Component } from "../interface/Component";
import { DBMS } from "../interface/DBMS";
import { Object } from "../interface/Object";

// This file is autogenerated - Please do not edit 

export interface RDBMS extends DBMS, Application, Asset, Component, Object {
  /** The external ID that defines this object for joining purposes */
  sqlDatabases?: string | Array<string>;
}
