import { URL } from "@zerobias-org/types-core-js";
import { T3_PermissionSet } from "../document/PermissionSet";
import { DataClassification } from "../enum/DataClassification";
import { Component } from "../interface/Component";
import { Object } from "../interface/Object";

// This file is autogenerated - Please do not edit 

export interface Repository extends Component, Object {
  /** Repository URL */
  repoUrl?: URL;
  /** Repository SSH URL */
  sshUrl?: URL;
  /** Repository Clone URL */
  cloneUrl?: URL;
  /** Repository License URL */
  licenseUrl?: URL;
  /** Repository HTML URL */
  licenseHtmlUrl?: URL;
  /** Boolean value indicating whether or not the repository or branch is a fork of another */
  repoIsFork?: boolean;
  /** Boolean value indicating whether or not the repository is archived or not */
  archived?: boolean;
  /** Boolean value indicating whether or not the repository has downloads */
  hasDownloads?: boolean;
  /** Boolean value indicating whether or not the repository has a wiki page */
  hasWiki?: boolean;
  /** Whether or not a component is a boundary component. */
  boundaryComponent?: boolean;
  /** Boolean value indicating whether or not the repository has the ability to receive vulnerability alerts */
  vulnerabilityAlertsEnabled?: boolean;
  /** Timestamp in RFC339/ISO8601 date-time string */
  created?: Date;
  /** Timestamp in RFC339/ISO8601 date-time string */
  pushed?: Date;
  /** Timestamp in RFC339/ISO8601 date-time string */
  updated?: Date;
  /** Timestamp in RFC339/ISO8601 date-time string */
  disabled?: Date;
  /** Classification Level of information, systems, data, or applications */
  visibility?: DataClassification;
  /** Repository Node Id */
  nodeId?: string;
  /** Repository license key */
  licenseKey?: string;
  /** Repository license name */
  licenseName?: string;
  /** License Node Id */
  licenseNodeId?: string;
  /** Software Package Data Exchange (SPDX) License ID */
  licenseSpdxId?: string;
  /** Number of repository forks */
  forkCount?: number;
  /** List of permissions for a given principal and resource */
  user?: string | Array<string> | T3_PermissionSet | Array<T3_PermissionSet>;
  /** The external ID that defines this object for joining purposes */
  pullRequests?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  owner: string;
  /** List of permissions for a given principal and resource */
  group?: string | Array<string> | T3_PermissionSet | Array<T3_PermissionSet>;
  /** The external ID that defines this object for joining purposes */
  labels?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  branches?: string | Array<string>;
}
