import { Object } from "../interface/Object";

// This file is autogenerated - Please do not edit 

export interface RepoLabel extends Object {
  /** The external ID that defines this object for joining purposes */
  repo: string;
  /** The external ID that defines this object for joining purposes */
  pullRequests?: string | Array<string>;
}
