import { Priority } from "../enum/Priority";
import { Role_accessLevel } from "../enum/Role_accessLevel";
import { Role_type } from "../enum/Role_type";
import { Object } from "../interface/Object";
import { Principal } from "../interface/Principal";

// This file is autogenerated - Please do not edit 

export interface Role extends Principal, Object {
  /** Types of roles in identity and access management systems */
  roleType?: Role_type;
  /** Priority of a task, incident, or request */
  priority?: Priority;
  /** Whether role is a built-in system role */
  isBuiltIn?: boolean;
  /** Access level classification for roles */
  accessLevel?: Role_accessLevel;
  /** The external ID that defines this object for joining purposes */
  assignees?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  app?: string | Array<string>;
}
