import { T3_IpRoute } from "../document/IpRoute";
import { T3_RouterAssociation } from "../document/RouterAssociation";
import { Asset } from "../interface/Asset";
import { Component } from "../interface/Component";
import { Object } from "../interface/Object";

// This file is autogenerated - Please do not edit 

export interface Router extends Asset, Component, Object {
  /** Describes relationship between a Router and Network */
  networks?: string | Array<string> | T3_RouterAssociation | Array<T3_RouterAssociation>;
  /** An item in an IP routing table */
  routes?: string | Array<string> | T3_IpRoute | Array<T3_IpRoute>;
  /** The external ID that defines this object for joining purposes */
  environment: string;
}
