import { TimeZoneDef } from "@zerobias-org/types-core-js";
import { Configuration } from "../interface/Configuration";
import { Object } from "../interface/Object";

// This file is autogenerated - Please do not edit 

export interface Schedule extends Configuration, Object {
  /** A time slot definition */
  timeSlots?: string | Array<string>;
  /** A time zone name */
  timeZone?: TimeZoneDef;
  /** The date when this schedule becomes effective */
  effectiveDate?: Date;
  /** The date and time this item is valid until */
  expirationDate?: Date;
  /** The external ID that defines this object for joining purposes */
  app?: string;
  /** The external ID that defines this object for joining purposes */
  credentials?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  entries?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  zones?: string | Array<string>;
}
