import { Object } from "../interface/Object";

// This file is autogenerated - Please do not edit 

export interface Secret extends Object {
  /** Secret versions */
  versions?: number;
  /** The external ID that defines this object for joining purposes */
  container?: string;
}
