import { Object } from "../interface/Object";

// This file is autogenerated - Please do not edit 

export interface SecretsContainer extends Object {
  /** The external ID that defines this object for joining purposes */
  manager?: string;
  /** The external ID that defines this object for joining purposes */
  secrets?: string | Array<string>;
}
