import { SnapshotRetentionPolicy } from "../enum/SnapshotRetentionPolicy";
import { Object } from "../interface/Object";

// This file is autogenerated - Please do not edit 

export interface Snapshot extends Object {
  /** Snapshot Retention Policy */
  retentionPolicy?: SnapshotRetentionPolicy;
  /** The external ID that defines this object for joining purposes */
  volume?: string;
}
