import { Object } from "../interface/Object";
import { Principal } from "../interface/Principal";

// This file is autogenerated - Please do not edit 

export interface SourceCodeMgmtPrincipal extends Principal, Object {
  /** The external ID that defines this object for joining purposes */
  branchProtectionRestricted?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  branchProtectionBypass?: string | Array<string>;
}
