import { Finding } from "../interface/Finding";
import { Object } from "../interface/Object";

// This file is autogenerated - Please do not edit 

export interface SourceCodeMgmtFinding extends Finding, Object {
  /** The external ID that defines this object for joining purposes */
  branch?: string;
  /** The external ID that defines this object for joining purposes */
  pullRequest?: string;
}
