import { T3_PermissionSet } from "../document/PermissionSet";
import { Group } from "../interface/Group";
import { Object } from "../interface/Object";
import { Principal } from "../interface/Principal";
import { SourceCodeMgmtPrincipal } from "../interface/SourceCodeMgmtPrincipal";

// This file is autogenerated - Please do not edit 

export interface SourceCodeMgmtGroup extends Group, SourceCodeMgmtPrincipal, Principal, Object {
  /** List of permissions for a given principal and resource */
  repo?: string | Array<string> | T3_PermissionSet | Array<T3_PermissionSet>;
}
