import { Asset } from "../interface/Asset";
import { Component } from "../interface/Component";
import { Database } from "../interface/Database";
import { NetworkService } from "../interface/NetworkService";
import { Object } from "../interface/Object";

// This file is autogenerated - Please do not edit 

export interface SqlDatabase extends Database, Asset, NetworkService, Component, Object {
  /** The external ID that defines this object for joining purposes */
  schemas?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  rdbms?: string;
}
