import { Object } from "../interface/Object";

// This file is autogenerated - Please do not edit 

export interface SqlSchema extends Object {
  /** The external ID that defines this object for joining purposes */
  tables?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  database?: string;
}
