import { Object } from "../interface/Object";

// This file is autogenerated - Please do not edit 

export interface SqlTable extends Object {
  /** The external ID that defines this object for joining purposes */
  columns?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  schema?: string;
}
