import { KeyPair_type } from "../enum/KeyPair_type";
import { Object } from "../interface/Object";

// This file is autogenerated - Please do not edit 

export interface SSHKeyPair extends Object {
  /** The fingerprint of the key pair */
  fingerprint?: string;
  /** Key Pair Type */
  keyType?: KeyPair_type;
}
