import { Group } from "../interface/Group";
import { Object } from "../interface/Object";
import { Principal } from "../interface/Principal";
import { SsoPrincipal } from "../interface/SsoPrincipal";

// This file is autogenerated - Please do not edit 

export interface SsoGroup extends Group, SsoPrincipal, Principal, Object {
}
