import { Account } from "../interface/Account";
import { Object } from "../interface/Object";
import { Principal } from "../interface/Principal";
import { SsoPrincipal } from "../interface/SsoPrincipal";

// This file is autogenerated - Please do not edit 

export interface SsoUser extends Account, SsoPrincipal, Principal, Object {
}
