import { T3_MitigationStrategy } from "../document/MitigationStrategy";
import { Element } from "../interface/Element";
import { Object } from "../interface/Object";

// This file is autogenerated - Please do not edit 

export interface Tactic extends Element, Object {
  /** The external ID that defines this object for joining purposes */
  parentTactic?: string;
  /** The external ID that defines this object for joining purposes */
  subTactics?: string | Array<string>;
  /** Mitigation Strategy */
  mitigatedBy?: string | Array<string> | T3_MitigationStrategy | Array<T3_MitigationStrategy>;
  /** The external ID that defines this object for joining purposes */
  techniques?: string | Array<string>;
}
