import { Element } from "../interface/Element";
import { Object } from "../interface/Object";

// This file is autogenerated - Please do not edit 

export interface Technique extends Element, Object {
  /** The platform the technique is applicable to */
  platforms?: string | Array<string>;
  /** The permissions required to execute the technique */
  permissions?: string;
  /** The external ID that defines this object for joining purposes */
  disablesCyberArtifacts?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  interpretsCyberArtifacts?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  runsCyberArtifacts?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  mayRunCyberArtifacts?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  enumeratesCyberArtifacts?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  mayExecuteCyberArtifacts?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  tactics?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  mayProduceCyberArtifacts?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  mayTransferCyberArtifacts?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  connectsCyberArtifacts?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  createsCyberArtifacts?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  copiesCyberArtifacts?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  loadsCyberArtifacts?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  queriesCyberArtifacts?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  mayModifyCyberArtifacts?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  obfuscatesCyberArtifacts?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  unmountsCyberArtifacts?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  forgesCyberArtifacts?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  usesCyberArtifacts?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  injectsCyberArtifacts?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  mayAccessCyberArtifacts?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  parentTechnique?: string;
  /** The external ID that defines this object for joining purposes */
  subTechniques?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  producesCyberArtifacts?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  mayAddCyberArtifacts?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  mayCreateCyberArtifacts?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  installsCyberArtifacts?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  addsCyberArtifacts?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  executesCyberArtifacts?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  mitigations?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  mayInvokeCyberArtifacts?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  invokesCyberArtifacts?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  modifiesCyberArtifacts?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  cyberArtifacts?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  accessesCyberArtifacts?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  readsCyberArtifacts?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  deletesCyberArtifacts?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  enablesCyberArtifacts?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  hidesCyberArtifacts?: string | Array<string>;
}
