import { Email } from "@zerobias-org/types-core-js";
import { T3_ComponentRole } from "../document/ComponentRole";
import { Object } from "../interface/Object";

// This file is autogenerated - Please do not edit 

export interface TicketingUser extends Object {
  /** A valid email */
  email?: Email | Array<Email>;
  /** Role and role type(s) responsible for a component */
  ticketsReported?: string | Array<string> | T3_ComponentRole | Array<T3_ComponentRole>;
  /** Role and role type(s) responsible for a component */
  ticketsAssigned?: string | Array<string> | T3_ComponentRole | Array<T3_ComponentRole>;
  /** Role and role type(s) responsible for a component */
  ticketsApproved?: string | Array<string> | T3_ComponentRole | Array<T3_ComponentRole>;
}
