import { T3_ComponentRole } from "../document/ComponentRole";
import { Priority } from "../enum/Priority";
import { TicketStatus } from "../enum/TicketStatus";
import { Object } from "../interface/Object";

// This file is autogenerated - Please do not edit 

export interface Ticket extends Object {
  /** Ticket Status */
  ticketStatus?: TicketStatus;
  /** Timestamp in RFC339/ISO8601 date-time string */
  opened?: Date | Array<Date>;
  /** Timestamp in RFC339/ISO8601 date-time string */
  started?: Date | Array<Date>;
  /** Timestamp in RFC339/ISO8601 date-time string */
  closed?: Date | Array<Date>;
  /** Timestamp in RFC339/ISO8601 date-time string */
  modified?: Date | Array<Date>;
  /** Timestamp in RFC339/ISO8601 date-time string */
  stopped?: Date | Array<Date>;
  /** Priority of a task, incident, or request */
  priority?: Priority;
  /** The external ID that defines this object for joining purposes */
  parent?: string;
  /** The external ID that defines this object for joining purposes */
  subTickets?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  impactedComponent?: string | Array<string>;
  /** Role and role type(s) responsible for a component */
  reporter?: string | Array<string> | T3_ComponentRole | Array<T3_ComponentRole>;
  /** Role and role type(s) responsible for a component */
  assignee?: string | Array<string> | T3_ComponentRole | Array<T3_ComponentRole>;
  /** Role and role type(s) responsible for a component */
  approvers?: string | Array<string> | T3_ComponentRole | Array<T3_ComponentRole>;
}
