import { Group } from "../interface/Group";
import { Object } from "../interface/Object";
import { Principal } from "../interface/Principal";

// This file is autogenerated - Please do not edit 

export interface TrainingGroup extends Group, Principal, Object {
  /** The external ID that defines this object for joining purposes */
  trainingCampaigns?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  phishingCampaigns?: string | Array<string>;
}
