import { EnrollmentStatus } from "../enum/EnrollmentStatus";
import { TestResult } from "../enum/TestResult";
import { Object } from "../interface/Object";

// This file is autogenerated - Please do not edit 

export interface TrainingRecord extends Object {
  /** Date of enrollment */
  dateEnrolled?: Date;
  /** The date when the event, ticket, or task started */
  dateStarted?: Date;
  /** Date of Completion expressed according ISO 8601/RFC 3339 */
  dateCompleted?: Date;
  /** Result of any assessment */
  testResult: TestResult;
  /** Training Record Enrollment Status */
  enrollmentStatus?: EnrollmentStatus;
  /** The external ID that defines this object for joining purposes */
  person?: string;
  /** The external ID that defines this object for joining purposes */
  app?: string;
  /** The external ID that defines this object for joining purposes */
  account?: string;
  /** The external ID that defines this object for joining purposes */
  module?: string;
}
