import { URL } from "@zerobias-org/types-core-js";
import { CompetencyType } from "../enum/CompetencyType";
import { TrainingModuleType } from "../enum/TrainingModuleType";
import { Object } from "../interface/Object";

// This file is autogenerated - Please do not edit 

export interface TrainingModule extends Object {
  /** Competency Type as prescribed by DoD 8570 for Information Assurance (IA) or the Office of Personnel Management (OPM) */
  competencyType?: CompetencyType | Array<CompetencyType>;
  /** Name of a training module provider such as a credentialing organization, institution, or publisher */
  provider?: string;
  /** The date when a component was purchased */
  purchaseDate?: Date;
  /** The date when a component was published */
  publishDate?: Date;
  /** A valid URL */
  policyUrl?: URL;
  /** Training Module Type, such as video training, interactive/gaming, or coursework */
  moduleType?: TrainingModuleType;
  /** The external ID that defines this object for joining purposes */
  campaigns?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  record?: string;
  /** The external ID that defines this object for joining purposes */
  app?: string;
  /** The external ID that defines this object for joining purposes */
  competencies?: string | Array<string>;
}
