import { Component } from "../interface/Component";
import { Object } from "../interface/Object";

// This file is autogenerated - Please do not edit 

export interface Validation extends Component, Object {
  /** Validating body assigned attesting compliance, such as NIST, FIPS, ISO, etc */
  body?: string;
  /** The external ID that defines this object for joining purposes */
  components?: string | Array<string>;
}
