import { T3_BlockDevice } from "../document/BlockDevice";
import { Vm_hypervisor } from "../enum/Vm_hypervisor";
import { AppEnvironment } from "../interface/AppEnvironment";
import { Asset } from "../interface/Asset";
import { Component } from "../interface/Component";
import { Object } from "../interface/Object";

// This file is autogenerated - Please do not edit 

export interface VirtualMachine extends AppEnvironment, Asset, Component, Object {
  /** Virtual Machine hypervisor type */
  hypervisor?: Vm_hypervisor;
  /** Whether or not a component is a boundary component. */
  boundaryComponent?: boolean;
  /** The external ID that defines this object for joining purposes */
  elasticInterfaces?: string | Array<string>;
  /** Block device */
  volumes?: string | Array<string> | T3_BlockDevice | Array<T3_BlockDevice>;
}
