import { Contact } from "../interface/Contact";
import { Location } from "../interface/Location";
import { Object } from "../interface/Object";
import { Party } from "../interface/Party";
import { Person } from "../interface/Person";
import { Principal } from "../interface/Principal";

// This file is autogenerated - Please do not edit 

export interface Visitor extends Person, Principal, Party, Object, Contact, Location {
  /** Whether an escort is required for this visitor */
  escortRequired?: boolean;
  /** Whether the visitor is currently checked in */
  checkedIn?: boolean;
  /** Date until which the visitor access is valid */
  validUntil?: Date;
  /** Time when the visitor checked in */
  checkInTime?: Date;
  /** Time when the visitor checked out */
  checkOutTime?: Date;
  /** The purpose or reason for the visitor's visit */
  visitPurpose?: string;
  /** Company or organization the visitor represents */
  company?: string;
  /** The external ID that defines this object for joining purposes */
  allowedAreas?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  visitorPass?: string;
  /** The external ID that defines this object for joining purposes */
  host?: string;
  /** The external ID that defines this object for joining purposes */
  app?: string;
}
