import { BlockDevice, T3_BlockDevice } from "../document/BlockDevice";
import { Asset } from "../interface/Asset";
import { Component } from "../interface/Component";
import { CryptoDevice } from "../interface/CryptoDevice";
import { Object } from "../interface/Object";

// This file is autogenerated - Please do not edit 

export interface Volume extends Asset, CryptoDevice, Object, Component {
  /** The size of the capacity, in GB */
  size?: number;
  /** Input/output operations per second (IOPS) */
  iops?: number;
  /** Block device */
  blockDevice?: BlockDevice | Array<BlockDevice>;
  /** The external ID that defines this object for joining purposes */
  snapshots?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  availabilityZone?: string;
  /** Block device */
  virtualMachine?: string | T3_BlockDevice;
}
