import { Object } from "../interface/Object";

// This file is autogenerated - Please do not edit 

export interface Weakness extends Object {
  /** A extended description for a weakness */
  extendedDescription?: string;
  /** The external ID that defines this object for joining purposes */
  testCases?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  vulnerabilities?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  attackPatterns?: string | Array<string>;
}
