import { Object } from "../interface/Object";

// This file is autogenerated - Please do not edit 

export interface WebGatewayOperation extends Object {
  /** The path of the resource */
  path?: string;
  /** The method of the operation */
  method?: string;
  /** The external ID that defines this object for joining purposes */
  resource?: string;
}
