import { WebGatewayType } from "../enum/WebGatewayType";
import { Object } from "../interface/Object";

// This file is autogenerated - Please do not edit 

export interface WebGateway extends Object {
  /** The web gateway type */
  type?: WebGatewayType;
  /** The external ID that defines this object for joining purposes */
  resources?: string | Array<string>;
}
