import { Object } from "../interface/Object";
import { Ticket } from "../interface/Ticket";

// This file is autogenerated - Please do not edit 

export interface WorkflowTicket extends Ticket, Object {
  /** The external ID that defines this object for joining purposes */
  workflow?: string;
  /** The external ID that defines this object for joining purposes */
  stepTicket?: string | Array<string>;
}
