import { Object } from "../interface/Object";

// This file is autogenerated - Please do not edit 

export interface Workflow extends Object {
  /** The external ID that defines this object for joining purposes */
  initialStep?: string;
  /** The external ID that defines this object for joining purposes */
  workflowApplication?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  workflowTicket?: string | Array<string>;
}
