import { T3_PartyRole } from "../document/PartyRole";
import { T3_Transition } from "../document/Transition";
import { Object } from "../interface/Object";

// This file is autogenerated - Please do not edit 

export interface WorkflowStep extends Object {
  /** Conditions required to transition workflow steps */
  nextStep?: string | Array<string> | T3_Transition | Array<T3_Transition>;
  /** Conditions required to transition workflow steps */
  previousStep?: string | Array<string> | T3_Transition | Array<T3_Transition>;
  /** Compliance role expressed in responsibility matrix assignments responsbility to processes */
  party?: string | Array<string> | T3_PartyRole | Array<T3_PartyRole>;
  /** The external ID that defines this object for joining purposes */
  stepTicket?: string | Array<string>;
}
