// This file is autogenerated - Please do not edit 

export enum AccessCredential_level {
  /** Temporary visitor access with minimal permissions */
  VISITOR = "VISITOR",
  /** Standard employee access to assigned areas */
  EMPLOYEE = "EMPLOYEE",
  /** Contractor access with time-limited permissions */
  CONTRACTOR = "CONTRACTOR",
  /** Supervisory access with extended area permissions */
  SUPERVISOR = "SUPERVISOR",
  /** Security personnel access to restricted areas */
  SECURITY = "SECURITY",
  /** Administrative access to all areas and systems */
  ADMIN = "ADMIN",
  /** Emergency access for critical situations */
  EMERGENCY = "EMERGENCY",
}
