// This file is autogenerated - Please do not edit 

export enum AccessCredential_type {
  /** Physical access card or badge */
  CARD = "CARD",
  /** Key fob or proximity token */
  FOB = "FOB",
  /** Mobile device credential or app */
  MOBILE = "MOBILE",
  /** Biometric credential (fingerprint, facial recognition, etc.) */
  BIOMETRIC = "BIOMETRIC",
  /** Personal identification number */
  PIN = "PIN",
  /** Security token or hardware key */
  TOKEN = "TOKEN",
  /** Digital certificate */
  CERTIFICATE = "CERTIFICATE",
  /** QR code credential */
  QR_CODE = "QR_CODE",
  /** Barcode credential */
  BARCODE = "BARCODE",
  /** Near-field communication credential */
  NFC = "NFC",
  /** Bluetooth-based credential */
  BLUETOOTH = "BLUETOOTH",
  /** Other or vendor-specific credential type */
  OTHER = "OTHER",
}
