// This file is autogenerated - Please do not edit 

export enum AccessLevel {
  /** No access granted */
  NONE = "NONE",
  /** Guest access with limited permissions */
  GUEST = "GUEST",
  /** Read-only access without modification rights */
  READ_ONLY = "READ_ONLY",
  /** Standard user access with basic permissions */
  USER = "USER",
  /** Enhanced user access with extended permissions */
  POWER_USER = "POWER_USER",
  /** Supervisory access with team management rights */
  SUPERVISOR = "SUPERVISOR",
  /** Manager access with department oversight */
  MANAGER = "MANAGER",
  /** Administrative access with system management rights */
  ADMIN = "ADMIN",
  /** Super administrator with full system control */
  SUPER_ADMIN = "SUPER_ADMIN",
  /** Emergency access for critical situations */
  EMERGENCY = "EMERGENCY",
}
