// This file is autogenerated - Please do not edit 

export enum AccountType {
  /** System */
  SYSTEM = "SYSTEM",
  /** Temporary */
  TEMPORARY = "TEMPORARY",
  /** User */
  USER = "USER",
  /** Emergency */
  EMERGENCY = "EMERGENCY",
  /** Guest */
  GUEST = "GUEST",
}
