// This file is autogenerated - Please do not edit 

export enum AccountStatus {
  /** Active */
  ACTIVE = "ACTIVE",
  /** Inactive */
  INACTIVE = "INACTIVE",
  /** Disabled */
  DISABLED = "DISABLED",
  /** Locked */
  LOCKED = "LOCKED",
  /** Expired */
  EXPIRED = "EXPIRED",
}
