// This file is autogenerated - Please do not edit 

export enum AddressType {
  /** Home Address */
  HOME = "HOME",
  /** Office Address */
  OFFICE = "OFFICE",
  /** Mailing Address */
  MAILING = "MAILING",
  /** Billing Address */
  BILLING = "BILLING",
  /** Receiving Address */
  RECEIVING = "RECEIVING",
  /** Agent Address */
  AGENT = "AGENT",
  /** Other */
  OTHER = "OTHER",
}
