// This file is autogenerated - Please do not edit 

export enum AdminStatus {
  /** Enabled/Up */
  ENABLED = "ENABLED",
  /** Disabled/Down */
  DISABLED = "DISABLED",
  /** Testing */
  TESTING = "TESTING",
}
