// This file is autogenerated - Please do not edit 

export enum AssetHistory_operation {
  /** */
  CHECK_IN = "CHECK_IN",
  /** */
  CHECK_OUT = "CHECK_OUT",
  /** */
  LEAVE_SERVICE = "LEAVE_SERVICE",
  /** */
  ENTER_SERVICE = "ENTER_SERVICE",
  /** */
  MAINTENANCE = "MAINTENANCE",
}
