// This file is autogenerated - Please do not edit 

export enum Asset_type {
  /** LAPTOP */
  LAPTOP = "LAPTOP",
  /** DESKTOP */
  DESKTOP = "DESKTOP",
  /** MOBILE */
  MOBILE = "MOBILE",
  /** TABLET */
  TABLET = "TABLET",
  /** Certificate Authority */
  CA = "CA",
  /** End-entity Certificate (TLS) */
  ENTITY = "ENTITY",
  /** Firewall */
  FIREWALL = "FIREWALL",
  /** Unknown */
  UNKNOWN = "UNKNOWN",
}
