// This file is autogenerated - Please do not edit 

export enum Asset_criticality {
  /** Affects the company's mission and might noticeably affect corporate profit-and-loss statements. */
  MISSION_CRITICAL = "MISSION_CRITICAL",
  /** Affects the mission of a specific business unit and its profit-and-loss statements. */
  UNIT_CRITICAL = "UNIT_CRITICAL",
  /** Might not hinder the mission, but affects high-importance processes. Measurable losses can be quantified in the case of outages. */
  HIGH = "HIGH",
  /** Impact on processes is likely. Losses are low or immeasurable, but brand damage or upstream losses are likely. */
  MEDIUM = "MEDIUM",
  /** Impact on business processes isn't measurable. Neither brand damage nor upstream losses are likely. Localized impact on a single team is likely. */
  LOW = "LOW",
  /** No business owner, team, or process that's associated with this workload can justify any investment in the ongoing management of the workload. */
  UNSUPPORTED = "UNSUPPORTED",
}
