// This file is autogenerated - Please do not edit 

export enum Asset_status {
  /** Asset is active and in use. In use by someone or something. */
  ACTIVE = "ACTIVE",
  /** Asset is available for assign. */
  AVAILABLE = "AVAILABLE",
  /** Asset is unavailable for assign (needs repair, configure, etc). */
  UNAVAILABLE = "UNAVAILABLE",
  /** Asset is retired and no longer in service. */
  RETIRED = "RETIRED",
}
