// This file is autogenerated - Please do not edit 

export enum AuthType {
  /** None */
  NONE = "NONE",
  /** One-Time-Password (OTP) */
  OTP = "OTP",
  /** Time-Based OTP (TOTP) */
  TOTP = "TOTP",
  /** Push to mobile applicaton */
  PUSH = "PUSH",
  /** Mobile SMS */
  SMS = "SMS",
  /** Email */
  EMAIL = "EMAIL",
  /** Fingerprint, face, retina */
  BIOMETRIC = "BIOMETRIC",
  /** Other */
  OTHER = "OTHER",
  /** Phone call MFA */
  PHONE = "PHONE",
  /** Password-based authentication */
  PASSWORD = "PASSWORD",
  /** Fast Identity Only (FIDO Alliance) v1 */
  FIDO = "FIDO",
  /** Fast Identity Only (FIDO Alliance) v2 */
  FIDO2 = "FIDO2",
  /** OAuth Token */
  OAUTH = "OAUTH",
  /** OpenID Connect */
  OIDC = "OIDC",
  /** Security Alliance Markup Language v1 */
  SAML = "SAML",
  /** Security Alliance Markup Language v2 */
  SAMLv2 = "SAMLv2",
  /** PIN */
  PIN = "PIN",
  /** Hardware based cryptographic device */
  HW_CRYPTO_DEVICE = "HW_CRYPTO_DEVICE",
  /** Software based cryptographic device */
  SW_CRYPTO_DEVICE = "SW_CRYPTO_DEVICE",
}
