// This file is autogenerated - Please do not edit 

export enum BackgroundCheckType {
  /** Criminal State */
  CRIMINAL_STATE = "CRIMINAL_STATE",
  /** Criminal Federal */
  CRIMINAL_FEDERAL = "CRIMINAL_FEDERAL",
  /** Financial */
  FINANCIAL = "FINANCIAL",
  /** Drug */
  DRUG = "DRUG",
  /** Motor vehicle */
  DMV = "DMV",
  /** Education */
  EDUCATION = "EDUCATION",
  /** Identity */
  IDENTITY = "IDENTITY",
  /** Other */
  OTHER = "OTHER",
}
