// This file is autogenerated - Please do not edit 

export enum BackupType {
  /** Full Backup */
  FULL = "FULL",
  /** Differential Backup */
  DIFFERENTIAL = "DIFFERENTIAL",
  /** Incremental Backup */
  INCREMENTAL = "INCREMENTAL",
}
