// This file is autogenerated - Please do not edit 

export enum Backup_mediaType {
  /** Digital Linear Tape (DLT) */
  TAPE = "TAPE",
  /** Cloud Storage */
  CLOUD = "CLOUD",
  /** Object Storage */
  OBJECT = "OBJECT",
  /** Portable Drive */
  PORTABLE = "PORTABLE",
  /** Optical Media */
  OPTICAL = "OPTICAL",
  /** Flash Drive */
  FLASH = "FLASH",
  /** Backup Appliance */
  APPLIANCE = "APPLIANCE",
}
