// This file is autogenerated - Please do not edit 

export enum BackupLocationType {
  /** Offsite storage */
  OFFSITE = "OFFSITE",
  /** Primary data processing location */
  PRIMARY = "PRIMARY",
  /** Alternate data processing location */
  ALTERNATE = "ALTERNATE",
  /** Other location */
  OTHER = "OTHER",
}
