// This file is autogenerated - Please do not edit 

export enum BackupState {
  /** Pending */
  PENDING = "PENDING",
  /** Running */
  RUNNING = "RUNNING",
  /** Aborted */
  ABORTED = "ABORTED",
  /** Completed */
  COMPLETED = "COMPLETED",
  /** Failed */
  FAILED = "FAILED",
}
