// This file is autogenerated - Please do not edit 

export enum CampaignStatus {
  /** Created */
  CREATED = "CREATED",
  /** Enrolling */
  ENROLLING = "ENROLLING",
  /** In Progress */
  IN_PROGRESS = "IN_PROGRESS",
  /** Completed */
  COMPLETED = "COMPLETED",
  /** Cancelled */
  CANCELLED = "CANCELLED",
  /** Closed */
  CLOSED = "CLOSED",
}
