// This file is autogenerated - Please do not edit 

export enum CapecAbstraction {
  /** Standard */
  STANDARD = "STANDARD",
  /** Detailed */
  DETAILED = "DETAILED",
  /** Meta */
  META = "META",
}
