// This file is autogenerated - Please do not edit 

export enum CertificateStatus {
  /** The request was received and the certificate is pending validation */
  PENDING_VALIDATION = "PENDING_VALIDATION",
  /** The certificate has been issued */
  ISSUED = "ISSUED",
  /** The request failed and the certificate could not be issued */
  FAILED = "FAILED",
  /** The validation of the certificate timed out */
  VALIDATION_TIMED_OUT = "VALIDATION_TIMED_OUT",
  /** The certificate has been revoked */
  REVOKED = "REVOKED",
  /** The certificate has expired */
  EXPIRED = "EXPIRED",
  /** The certificate is inactive */
  INACTIVE = "INACTIVE",
}
