// This file is autogenerated - Please do not edit 

export enum ChangeType {
  /** Low risk and low impact change that is pre-defined and pre-approved by an organizations Change Advisory Board (CAB) */
  STANDARD = "STANDARD",
  /** Non-trivial changes that do not occur frequently but this undergoes every stage of change lifecycle including change Change Advisory Board (CAB) approval */
  MINOR_CHANGE = "MINOR_CHANGE",
  /** High risk and high impact change that could interrupt production live environments if not planned properly which at a minimum requires Change Advisory Board (CAB) approval and potentially external stakeholders as defined by the organization */
  MAJOR_CHANGE = "MAJOR_CHANGE",
  /** Emergency changes are unexpected disruptions that need to be resolved as soon as possible */
  EMERGENCY_CHANGE = "EMERGENCY_CHANGE",
}
