// This file is autogenerated - Please do not edit 

export enum ChangeApprovalType {
  /** Security Approval */
  SECURITY = "SECURITY",
  /** Manager Approval */
  MANAGER = "MANAGER",
  /** Change Advisory Board Approval */
  CAB = "CAB",
  /** Change Committee Approval */
  COMMITTEE = "COMMITTEE",
  /** Customer Approval */
  CUSTOMER = "CUSTOMER",
  /** Budget/Finance Approval */
  FINANCE = "FINANCE",
  /** Human Resources Approval */
  HR = "HR",
  /** Compliance Approval */
  COMPLIANCE = "COMPLIANCE",
}
