// This file is autogenerated - Please do not edit 

export enum CipherPadding {
  /** */
  NoPadding = "NoPadding",
  /** */
  PKCS5Padding = "PKCS5Padding",
  /** */
  ISO10126Padding = "ISO10126Padding",
  /** */
  SSL3Padding = "SSL3Padding",
}
