// This file is autogenerated - Please do not edit 

export enum CipherKeyGenerator {
  /** */
  AES = "AES",
  /** */
  Blowfish = "Blowfish",
  /** */
  DES = "DES",
  /** */
  DESede = "DESede",
  /** */
  HmacMD2 = "HmacMD2",
  /** */
  HmacMD5 = "HmacMD5",
  /** */
  HmacSHA1 = "HmacSHA1",
  /** */
  MARS = "MARS",
  /** */
  RC2 = "RC2",
  /** */
  RC4 = "RC4",
  /** */
  Seal = "Seal",
  /** */
  Key = "Key",
}
