// This file is autogenerated - Please do not edit 

export enum CipherAlgorithm {
  /** */
  RC4 = "RC4",
  /** */
  AES = "AES",
  /** */
  Blowfish = "Blowfish",
  /** */
  DES = "DES",
  /** */
  DESede = "DESede",
  /** */
  MARS = "MARS",
  /** */
  PBEWithMd2AndDes = "PBEWithMd2AndDes",
  /** */
  PBEWithMd2AndRc2 = "PBEWithMd2AndRc2",
  /** */
  PBEWithMd2AndTripleDes = "PBEWithMd2AndTripleDes",
  /** */
  PBEWithMd2And128BitRc2 = "PBEWithMd2And128BitRc2",
  /** */
  PBEWithMd2And128BitRc4 = "PBEWithMd2And128BitRc4",
  /** */
  PBEWithMd2And2KeyTripleDes = "PBEWithMd2And2KeyTripleDes",
  /** */
  PBEWithMd5AndDes = "PBEWithMd5AndDes",
  /** */
  PBEWithMd5AndRc2 = "PBEWithMd5AndRc2",
  /** */
  PBEWithMd5AndTripleDes = "PBEWithMd5AndTripleDes",
  /** */
  PBEWithMd5And128BitRc2 = "PBEWithMd5And128BitRc2",
  /** */
  PBEWithMd5And128BitRc4 = "PBEWithMd5And128BitRc4",
  /** */
  PBEWithMd5And2KeyTripleDes = "PBEWithMd5And2KeyTripleDes",
  /** */
  PBEWithShaAndDes = "PBEWithShaAndDes",
  /** */
  PBEWithShaAndRc2 = "PBEWithShaAndRc2",
  /** */
  PBEWithShaAndTripleDes = "PBEWithShaAndTripleDes",
  /** */
  PBEWithShaAnd128BitRc2 = "PBEWithShaAnd128BitRc2",
  /** */
  PBEWithShaAnd128BitRc4 = "PBEWithShaAnd128BitRc4",
  /** */
  PBEWithShaAnd2KeyTripleDes = "PBEWithShaAnd2KeyTripleDes",
  /** */
  PBEWithSha1AndDes = "PBEWithSha1AndDes",
  /** */
  PBEWithSha1AndRc2 = "PBEWithSha1AndRc2",
  /** */
  PBEWithSha1AndTripleDes = "PBEWithSha1AndTripleDes",
  /** */
  PBEWithSha1And128BitRc2 = "PBEWithSha1And128BitRc2",
  /** */
  PBEWithSha1And128BitRc4 = "PBEWithSha1And128BitRc4",
  /** */
  PBEWithSha1And2KeyTripleDes = "PBEWithSha1And2KeyTripleDes",
  /** */
  RC2 = "RC2",
  /** */
  RSA = "RSA",
  /** */
  Seal = "Seal",
}
