// This file is autogenerated - Please do not edit 

export enum CipherMode {
  /** */
  ECB = "ECB",
  /** */
  CBC = "CBC",
  /** */
  CFB = "CFB",
  /** */
  CTR = "CTR",
  /** */
  OFB = "OFB",
  /** */
  PCBC = "PCBC",
  /** */
  CTS = "CTS",
  /** */
  GCM = "GCM",
}
