// This file is autogenerated - Please do not edit 

export enum CompetencyType {
  /** IA Technical Level I */
  DOD_IAT_Level_I = "DOD_IAT_Level_I",
  /** IA Technical Level II */
  DOD_IAT_Level_II = "DOD_IAT_Level_II",
  /** IA Technical Level III */
  DOD_IAT_Level_III = "DOD_IAT_Level_III",
  /** IA Manager Level I */
  DOD_IAM_Level_I = "DOD_IAM_Level_I",
  /** IA Manager Level II */
  DOD_IAM_Level_II = "DOD_IAM_Level_II",
  /** IA Manager Level III */
  DOD_IAM_Level_III = "DOD_IAM_Level_III",
  /** IA Systems Architect and Engineer I */
  DOD_IASAE_I = "DOD_IASAE_I",
  /** IA Systems Architect and Engineer II */
  DOD_IASAE_II = "DOD_IASAE_II",
  /** IA Systems Architect and Engineer III */
  DOD_IASAE_III = "DOD_IASAE_III",
  /** Cyber Security Service Provider Analyst */
  DOD_CSSP_Analyst = "DOD_CSSP_Analyst",
  /** Cyber Security Service Provider Infrastructure Support */
  DOD_CSSP_Infrastructure_Support = "DOD_CSSP_Infrastructure_Support",
  /** Cyber Security Service Provider Incident Responder */
  DOD_CSSP_Incident_Responder = "DOD_CSSP_Incident_Responder",
  /** Cyber Security Service Provider Auditor */
  DOD_CSSP_Auditor = "DOD_CSSP_Auditor",
  /** Cyber Security Service Provider Manager */
  DOD_CSSP_Manager = "DOD_CSSP_Manager",
  /** Knowledge of tools, equipment, and technologies used to help individuals with disabilities use computer equipment and software */
  ACCESSIBILITY = "ACCESSIBILITY",
  /** Knowledge of the laws, principles, and procedures used in apprehending a criminal suspect, including polices for pursuit and proper use of force and capture such as Miranda rights */
  ARREST = "ARREST",
  /** Knowledge of guidelines, regulations, and procedures associated with an accident investigation including preservation of accident scene, root cause analysis, and evidence detection and handling */
  ACCIDENT_INVESTIGATION = "ACCIDENT_INVESTIGATION",
  /** Holds self and others accountable for measurable high-quality, timely, and cost-effective results Determines objectives, sets priorities, and delegates work Accepts responsibility for mistakes Complies with established control systems and rules */
  ACCOUNTABILITY = "ACCOUNTABILITY",
  /** Knowledge of traditional accounting practices including accrual, obligations, and costs methods */
  ACCOUNTING = "ACCOUNTING",
  /** Knowledge of general ledger accounting and the control_AND_subsidiary account relationships and reconciliation techniques, including accounts receivable, accounts payable, and disbursing officers accountability */
  ACCOUNTING_OPERATIONS = "ACCOUNTING_OPERATIONS",
  /** Knowledge of the principles and methods for developing an integrated acquisition management plan that describes the business, technical, and support strategies, including the relationship between the acquisition phases, work efforts, and key program events (for example, decision points, contract awards, test activities) */
  ACQUISITION_STRATEGY = "ACQUISITION_STRATEGY",
  /** Knowledge of planning, coordination, and execution of business functions, resource allocation, and production */
  ADMINISTRATION_AND_MANAGEMENT = "ADMINISTRATION_AND_MANAGEMENT",
  /** Knowledge of state and Federal administrative laws, including procedures, regulations, guidelines, and precedents related to case preparation and settlements */
  ADMINISTRATIVE_LAW = "ADMINISTRATIVE_LAW",
  /** Knowledge of the concepts, principles, and theories of aerodynamics or space environments related to the design, development, testing, analysis, application, and utilization of aerospace and aeronautical devices, vehicles, systems, and equipment */
  AEROSPACE_ENGINEERING = "AEROSPACE_ENGINEERING",
  /** Bends, stretches, twists, or reaches out with the body, arms, or legs */
  AGILITY = "AGILITY",
  /** Knowledge of aircraft engines, parts, and systems, including their designs, uses, repair, and maintenance */
  AIRCRAFT_MAINTENANCE = "AIRCRAFT_MAINTENANCE",
  /** Knowledge of ammunition and explosives and their uses, interactions, dangers, production, handling, storage, and disposal */
  AMMUNITION_AND_EXPLOSIVES = "AMMUNITION_AND_EXPLOSIVES",
  /** Knowledge of the care and handling of animals, including feeding, controlling, restraint, health, and reproduction */
  ANIMAL_HUSBANDRY = "ANIMAL_HUSBANDRY",
  /** Selects and understands procedures, machines, or tools that will produce the desired results; identifies or solves problems in machines, computers, or other technologies as they are related to performing tasks */
  APPLIES_TECHNOLOGY_TO_TASKS = "APPLIES_TECHNOLOGY_TO_TASKS",
  /** Knowledge of the concepts, principles, theories, and practices used in the planning, design, construction, and maintenance of buildings or other structures, taking into consideration aesthetic and functional concerns */
  ARCHITECTURE = "ARCHITECTURE",
  /** Performs computations such as addition, subtraction, multiplication, and division correctly using whole numbers, fractions, decimals, and percentages */
  ARITHMETIC = "ARITHMETIC",
  /** Performs computations such as addition, subtraction, multiplication, and division correctly; solves practical problems by choosing appropriately from a variety of mathematical techniques such as formulas and percentages */
  ARITHMETIC_AND_MATHEMATICAL_REASONING = "ARITHMETIC_AND_MATHEMATICAL_REASONING",
  /** Knowledge of the principles, methods, and tools used to design systems that perform human intelligence functions */
  ARTIFICIAL_INTELLIGENCE = "ARTIFICIAL_INTELLIGENCE",
  /** Knowledge of the concepts, principles, and theories of the physical processes leading to the emission of electromagnetic radiation or particles from celestial bodies, the measurement and physical characteristics of celestial bodies, including cosmic microwave background, submillimeter technology, galaxies, star formations, and planetary science */
  ASTRONOMY = "ASTRONOMY",
  /** Is thorough when performing work and conscientious about attending to detail */
  ATTENTION_TO_DETAIL = "ATTENTION_TO_DETAIL",
  /** Knowledge of the principles, practices, and techniques used to report audit findings (criteria, condition, cause, effect, and recommendation) */
  AUDIT_REPORTING = "AUDIT_REPORTING",
  /** Knowledge of generally accepted auditing standards and procedures for conducting financial and compliance, economy and efficiency, and program audits */
  AUDITING = "AUDITING",
  /** Knowledge of the environment, plant and animal living tissue, cells, organisms, and entities, including their functions, interdependencies and interactions with each other and the environment */
  BIOLOGY = "BIOLOGY",
  /** Knowledge of the concepts, principles, and theories of plants, including structures and functions, classification, taxonomy, plant communities, distribution, habitat requirements, life histories, reproduction, conservation, and care of plant species */
  BOTANY = "BOTANY",
  /** Knowledge of the principles and practices of budget administration and analysis; including preparing, justifying, reporting on, and executing the budget; and the relationships among program, budget, accounting, and reporting systems */
  BUDGET_ADMINISTRATION = "BUDGET_ADMINISTRATION",
  /** Knowledge of materials, methods, and the tools to construct objects, structures, and buildings */
  BUILDING_AND_CONSTRUCTION = "BUILDING_AND_CONSTRUCTION",
  /** Knowledge of methods, metrics, tools, and techniques of Business Process Reengineering */
  BUSINESS_PROCESS_REENGINEERING = "BUSINESS_PROCESS_REENGINEERING",
  /** Knowledge of the principles and methods for monitoring, estimating, or reporting actual performance or the performance capability of information systems or components */
  CAPACITY_MANAGEMENT = "CAPACITY_MANAGEMENT",
  /** Knowledge of the principles and methods of capital investment analysis or business case analysis, including return on investment analysis */
  CAPITAL_PLANNING_AND_INVESTMENT_ASSESSMENT = "CAPITAL_PLANNING_AND_INVESTMENT_ASSESSMENT",
  /** Knowledge of materials, methods, and the appropriate tools to construct, install, finish, or repair wooden objects or structures */
  CARPENTRY_AND_WOODWORKING = "CARPENTRY_AND_WOODWORKING",
  /** Knowledge of the concepts, principles, theories, and methods related to the research, design, development, or revision of maps, charts, and related cartographic products, and photogrammatic and cartographic processing */
  CARTOGRAPHY = "CARTOGRAPHY",
  /** Knowledge of change management principles, strategies, and techniques required for effectively planning, implementing, and evaluating change in the organization */
  CHANGE_MANAGEMENT = "CHANGE_MANAGEMENT",
  /** Knowledge of the concepts, principles, and theories related to the chemical composition or physical characteristics of materials for the design, construction, operation, and improvement of processes or systems */
  CHEMICAL_ENGINEERING = "CHEMICAL_ENGINEERING",
  /** Knowledge of chemicals, including hazardous materials, and their uses, interactions, dangers, production, storage, and disposal */
  CHEMISTRY = "CHEMISTRY",
  /** Knowledge of the concepts, principles, theories, and methods required to plan, design, construct, operate, and maintain facilities such as buildings, transportation systems, water and sanitary systems, and other public works systems */
  CIVIL_ENGINEERING = "CIVIL_ENGINEERING",
  /** Knowledge of classification concepts, principles, and practices related to structuring organizations and positions and determining the appropriate pay system, occupational grouping, title, and pay level of positions */
  CLASSIFICATION = "CLASSIFICATION",
  /** Knowledge of filing, typing, entering data, maintaining records, taking shorthand, and using and completing forms */
  CLERICAL = "CLERICAL",
  /** Knowledge of the impact of change on people, processes, procedures, leadership, and organizational culture; knowledge of change management principles, strategies, and techniques required for effectively planning, implementing, and evaluating change in the organization */
  CLIENT_ENGAGEMENT_AND_CHANGE_MANAGEMENT = "CLIENT_ENGAGEMENT_AND_CHANGE_MANAGEMENT",
  /** Knowledge of the production, communication and dissemination of information and ideas to inform and entertain via written, oral, and visual media */
  COMMUNICATIONS_AND_MEDIA = "COMMUNICATIONS_AND_MEDIA",
  /** Knowledge of the principles, policies, and procedures involved in ensuring the security of communications services and data, and in maintaining the communications environment on which it resides */
  COMMUNICATIONS_SECURITY_MANAGEMENT = "COMMUNICATIONS_SECURITY_MANAGEMENT",
  /** Knowledge of compensation concepts, principles, and practices, including pay and leave administration and compensation flexibilities */
  COMPENSATION = "COMPENSATION",
  /** Knowledge of procedures for assessing, evaluating, and monitoring programs or projects for compliance with Federal laws, regulations, and guidance */
  COMPLIANCE = "COMPLIANCE",
  /** Knowledge of the guidelines, regulations, and procedures associated with compliance inquiries, including application of compliance rules and criteria and ability to make appropriate decisions and issue citations, fines, or orders */
  COMPLIANCE_INSPECTION = "COMPLIANCE_INSPECTION",
  /** Knowledge of tools and techniques used in data recovery and preservation of electronic evidence */
  COMPUTER_FORENSICS = "COMPUTER_FORENSICS",
  /** Knowledge of computer languages and their applications to enable a system to perform specific functions */
  COMPUTER_LANGUAGES = "COMPUTER_LANGUAGES",
  /** Knowledge of defensive measures to detect, respond, and protect information, information systems, and networks from threats */
  COMPUTER_NETWORK_DEFENSE = "COMPUTER_NETWORK_DEFENSE",
  /** Uses computers, software applications, databases, and automated systems to accomplish work */
  COMPUTER_SKILLS = "COMPUTER_SKILLS",
  /** Knowledge of circuit boards, processors, chips, and computer hardware and software, including applications and programming */
  COMPUTERS = "COMPUTERS",
  /** Knowledge of electric circuit boards, processors, chips, and computer hardware and software, including applications and programming */
  COMPUTERS_AND_ELECTRONICS = "COMPUTERS_AND_ELECTRONICS",
  /** Knowledge of the principles and methods for planning or managing the implementation, update, or integration of information systems components */
  CONFIGURATION_MANAGEMENT = "CONFIGURATION_MANAGEMENT",
  /** Manages and resolves conflicts, grievances, confrontations, or disagreements in a constructive manner to minimize negative personal impact */
  CONFLICT_MANAGEMENT = "CONFLICT_MANAGEMENT",
  /** Displays a high level of effort and commitment towards performing work; demonstrates responsible behavior */
  CONSCIENTIOUSNESS = "CONSCIENTIOUSNESS",
  /** Knowledge of the laws and legal precedents related to the US Constitution */
  CONSTITUTIONAL_LAW = "CONSTITUTIONAL_LAW",
  /** Assesses and recognizes own strengths and weaknesses; pursues self-development */
  CONTINUAL_LEARNING = "CONTINUAL_LEARNING",
  /** Knowledge of various types of contracts, techniques, or requirements (for example, Federal Acquisitions Regulations) for contracting or procurement, and contract negotiation and administration */
  CONTRACTING_AND_PROCUREMENT = "CONTRACTING_AND_PROCUREMENT",
  /** Knowledge of the principles, procedures, and requirements for maintaining control and accountability of obligations and expenditures for all appropriations and fund accounts (for example, revolving, non-appropriated, multiyear, and single-year appropriations) */
  CONTROL_OF_FUNDS = "CONTROL_OF_FUNDS",
  /** Knowledge of the principles, procedures, and methods of cost accounting, including the use of historical cost, market value, or present value to measure cost; methods for assigning cost to accounting periods; and cost allocation, cost accrual, depreciation, and unit cost */
  COST_ACCOUNTING = "COST_ACCOUNTING",
  /** Knowledge of the principles, practices, and methods used to determine, estimate, and analyze costs, including determining life cycle costs, application of cost models, and evaluation of cost realism */
  COST_ESTIMATION_AND_ANALYSIS = "COST_ESTIMATION_AND_ANALYSIS",
  /** Knowledge of the principles and methods of cost-benefit analysis, including the time value of money, present value concepts, and quantifying tangible and intangible benefits */
  COST_BENEFIT_ANALYSIS = "COST_BENEFIT_ANALYSIS",
  /** Uses imagination to develop new insights into situations and applies innovative solutions to problems; designs new methods where established methods and procedures are inapplicable or are unavailable */
  CREATIVE_THINKING = "CREATIVE_THINKING",
  /** Develops new insights into situations; questions conventional approaches; encourages new ideas and innovations; designs and implements new or cutting edge programs_AND_processes */
  CREATIVITY_AND_INNOVATION = "CREATIVITY_AND_INNOVATION",
  /** Knowledge of the guidelines, regulations, and procedures associated with criminal investigation, including evidence detection and handling and drawing appropriate factual inferences and conclusions */
  CRIMINAL_INVESTIGATION = "CRIMINAL_INVESTIGATION",
  /** Knowledge of state and Federal criminal laws, including procedures, regulations, guidelines, and precedents related to admissibility of evidence and prosecution */
  CRIMINAL_LAW = "CRIMINAL_LAW",
  /** Anticipates and meets the needs of both internal and external customers Delivers high-quality products and services; is committed to continuous improvement */
  CUSTOMER_SERVICE = "CUSTOMER_SERVICE",
  /** Knowledge of meat cutting, including the grades and structure of meat, fish, or poultry */
  CUTTING = "CUTTING",
  /** Knowledge of the principles, procedures, and tools of data management, such as modeling techniques, data backup, data recovery, data dictionaries, data warehousing, data mining, data archiving, data disposal, and data standardization processes */
  DATA_MANAGEMENT = "DATA_MANAGEMENT",
  /** Knowledge of computer hardware and software development and systems as they apply to the conception, specification, analysis, planning, development, installation, test, modification and use of data handling and computing systems in support of aerospace flight and ground systems */
  DATA_SYSTEMS = "DATA_SYSTEMS",
  /** Knowledge of the principles, methods, and tools for automating, developing, implementing, or administering database systems */
  DATABASE_ADMINISTRATION = "DATABASE_ADMINISTRATION",
  /** Knowledge of the uses of database management systems and software to control the organization, storage, retrieval, security, and integrity of data */
  DATABASE_MANAGEMENT_SYSTEMS = "DATABASE_MANAGEMENT_SYSTEMS",
  /** Makes sound, well-informed, and objective decisions; perceives the impact and implications of decisions; commits to action, even in uncertain situations, to accomplish organizational goals; causes change */
  DECISION_MAKING = "DECISION_MAKING",
  /** Knowledge of decision support theories, methods, and tools for identifying, synthesizing, representing, and evaluating the important aspects of a decision situation and prescribing the recommended course for decision makers and other stakeholders */
  DECISION_SUPPORT = "DECISION_SUPPORT",
  /** Makes well-informed, effective, and timely decisions, even when data are limited or solutions produce unpleasant consequences; perceives the impact and implications of decisions */
  DECISIVENESS = "DECISIVENESS",
  /** Accurately judges which of several objects is closer or farther away from the observer, or the distance between an object and the observer */
  DEPTH_PERCEPTION = "DEPTH_PERCEPTION",
  /** Knowledge of conceptualizing, developing, producing, understanding, and using plans, models, blueprints, and maps, including the use of tools and instruments to produce precision technical drawings, working prototypes, components, or systems */
  DESIGN = "DESIGN",
  /** Knowledge of the policies and procedures for detaining criminal suspects including processing, fingerprinting, detention requests, informing detainee of charges, and transportation */
  DETENTION = "DETENTION",
  /** Develops the ability of others to perform and contribute to the organization by providing ongoing feedback and by providing opportunities to learn through formal and informal methods */
  DEVELOPING_OTHERS = "DEVELOPING_OTHERS",
  /** Knowledge of the principles, theoretical concepts, and tools underlying distributed computing systems, including their associated components and communication standards */
  DISTRIBUTED_SYSTEMS = "DISTRIBUTED_SYSTEMS",
  /** Knowledge of interdisciplinary disciplines associated with the earths composition, structure, or other physical aspects, including atmosphere */
  EARTH_SCIENCE = "EARTH_SCIENCE",
  /** Knowledge of the concepts, principles, and theories of the interrelationships among organisms and their environment, including competition and predation, evolution and natural selection, population dynamics, and the impact of natural phenomena or human actions on natural systems, processes, and biota */
  ECOLOGY = "ECOLOGY",
  /** Knowledge of economic policy, principles, and practices, market and non-market values, and the analysis and reporting of economic data */
  ECONOMICS = "ECONOMICS",
  /** Knowledge of economic and accounting principles and practices, tax law and practices, the financial markets, banking, and the analysis and reporting of financial data */
  ECONOMICS_AND_ACCOUNTING = "ECONOMICS_AND_ACCOUNTING",
  /** Identifies and understands economic, political, and social trends that affect the organization */
  EXTERNAL_AWARENESS = "EXTERNAL_AWARENESS",
  /** Knowledge of teaching, training, research, making presentations, lecturing, testing, and other instructional methods */
  EDUCATION_AND_TRAINING = "EDUCATION_AND_TRAINING",
  /** Knowledge of electrical equipment, components, instruments, and systems, including their design, installation, testing, uses, repair, or maintenance */
  ELECTRICAL = "ELECTRICAL",
  /** Knowledge of the concepts, principles, theories, and methods related to the design, analysis, test, and integration of electrical systems; energy conversion; electrical power generation; and energy transmission, control, distribution or use */
  ELECTRICAL_ENGINEERING = "ELECTRICAL_ENGINEERING",
  /** Knowledge of the principles, methods, and tools for conducting business online, including electronic data interchange */
  ELECTRONIC_COMMERCE = "ELECTRONIC_COMMERCE",
  /** Knowledge of electronic theory, circuits, components, and material properties (excluding computers) */
  ELECTRONICS = "ELECTRONICS",
  /** Knowledge of the concepts, principles, theories, and methods related to the design, analysis, test, fabrication, or verification of analog or digital electronic systems */
  ELECTRONICS_ENGINEERING = "ELECTRONICS_ENGINEERING",
  /** Knowledge of specifications and uses of specialized computer systems used to control devices (for example, automobiles, helicopters), including the appropriate programming languages */
  EMBEDDED_COMPUTERS = "EMBEDDED_COMPUTERS",
  /** Knowledge of HR concepts, principles, and practices related to retirement, insurance, injury compensation, and other employee benefits programs */
  EMPLOYEE_BENEFITS = "EMPLOYEE_BENEFITS",
  /** Knowledge of employee development concepts, principles, and practices related to planning, evaluating, and administering training, organizational development, and career development initiatives */
  EMPLOYEE_DEVELOPMENT = "EMPLOYEE_DEVELOPMENT",
  /** Knowledge of laws, rules, regulations, case law, principles, and practices related to employee conduct, performance, and dispute resolution */
  EMPLOYEE_RELATIONS = "EMPLOYEE_RELATIONS",
  /** Knowledge of procedures, tools, and applications used to keep data or information secure, including public key infrastructure, point-to-point encryption, and smart cards */
  ENCRYPTION = "ENCRYPTION",
  /** Knowledge of engineering concepts, principles, and practices, and of equipment, tools, mechanical devices, and their uses to produce motion, light, power, technology, and other applications */
  ENGINEERING_AND_TECHNOLOGY = "ENGINEERING_AND_TECHNOLOGY",
  /** Knowledge of principles, concepts, and methods of enterprise architecture to align information technology (IT) strategy, plans, and systems with the mission, goals, structure, and processes of the organization */
  ENTERPRISE_ARCHITECTURE = "ENTERPRISE_ARCHITECTURE",
  /** Knowledge of the concepts, principles, and theories of insects, including taxonomy, morphology, behavior, life cycles, population dynamics, host-insect interactions, the role of insects in natural and managed ecosystems, and the regulation, prevention, and control of pest-related problems */
  ENTOMOLOGY = "ENTOMOLOGY",
  /** Positions the organization for future success by identifying new opportunities; builds the organization by developing or improving products or services Takes calculated risks to accomplish organizational objectives */
  ENTREPRENEURSHIP = "ENTREPRENEURSHIP",
  /** Knowledge of the concepts, principles, theories, and methods to protect and improve the quality of the environment and its resources; and to monitor, control, abate, and prevent pollutants */
  ENVIRONMENTAL_ENGINEERING = "ENVIRONMENTAL_ENGINEERING",
  /** Accurately coordinates ones eyes with ones fingers, wrists, or arms to perform job-related tasks (for example, to move, carry, or manipulate objects) */
  EYE_HAND_COORDINATION = "EYE_HAND_COORDINATION",
  /** Knowledge of the physical, engineering, and experimental equipment and operational characteristics of facilities, and safety and equipment development designed to support aerospace activities */
  FACILITIES = "FACILITIES",
  /** Knowledge of methods and procedures for processing direct and reimbursable program funds (for example, automatic and funded reimbursements, interagency agreements, transfer appropriations), grants, loans, and credit programs */
  FEDERAL_FUNDS_PROCESSING = "FEDERAL_FUNDS_PROCESSING",
  /** Knowledge of the principles, methods, and techniques of financial analysis, forecasting, and modeling to interpret quantitative and qualitative data; includes data modeling, earned value management, and evaluating key financial indicators, trends, and historical data */
  FINANCIAL_ANALYSIS = "FINANCIAL_ANALYSIS",
  /** Knowledge of the differences between acquisition and financial assistance purposes and requirements; knowledge of Federal assistance instruments, techniques, and procedures for grants (for example, block, mandatory, discretionary) and agreements (for example, cooperative, interagency) */
  FINANCIAL_ASSISTANCE_MECHANISMS = "FINANCIAL_ASSISTANCE_MECHANISMS",
  /** Understands the organizations financial processes Prepares, justifies, and administers the program budget  Oversees procurement and contracting to achieve desired results   Monitors expenditures and uses cost-benefit thinking to set priorities */
  FINANCIAL_MANAGEMENT = "FINANCIAL_MANAGEMENT",
  /** Knowledge of the standards, architecture, and specifications of automated financial systems, including source documents, system flows, system interfaces, and related internal controls */
  FINANCIAL_SYSTEMS = "FINANCIAL_SYSTEMS",
  /** Knowledge of theory and techniques required to produce, compose, and perform works of music, dance, visual arts, drama, and sculpture */
  FINE_ARTS = "FINE_ARTS",
  /** Knowledge of the concepts, principles, and theories of fire management, including the characteristics, behavior, and ecology of fire; methodologies, strategies, and equipment used in prescribed fires; fire detection, prevention, and suppression strategies; and integration of fire with natural resource management */
  FIRE_MANAGEMENT = "FIRE_MANAGEMENT",
  /** Knowledge of firearm usage and related issues, such as ammunition, range regulations and safety and use of force policies */
  FIREARMS = "FIREARMS",
  /** Knowledge of emergency management methods, such as first aid, rescue techniques, and threat assessments */
  FIRST_RESPONSE = "FIRST_RESPONSE",
  /** Knowledge of the concepts, principles, and theories of aquatic life, including classification, taxonomy, population dynamics, distribution, habitat requirements, life histories, reproduction, behaviors, conservation, and care of aquatic species */
  FISHERY_BIOLOGY = "FISHERY_BIOLOGY",
  /** Is open to change and new information; rapidly adapts to new information, changing conditions, or unexpected obstacles */
  FLEXIBILITY = "FLEXIBILITY",
  /** Knowledge of the concepts, principles, and theories related to the development, design, test, and evaluation of aerospace flight vehicles and their component subsystems, or their related external systems */
  FLIGHT_SYSTEMS = "FLIGHT_SYSTEMS",
  /** Knowledge of specifications, uses, and types of computer or computer-related equipment */
  HARDWARE = "HARDWARE",
  /** Knowledge of the concepts, principles, and theories of computational fluid dynamics, fluid mechanics, flight dynamics, flight structures, the force and motion mechanics of vehicles in various atmospheric and celestial environments, aerothermodynamics, and the characteristics of electrically conducting fluids under the action of magnetic and electric fields */
  FLUID_DYNAMICS_AND_MECHANICS = "FLUID_DYNAMICS_AND_MECHANICS",
  /** Knowledge of planning, growing, and harvesting of food for consumption using appropriate equipment and techniques */
  FOOD_PRODUCTION = "FOOD_PRODUCTION",
  /** Knowledge of preparing and serving food for consumption */
  FOOD_SERVICE = "FOOD_SERVICE",
  /** Knowledge of sign language or of the structure and content of a foreign (non-English) language, including the meaning and spelling of words, rules of composition, and grammar */
  FOREIGN_LANGUAGE = "FOREIGN_LANGUAGE",
  /** Knowledge of procedures of civil, criminal, or administrative hearings, evidence collection, including the delivery and receipt of evidence, classes of evidence, and rules of evidence and legal procedures */
  FORENSICS = "FORENSICS",
  /** Knowledge of the concepts, principles, and theories of silviculture and forest ecology, forest use, management, harvesting, conducting inventories, regeneration, sustainability, and conservation; and the role of disturbances in timberland resources */
  FOREST_MANAGEMENT = "FOREST_MANAGEMENT",
  /** Knowledge of the concepts, principles, and theories of engineering and their practical applications */
  GENERAL_ENGINEERING = "GENERAL_ENGINEERING",
  /** Knowledge of the concepts, principles, and theories of genetics, including the biochemistry of DNA, gene interaction, gene expression, gene inheritance, population genetics, adaptation, and evolution */
  GENETICS = "GENETICS",
  /** Knowledge of the concepts, principles, theories, and methods for describing the location and distribution of land, sea, and air masses, including their physical locations, relationships, characteristics, and what the land supports */
  GEOGRAPHICAL_SCIENCES = "GEOGRAPHICAL_SCIENCES",
  /** Knowledge of geographical locations, their relationships and characteristics */
  GEOGRAPHY = "GEOGRAPHY",
  /** Knowledge of the concepts, principles, and theories of the origins and structure of the earth, including the physical forces that have shaped it and its physical and organic history */
  GEOLOGY = "GEOLOGY",
  /** Knowledge of the concepts, principles, and theories related to solid earth structure, global seismic patterns, lithosphere, atmosphere, and the behavior of the earths gravitational, magnetic, and electrical fields, and other forces affecting the earth and its environment */
  GEOPHYSICS = "GEOPHYSICS",
  /** Knowledge of the concepts, principles, theories, and methods related to the investigation and evaluation of subsurface soil or geologic conditions and properties for the purpose of designing stable foundation systems, earthen structures, or the remediation of subsurface conditions */
  GEOTECHNICAL_ENGINEERING = "GEOTECHNICAL_ENGINEERING",
  /** Knowledge of requirements, practices, and procedures for soliciting, receiving, reviewing, and processing proposals, and awarding and administering grants and agreements */
  GRANTS_MANAGEMENT = "GRANTS_MANAGEMENT",
  /** Knowledge of principles, laws, regulations, policies, practices, and guidelines (for example, Executive Orders, Code of Federal Regulations, OMB circulars) of grant or agreement programs, including their order of precedence */
  GRANTS_MANAGEMENT_LAWS_REGULATIONS_AND_GUIDELINES = "GRANTS_MANAGEMENT_LAWS_REGULATIONS_AND_GUIDELINES",
  /** Knowledge of the principles, methods, and tools for designing, developing, and testing computer or computer-related equipment */
  HARDWARE_ENGINEERING = "HARDWARE_ENGINEERING",
  /** Knowledge of hazardous materials and waste and their uses, interactions, dangers, production, handling, storage, and disposal */
  HAZARDOUS_MATERIALS = "HAZARDOUS_MATERIALS",
  /** Knowledge of the concepts, principles, theories, and methods pertaining to the protection of people, their environment, and equipment from hazards (for example, radiation or hazardous chemicals) and the control of radioactive material */
  HEALTH_PHYSICS = "HEALTH_PHYSICS",
  /** Knowledge of historical events and their causes, indicators, and impact on particular civilization and cultures, and of preservation and archival techniques */
  HISTORY_AND_ARCHEOLOGY = "HISTORY_AND_ARCHEOLOGY",
  /** Knowledge of the concepts, principles, theories, and practices of cultivation or crop management, physiological processes in plant growth and crop yield */
  HORTICULTURAL_SCIENCES = "HORTICULTURAL_SCIENCES",
  /** Knowledge of cultivating flowers, plants, and trees */
  HORTICULTURE = "HORTICULTURE",
  /** Knowledge of HR management concepts, principles, and practices related to identifying and analyzing HR processes, translating functional requirements into technical requirements, and delivering and maintaining HR information systems */
  HR_INFORMATION_SYSTEMS = "HR_INFORMATION_SYSTEMS",
  /** Builds and manages workforce based on organizational goals, budget considerations, and staffing needs Ensures that employees are appropriately recruited, selected, appraised, and rewarded; takes action to address performance problems Manages a multi-sector workforce and a variety of work situations */
  HUMAN_CAPITAL_MANAGEMENT = "HUMAN_CAPITAL_MANAGEMENT",
  /** Knowledge of the principles, methods, and tools used to identify and apply information about human behavior, abilities, limitations, and other characteristics to the design of tools, machines, systems, tasks, jobs, and environments for effective human use */
  HUMAN_FACTORS = "HUMAN_FACTORS",
  /** Knowledge of the concepts, principles, theories, and methods applicable to analysis of the flow of fluids (open channel and pressure flow), estimation of river stages, and design of hydraulic structures, drainage structures, pipes, navigation facilities, reservoirs, locks, and dams */
  HYDRAULIC_ENGINEERING = "HYDRAULIC_ENGINEERING",
  /** Knowledge of the concepts, principles, theories, and methods related to the magnitude, distribution, and quality of water resources including watershed management, climatology, geomorphology, groundwater hydrology, water quality, water resource management, and groundwater_AND_surface water interactions */
  HYDROLOGY = "HYDROLOGY",
  /** Knowledge of methods and controls to validate the identity of individuals to verify access approval and level, and monitor activity to ensure that only authorized access is taking place */
  IDENTITY_MANAGEMENT = "IDENTITY_MANAGEMENT",
  /** Knowledge of the tactics, technologies, principles, and processes to protect, analyze, prioritize, and handle incidents */
  INCIDENT_MANAGEMENT = "INCIDENT_MANAGEMENT",
  /** Knowledge of principles and methods for operating industrial equipment */
  INDUSTRIAL_EQUIPMENT_OPERATION = "INDUSTRIAL_EQUIPMENT_OPERATION",
  /** Persuades others to accept recommendations, cooperate, or change their behavior; works with others towards an agreement; negotiates to find mutually acceptable solutions */
  INFLUENCING_AND_NEGOTIATING = "INFLUENCING_AND_NEGOTIATING",
  /** Knowledge of methods and procedures to protect information systems and data by ensuring their availability, authentication, confidentiality, and integrity */
  INFORMATION_ASSURANCE = "INFORMATION_ASSURANCE",
  /** Identifies a need for and knows where or how to gather information; organizes and maintains information or information management systems */
  INFORMATION_MANAGEMENT = "INFORMATION_MANAGEMENT",
  /** Knowledge of the principles, methods, and techniques of information technology (IT) assessment, planning, management, monitoring, and evaluation, such as IT baseline assessment, interagency functional analysis, contingency planning, and disaster recovery */
  INFORMATION_RESOURCES_STRATEGY_AND_PLANNING = "INFORMATION_RESOURCES_STRATEGY_AND_PLANNING",
  /** Knowledge of methods, tools, and procedures, including development of information security plans, to prevent information systems vulnerabilities, and provide or restore security of information systems and network services */
  INFORMATION_SYSTEMS_AND_NETWORK_SECURITY = "INFORMATION_SYSTEMS_AND_NETWORK_SECURITY",
  /** Knowledge of the principles, methods, and tools for evaluating information systems security features against a set of specified security requirements Includes developing security certification and accreditation plans and procedures, documenting deficiencies, reporting corrective actions, and recommending changes to improve the security of information systems */
  INFORMATION_SYSTEMS_SECURITY_CERTIFICATION = "INFORMATION_SYSTEMS_SECURITY_CERTIFICATION",
  /** Knowledge of architectural methodologies used in the design and development of information systems, including the physical structure of a systems internal operations and interactions with other systems */
  INFORMATION_TECHNOLOGY_ARCHITECTURE = "INFORMATION_TECHNOLOGY_ARCHITECTURE",
  /** Knowledge of the principles, methods, and tools (for example, surveys, system performance measures) to assess the effectiveness and practicality of information technology systems */
  INFORMATION_TECHNOLOGY_PERFORMANCE_ASSESSMENT = "INFORMATION_TECHNOLOGY_PERFORMANCE_ASSESSMENT",
  /** Knowledge of the principles, methods, and tools for the coordinated management of an IT program to include providing oversight of multiple IT projects, integrating dependent schedules and deliverables, and related activities (for example, benefits management, life cycle management, program governance) */
  INFORMATION_TECHNOLOGY_PROGRAM_MANAGEMENT = "INFORMATION_TECHNOLOGY_PROGRAM_MANAGEMENT",
  /** Knowledge of scientific principles, methods, and tools of basic and applied research used to conduct a systematic inquiry into a subject matter area */
  INFORMATION_TECHNOLOGY_RESEARCH_AND_DEVELOPMENT = "INFORMATION_TECHNOLOGY_RESEARCH_AND_DEVELOPMENT",
  /** Knowledge of the architecture and typology of software, hardware, and networks, including LANS, WANS, and telecommunications systems, their components and associated protocols and standards, and how they operate and integrate with one another and with associated controlling software */
  INFRASTRUCTURE_DESIGN = "INFRASTRUCTURE_DESIGN",
  /** Knowledge of various types of insurance, insurance regulations, claims processing, examination, adjudication, or adjustment */
  INSURANCE = "INSURANCE",
  /** Behaves in an honest, fair, and ethical manner Shows consistency in words and actions Models high standards of ethics */
  INTEGRITY_AND_HONESTY = "INTEGRITY_AND_HONESTY",
  /** Selects, acquires, stores, and distributes resources such as materials, equipment, or money */
  MANAGES_RESOURCES = "MANAGES_RESOURCES",
  /** Knowledge of the principles, methods, and techniques for establishing internal control activities (for example, authorizations, verifications, reconciliations), monitoring their use, and evaluating their performance (for example, identification of material weaknesses or significant deficiencies) */
  INTERNAL_CONTROLS = "INTERNAL_CONTROLS",
  /** Treats others with courtesy, sensitivity, and respect  Considers and responds appropriately to the needs and feelings of different people in different situations */
  INTERPERSONAL_SKILLS = "INTERPERSONAL_SKILLS",
  /** Knowledge of mathematical modeling and simulation tools and techniques to plan and conduct test and evaluation programs, characterize systems support decisions involving requirements, evaluate design alternatives, or support operational preparation */
  IT_MODELING_AND_SIMULATION = "IT_MODELING_AND_SIMULATION",
  /** Knowledge of the value of collected information and the methods of sharing that information throughout an organization */
  KNOWLEDGE_MANAGEMENT = "KNOWLEDGE_MANAGEMENT",
  /** Knowledge of state and Federal employment laws, regulations, guidelines, and legal precedents related to hiring practices, equal employment opportunity, and wage and hour restrictions */
  LABOR_LAW = "LABOR_LAW",
  /** Knowledge of laws, rules, regulations, case law, principles, and practices related to negotiating and administering labor agreements */
  LABOR_RELATIONS = "LABOR_RELATIONS",
  /** Knowledge of the concepts, theories, and practices used in the planning, designing, construction, and adaptation of outdoor features, taking into consideration recreation planning, requirements, aesthetic value, and compatibility with other developments and resources */
  LANDSCAPE_ARCHITECTURE = "LANDSCAPE_ARCHITECTURE",
  /** Influences, motivates, and challenges others; adapts leadership styles to a variety of situations */
  LEADERSHIP = "LEADERSHIP",
  /** Uses efficient learning techniques to acquire and apply new knowledge and skills; uses training, feedback, or other opportunities for self-learning and development */
  LEARNING = "LEARNING",
  /** Knowledge of laws, legal codes, court procedures, precedents, legal practices and documents, Government regulations, Executive orders, agency rules, Government organization and functions, and the democratic political process */
  LEGAL_GOVERNMENT_AND_JURISPRUDENCE = "LEGAL_GOVERNMENT_AND_JURISPRUDENCE",
  /** Fosters an inclusive workplace where diversity and individual differences are valued and leveraged to achieve the vision and mission of the organization */
  LEVERAGING_DIVERSITY = "LEVERAGING_DIVERSITY",
  /** Knowledge of life sciences that involve the theoretical and experimental research of life systems */
  LIFE_SCIENCES_AND_SYSTEMS = "LIFE_SCIENCES_AND_SYSTEMS",
  /** Receives, attends to, interprets, and responds to verbal messages and other cues such as body language in ways that are appropriate to listeners and situations */
  LISTENING = "LISTENING",
  /** Knowledge of the principles and methods for designing business logic components, system processes and outputs, user interfaces, data inputs, and productivity tools (for example, computer-aided software engineering) */
  LOGICAL_SYSTEMS_DESIGN = "LOGICAL_SYSTEMS_DESIGN",
  /** Identifies a need; gathers, organizes, and maintains information; determines its importance and accuracy, and communicates it by a variety of methods */
  MANAGES_AND_ORGANIZES_INFORMATION = "MANAGES_AND_ORGANIZES_INFORMATION",
  /** Plans, distributes, and monitors work assignments; evaluates work performance and provides feedback to others on their performance */
  MANAGES_HUMAN_RESOURCES = "MANAGES_HUMAN_RESOURCES",
  /** Plans, distributes, coordinates, and monitors work assignments of others; evaluates work performance and provides feedback to others on their performance; ensures that staff are appropriately selected, utilized, and developed, and that they are treated in a fair and equitable manner */
  MANAGING_HUMAN_RESOURCES = "MANAGING_HUMAN_RESOURCES",
  /** Knowledge of the specifications, tools, inputs, raw materials, outputs, and waste related to the manufacture of prototypes, models, systems, or other products */
  MANUFACTURING = "MANUFACTURING",
  /** Knowledge of the concepts, principles, theories, and methods related to the composition, structures, and properties of materials, their use, behavior and performance under environmental influences, and the identification, processing, and manufacture of optimal materials for various applications */
  MATERIALS_ENGINEERING = "MATERIALS_ENGINEERING",
  /** Solves practical problems by choosing appropriately from a variety of mathematical and statistical techniques */
  MATHEMATICAL_REASONING = "MATHEMATICAL_REASONING",
  /** Knowledge of electronics and related electrical engineering disciplines necessary for the research and development of sensors, electronic measurement devices, and instrumentation systems for aerospace systems and components */
  MEASUREMENT_AND_INSTRUMENTATION = "MEASUREMENT_AND_INSTRUMENTATION",
  /** Knowledge of machines and tools, including their designs, installation, uses, repair, and maintenance */
  MECHANICAL = "MECHANICAL",
  /** Knowledge of the concepts, principles, theories, and methods related to planning, designing, developing, testing, or evaluating thermodynamic, mechanical, electro-mechanical, pneumatic, hydraulic, or structural equipment, systems, models, tools, or specialized mechanical devices */
  MECHANICAL_ENGINEERING = "MECHANICAL_ENGINEERING",
  /** Knowledge of machines and tools, including their design, use, benefits, repair, operation, and maintenance */
  MECHANICS = "MECHANICS",
  /** Knowledge of the diagnosis and treatment of injuries, diseases, and deformities, including preventive health-care measures */
  MEDICINE_AND_DENTISTRY = "MEDICINE_AND_DENTISTRY",
  /** Recalls information that has been presented previously */
  MEMORY = "MEMORY",
  /** Sees things in the mind by mentally organizing and processing symbols, pictures, graphs, objects, or other information (for example, sees a building from a blueprint, or sees the flow of work activities from reading a work plan) */
  MENTAL_VISUALIZATION = "MENTAL_VISUALIZATION",
  /** Knowledge of materials, methods, and appropriate tools to process, treat, form, or shape metal */
  METAL_PROCESSING_AND_METALWORKING = "METAL_PROCESSING_AND_METALWORKING",
  /** Knowledge of the concepts, principles, and theories related to the study of extracting, refining, alloying, and preparing metals for use; and their properties and behavior as affected by the composition, treatment in manufacture, and conditions of use */
  METALLURGY = "METALLURGY",
  /** Knowledge of mine safety and health principles and practices, techniques and procedures, regulations, and standards as they apply to conducting inspections_AND_investigations, identifying and evaluating unsafe conditions, and recommending methods to correct unsafe conditions */
  MINE_SAFETY_AND_HEALTH = "MINE_SAFETY_AND_HEALTH",
  /** Knowledge of the concepts, principles, theories, and methods related to rock mechanics; the exploration, excavation, extraction, processing and transporting of mineral resources; and the conservation and development of mineral lands, materials, and deposits */
  MINING_ENGINEERING = "MINING_ENGINEERING",
  /** Knowledge of the tools and techniques used to develop functional, physical, or prototype models and simulations for test and evaluation programs, the prediction of behavior and phenomena, and to visually communicate concepts */
  MODELING_AND_SIMULATION = "MODELING_AND_SIMULATION",
  /** Knowledge of the principles, methods, tools, and techniques to develop or apply technology using text, audio, graphics, or other media */
  MULTIMEDIA_TECHNOLOGIES = "MULTIMEDIA_TECHNOLOGIES",
  /** Works with others towards an agreement that may involve exchanging specific resources or resolving differences */
  NEGOTIATION = "NEGOTIATION",
  /** Knowledge of the operation, management, and maintenance of network and telecommunication systems and linked systems and peripherals */
  NETWORK_MANAGEMENT = "NETWORK_MANAGEMENT",
  /** Knowledge of the concepts, principles, theories, and application of nuclear technologies including research, development, construction, operation, testing, and maintenance of nuclear reactors, radiation generating devices, and associated systems and equipment */
  NUCLEAR_ENGINEERING = "NUCLEAR_ENGINEERING",
  /** Knowledge of the concepts, principles, theories, and methods related to the prediction of nuclear interactions and reactions, including practices and methods used to produce, measure, use, or observe such reactions in stars, nuclear weapons systems, and radiation shielding */
  NUCLEAR_PHYSICS = "NUCLEAR_PHYSICS",
  /** Knowledge of the principles, methods, tools, and techniques that use object-oriented languages, analysis, and design methodologies */
  OBJECT_TECHNOLOGY = "OBJECT_TECHNOLOGY",
  /** Knowledge of computer network, desktop, and mainframe operating systems and their applications */
  OPERATING_SYSTEMS = "OPERATING_SYSTEMS",
  /** Knowledge of engineering or physical science disciplines to support space flight operations, training or planning; serving as an astronaut or mission specialist */
  OPERATIONS = "OPERATIONS",
  /** Knowledge of procedures to ensure production or delivery of products and services, including tools and mechanisms for distributing new or enhanced software */
  OPERATIONS_SUPPORT = "OPERATIONS_SUPPORT",
  /** Makes clear and convincing oral presentations Listens effectively; clarifies information as needed */
  ORAL_COMMUNICATION = "ORAL_COMMUNICATION",
  /** Knows the organizations mission and functions, and how its social, political, and technological systems work and operates effectively within them; this includes the programs, policies, procedures, rules, and regulations of the organization */
  ORGANIZATIONAL_AWARENESS = "ORGANIZATIONAL_AWARENESS",
  /** Knowledge of the principles of organizational development and change management theories, and their applications */
  ORGANIZATIONAL_DEVELOPMENT = "ORGANIZATIONAL_DEVELOPMENT",
  /** Knowledge of the methods, techniques, and tools used to analyze program, organizational, and mission performance; includes methods that deliver key performance information (for example, comparative, trend, diagnostic, root cause, predictive) used to inform decisions, actions, communications, and accountability systems */
  ORGANIZATIONAL_PERFORMANCE_ANALYSIS = "ORGANIZATIONAL_PERFORMANCE_ANALYSIS",
  /** Knowledge of materials, methods, and appropriate tools to apply paint and other protective coating materials on drywall, wood, metal, glass, and other surfaces */
  PAINTING = "PAINTING",
  /** Develops networks and builds alliances; collaborates across boundaries to build strategic relationships and achieve common goals */
  PARTNERING = "PARTNERING",
  /** Knowledge of the concepts, principles, and theories of plant, insect, or animal diseases and host_AND_pathogen relationships, including effects on natural and managed ecosystems */
  PATHOLOGY = "PATHOLOGY",
  /** Quickly and accurately sees detail in words, numbers, pictures, and graphs */
  PERCEPTUAL_SPEED = "PERCEPTUAL_SPEED",
  /** Knowledge of performance management concepts, principles, and practices related to planning, monitoring, rating, and rewarding employee performance */
  PERFORMANCE_MANAGEMENT = "PERFORMANCE_MANAGEMENT",
  /** Knowledge of the principles and methods for evaluating program or organizational performance using financial and nonfinancial measures, including identification of evaluation factors (for example, workload, personnel requirements), metrics, and outcomes */
  PERFORMANCE_MEASUREMENT = "PERFORMANCE_MEASUREMENT",
  /** Sees objects or movement of objects to ones side when the eyes are focused forward */
  PERIPHERAL_VISION = "PERIPHERAL_VISION",
  /** Knowledge of hiring, classification, benefits, labor relations, negotiation, and Federal, state, and local employment regulations */
  PERSONNEL_AND_HUMAN_RESOURCES = "PERSONNEL_AND_HUMAN_RESOURCES",
  /** Knowledge of methods and controls of personnel, public safety, and security operations; investigation and inspection techniques; or rules, regulations, precautions, and prevention techniques for the protection of people, data, or property */
  PERSONNEL_SECURITY_AND_SAFETY = "PERSONNEL_SECURITY_AND_SAFETY",
  /** Knowledge of pest species and the methods and materials, including chemicals, for control or prevention */
  PEST_CONTROL = "PEST_CONTROL",
  /** Knowledge of the concepts, principles, theories, and methods related to the exploration, development, extraction, recovery, processing, and conservation of fluid minerals, geothermal resources, organic compounds, or natural gas resources */
  PETROLEUM_ENGINEERING = "PETROLEUM_ENGINEERING",
  /** Knowledge of different philosophical systems, including their basic principles, values, ethics, ways of  thinking, customs, religions, and practices, and their impact on human culture */
  PHILOSOPHY = "PHILOSOPHY",
  /** Knowledge of the concepts, principles, theories, and methods to investigate and apply the relations between space, time, matter, and energy in the areas of gravity, atomic principles, mechanics, heat, light, sound, electricity, magnetism, and related natural phenomena */
  PHYSICAL_SCIENCES = "PHYSICAL_SCIENCES",
  /** Knowledge of methods and controls to protect an organization from natural or man-made threats to physical locations where information systems equipment is located or work is performed (for example, computer rooms, work locations, and equipment rooms) */
  PHYSICAL_SECURITY = "PHYSICAL_SECURITY",
  /** Exerts maximum muscle force to lift, push, pull, or carry objects; performs moderately laboring work */
  PHYSICAL_STRENGTH = "PHYSICAL_STRENGTH",
  /** Ability to bend, lift, climb, stand, and walk for long periods of time; ability to perform moderately heavy laboring work */
  PHYSICAL_STRENGTH_AND_AGILITY = "PHYSICAL_STRENGTH_AND_AGILITY",
  /** Knowledge and prediction of physical principles, laws, and applications including air, water, material dynamics, light, atomic principles, heat, electric theory, earth formations, and meteorological and related natural phenomena */
  PHYSICS = "PHYSICS",
  /** Knowledge of the principles, methods, and tools used for risk assessment and mitigation, including assessment of failures and their consequences */
  RISK_MANAGEMENT = "RISK_MANAGEMENT",
  /** Organizes work, sets priorities, and determines resource requirements; determines short- or long-term goals and strategies to achieve them; coordinates with other organizations or parts of the organization to accomplish goals; monitors progress and evaluates outcomes */
  PLANNING_AND_EVALUATING = "PLANNING_AND_EVALUATING",
  /** Knowledge of materials, methods, and the appropriate tools to install, maintain, or repair pipelines, pipe systems, and fixtures, including water, air, steam, gas, chemicals, or sewage */
  PLUMBING_AND_PIPEFITTING = "PLUMBING_AND_PIPEFITTING",
  /** Identifies the internal and external politics that impact the work of the organization Perceives organizational and political reality and acts accordingly */
  POLITICAL_SAVVY = "POLITICAL_SAVVY",
  /** Knowledge of generally accepted accounting principles, standards, and practices (for example, double entry accounting, accrual accounting), including the full accounting cycle and the preparation of work sheets, financial statements, ledgers, and journals */
  PRINCIPLES_OF_ACCOUNTING = "PRINCIPLES_OF_ACCOUNTING",
  /** Knowledge of the basic principles, practices, and methods of financial management to include requisitions, apportionments, allotments, investments, fiscal management, activity reporting, and fiscal year guidelines */
  PRINCIPLES_OF_FINANCE = "PRINCIPLES_OF_FINANCE",
  /** Identifies and analyzes problems; weighs relevance and accuracy of information; generates and evaluates alternative solutions; makes recommendations */
  PROBLEM_SOLVING = "PROBLEM_SOLVING",
  /** Knowledge of the principles, methods, and procedures used for the automated control of a process, including the design, development, and maintenance of associated software, hardware, and systems */
  PROCESS_CONTROL = "PROCESS_CONTROL",
  /** Knowledge of methods for researching and analyzing external products to determine their potential for meeting organizational standards and business needs */
  PRODUCT_EVALUATION = "PRODUCT_EVALUATION",
  /** Knowledge of inputs, outputs, raw materials, waste, quality control, costs, maintaining inventory, and techniques for maximizing the manufacture and distribution of goods */
  PRODUCTION_AND_PROCESSING = "PRODUCTION_AND_PROCESSING",
  /** Knowledge of the principles, methods, or tools for developing, scheduling, coordinating, and managing projects and resources, including monitoring and inspecting costs, work, and contractor performance */
  PROJECT_MANAGEMENT = "PROJECT_MANAGEMENT",
  /** Knowledge of the concepts, principles, and theories of liquid, solid, electrical, chemical, electrochemical, or nuclear propulsion and power generation systems, their component parts and subsystems, and the direct and indirect conversion of energy into power for various applications */
  PROPULSION_AND_POWER = "PROPULSION_AND_POWER",
  /** Knowledge of the concepts, principles, and theories of human behavior and performance in various contexts, mental processes, or the assessment and treatment of behavioral and affective disorders */
  PSYCHOLOGY = "PSYCHOLOGY",
  /** Knowledge of functions, principles, methods, and techniques of public planning, including those related to community planning, outdoor recreation planning, and natural resource management, such as demand forecasting, environmental impact analysis, financial forecasting, and land use planning and zoning */
  PUBLIC_PLANNING = "PUBLIC_PLANNING",
  /** Knowledge of materials, methods, and appropriate tools to construct, maintain, or repair road surfaces, including sidewalks, parking lots, runways, etc */
  ROAD_WORK_AND_PAVEMENT = "ROAD_WORK_AND_PAVEMENT",
  /** Knowledge of military, weaponry, and intelligence operations; public safety and security operations; occupational health and safety; investigation and inspection techniques; or rules, regulations, precautions, and prevention techniques for the protection of people, data, and property */
  PUBLIC_SAFETY_AND_SECURITY = "PUBLIC_SAFETY_AND_SECURITY",
  /** Shows a commitment to serve the public Ensures that actions meet public needs; aligns organizational objectives and practices with public interests */
  PUBLIC_SERVICE_MOTIVATION = "PUBLIC_SERVICE_MOTIVATION",
  /** Knowledge of the principles, methods, and tools of quality assurance and quality control used to ensure a product fulfills functional requirements and standards */
  QUALITY_ASSURANCE = "QUALITY_ASSURANCE",
  /** Knowledge of the principles, methods, and tools of quality assurance, quality control, and reliability used to ensure that a project, system, or product fulfills requirements and standards */
  QUALITY_MANAGEMENT = "QUALITY_MANAGEMENT",
  /** Knowledge of the concepts, principles, and theories of non-forested or forested land ecosystems, including rangeland use, management, and monitoring; conducting inventories; and the role of disturbances in rangeland ecosystems */
  RANGELAND_MANAGEMENT = "RANGELAND_MANAGEMENT",
  /** Understands and interprets written material, including technical materials, rules, regulations, instructions, reports, charts, graphs, or tables; applies what is learned from written material to specific situations */
  READING = "READING",
  /** Understands and interprets written material, including technical material, rules, regulations, instructions, reports, charts, graphs, or tables; applies what is learned from written material to specific situations */
  READING_COMPREHENSION = "READING_COMPREHENSION",
  /** Knowledge of real estate principles, practices, markets, and values */
  REAL_ESTATE = "REAL_ESTATE",
  /** Identifies rules, principles, or relationships that explain facts, data, or other information; analyzes information and makes correct inferences or draws accurate conclusions */
  REASONING = "REASONING",
  /** Knowledge of HR concepts, principles, and practices related to identifying, attracting, and selecting individuals and placing them into positions to address changing organizational needs */
  RECRUITMENT_AND_PLACEMENT = "RECRUITMENT_AND_PLACEMENT",
  /** Knowledge of the concepts, principles, theories, and methods necessary to obtain, use, and interpret data from remote sensing sources, including aircrafts and satellites */
  REMOTE_SENSING = "REMOTE_SENSING",
  /** Knowledge of the principles and methods to identify, analyze, specify, design, and manage functional and infrastructure requirements; includes translating functional requirements into technical requirements used for logical design or presenting alternative technologies or approaches */
  REQUIREMENTS_ANALYSIS = "REQUIREMENTS_ANALYSIS",
  /** Knowledge of the scientific principles, methods, and processes used to conduct a systematic and objective inquiry; including study design, collection, analysis, and interpretation of data; and the reporting of results */
  RESEARCH = "RESEARCH",
  /** Deals effectively with pressure; remains optimistic and persistent, even under adversity Recovers quickly from setbacks */
  RESILIENCE = "RESILIENCE",
  /** Knowledge of techniques and methods used to restrain hostile individuals, including the models and guidelines on appropriate level and nature of force for self-defense */
  RESTRAINT_AND_SELF_DEFENSE = "RESTRAINT_AND_SELF_DEFENSE",
  /** Knowledge of the concepts, principles, theories, and methods to identify, control, mitigate, and eliminate safety hazards in the design and use of facilities, equipment, operations, and work processes */
  SAFETY_ENGINEERING = "SAFETY_ENGINEERING",
  /** Knowledge of showing, promoting, and selling products and services */
  SALES_AND_MARKETING = "SALES_AND_MARKETING",
  /** Knowledge of the laws, principles and methods of conducting searches on personal property such as vehicles, documents, buildings, and items */
  SEARCH = "SEARCH",
  /** Knowledge of the laws, regulations, and guidelines related to securing personnel, facilities, and information, including the requirements for handling, transporting, and protecting classified information and proper reporting of security incidents */
  SECURITY = "SECURITY",
  /** Knowledge of the laws, regulations, and procedures for property seizure, including chain of custody requirements and procedures to catalog and secure seized property */
  SEIZURE = "SEIZURE",
  /** Believes in own self-worth; maintains a positive view of self and displays a professional image */
  SELF_ESTEEM = "SELF_ESTEEM",
  /** Sets well-defined and realistic personal goals; displays a high level of initiative, effort, and commitment towards completing assignments in a timely manner; works with minimal supervision; is motivated to achieve; demonstrates responsible behavior */
  SELF_MANAGEMENT = "SELF_MANAGEMENT",
  /** Knowledge of the concepts, principles, and theories of group behavior and dynamics; societal trends and influences; and cultures, their history, migrations, ethnicity, and origins */
  SOCIOLOGY_AND_ANTHROPOLOGY = "SOCIOLOGY_AND_ANTHROPOLOGY",
  /** Knowledge of the principles, methods, and tools for designing, developing, and testing software in a given environment */
  SOFTWARE_DEVELOPMENT = "SOFTWARE_DEVELOPMENT",
  /** Knowledge of software engineering design and development methodologies, paradigms, and tools; the software life cycle; software reusability; and software reliability metrics */
  SOFTWARE_ENGINEERING = "SOFTWARE_ENGINEERING",
  /** Knowledge of the principles, methods, and tools for analyzing and developing software test and evaluation procedures */
  SOFTWARE_TESTING_AND_EVALUATION = "SOFTWARE_TESTING_AND_EVALUATION",
  /** Knowledge of the concepts, principles, or theories of soil composition, formation, classification, mapping, testing, and management, including erosion, pollution, conservation, and watershed management */
  SOIL_SCIENCE = "SOIL_SCIENCE",
  /** Knowledge of physical science and engineering necessary to conduct research or study the solar system and beyond */
  SPACE_SCIENCE = "SPACE_SCIENCE",
  /** Knows ones location in relation to the environment; determines where other objects are in relation to ones self (for example, when using a map) */
  SPATIAL_ORIENTATION = "SPATIAL_ORIENTATION",
  /** Uses correct English grammar to organize and communicate ideas in words that are appropriate to listeners and situations; uses body language appropriately */
  SPEAKING = "SPEAKING",
  /** Knowledge of the concepts, practices, and techniques used to identify, engage, influence, and monitor relationships with individuals and groups connected to a work effort; including those actively involved, those who exert influence over the process and its results, and those who have a vested interest in the outcome (positive or negative) */
  STAKEHOLDER_MANAGEMENT = "STAKEHOLDER_MANAGEMENT",
  /** Exerts oneself physically over long periods of time without tiring (which may include performing repetitive tasks such as data entry, coding, hammering or lifting objects) */
  STAMINA = "STAMINA",
  /** Knowledge of standards that either are compliant with or derived from established standards or guidelines */
  STANDARDS = "STANDARDS",
  /** Formulates objectives and priorities, and implements plans consistent with the long-term interests of the organization in a global environment  Capitalizes on opportunities and manages risks */
  STRATEGIC_THINKING = "STRATEGIC_THINKING",
  /** Deals calmly and effectively with high stress situations (for example, tight deadlines, hostile individuals, emergency situations, dangerous situations) */
  STRESS_TOLERANCE = "STRESS_TOLERANCE",
  /** Knowledge of the concepts, principles, theories, and methods related to the design and analysis of complex structures using a variety of materials Structures may include aerospace systems or structures, and other determinate or indeterminate systems */
  STRUCTURAL_ENGINEERING = "STRUCTURAL_ENGINEERING",
  /** Knowledge of surveillance and counter-surveillance techniques, policies, and laws, including overt and covert methods and electronic, optical, and video surveillance methods and tools */
  SURVEILLANCE = "SURVEILLANCE",
  /** Knowledge of the concepts, principles, theories, and methods used in the measurement or determination of land boundaries, distances, elevations, areas, angles, and other features of the earths surface */
  SURVEYING = "SURVEYING",
  /** Knowledge of the practice of integrating multiple disciplines into a team as part of a structured development process throughout a systems life cycle */
  SYSTEMS_ENGINEERING = "SYSTEMS_ENGINEERING",
  /** Knowledge of the principles, methods, and procedures for installing, integrating, and optimizing information systems components */
  SYSTEMS_INTEGRATION = "SYSTEMS_INTEGRATION",
  /** Knowledge of systems life cycle management concepts used to plan, develop, implement, operate, and maintain information systems */
  SYSTEMS_LIFE_CYCLE = "SYSTEMS_LIFE_CYCLE",
  /** Knowledge of principles, methods, and tools for analyzing and developing systems testing and evaluation procedures and technical characteristics of IT systems, including identifying critical operational issues */
  SYSTEMS_TESTING_AND_EVALUATION = "SYSTEMS_TESTING_AND_EVALUATION",
  /** Knowledge of accounting and tax law for individuals, sole proprietorships, partnerships, and corporations */
  TAX_LAW = "TAX_LAW",
  /** Helps others learn; identifies training needs; provides constructive reinforcement; coaches others on how to perform tasks; acts as a mentor */
  TEACHES_OTHERS = "TEACHES_OTHERS",
  /** Helps others learn through formal or informal methods; identifies training needs; provides constructive feedback; coaches others on how to perform tasks; acts as a mentor */
  TEACHING_OTHERS = "TEACHING_OTHERS",
  /** Inspires and fosters team commitment, spirit, pride, and trust Facilitates cooperation and motivates team members to accomplish group goals */
  TEAM_BUILDING = "TEAM_BUILDING",
  /** Encourages and facilitates cooperation, pride, trust, and group identity; fosters commitment and team spirit; works with others to achieve goals */
  TEAMWORK = "TEAMWORK",
  /** Uses knowledge that is acquired through formal training or extensive on-the-job experience to perform ones job; works with, understands, and evaluates technical information related to the job; advises others on technical issues */
  TECHNICAL_COMPETENCE = "TECHNICAL_COMPETENCE",
  /** Understands and appropriately applies principles, procedures, requirements, regulations, and policies related to specialized expertise */
  TECHNICAL_CREDIBILITY = "TECHNICAL_CREDIBILITY",
  /** Knowledge of procedures for developing technical and operational support documentation */
  TECHNICAL_DOCUMENTATION = "TECHNICAL_DOCUMENTATION",
  /** Troubleshoots, diagnoses, analyzes, and identifies system malfunctions to determine the source and cause of the problem */
  TECHNICAL_PROBLEM_SOLVING = "TECHNICAL_PROBLEM_SOLVING",
  /** Uses machines, tools, instruments, or equipment effectively; uses computers and computer applications to analyze and communicate information in the appropriate format */
  TECHNOLOGY_APPLICATION = "TECHNOLOGY_APPLICATION",
  /** Knowledge of developments and new applications of information technology (hardware, software, telecommunications), emerging technologies and their applications to business processes, and applications and implementation of information systems to meet organizational requirements */
  TECHNOLOGY_AWARENESS = "TECHNOLOGY_AWARENESS",
  /** Keeps up-to-date on technological developments  Makes effective use of technology to achieve results  Ensures access to and security of technology systems */
  TECHNOLOGY_MANAGEMENT = "TECHNOLOGY_MANAGEMENT",
  /** Knowledge of the concepts, principles, and theories of transmissions, broadcasting, switching, control, construction, or operation of telecommunications systems */
  TELECOMMUNICATIONS = "TELECOMMUNICATIONS",
  /** Knowledge of materials, methods, and appropriate tools to make and repair items made of fabric or leather */
  TEXTILES = "TEXTILES",
  /** Knowledge of diagnosis and treatment of physical and mental ailments, and career guidance */
  THERAPY_AND_COUNSELING = "THERAPY_AND_COUNSELING",
  /** Knowledge of materials, methods, and appropriate tools to make or repair metal parts, tools, gauges, models,  patterns, and machines */
  TOOLMAKING = "TOOLMAKING",
  /** Knowledge of principles and methods for moving people or goods by air, rail, sea, or road, including costs and limits */
  TRANSPORTATION = "TRANSPORTATION",
  /** Knowledge of the concepts, principles, theories, and methods applicable to planning, designing, and constructing of transportation systems including traffic analysis, signal analysis, highway capacity, pavement design, bridge construction, planning of transportation projects, environmental analysis of transportation facilities, and transportation network analysis */
  TRANSPORTATION_ENGINEERING = "TRANSPORTATION_ENGINEERING",
  /** Knowledge of motor vehicle engines, parts, and systems, including their designs, uses, repair, and maintenance */
  VEHICLE_MAINTENANCE = "VEHICLE_MAINTENANCE",
  /** Knowledge of procedures for operating motor vehicles, including cars, trucks, or watercraft */
  VEHICLE_OPERATION = "VEHICLE_OPERATION",
  /** Understands where the organization is headed and how to make a contribution; takes a long-term view and recognizes opportunities to help the organization accomplish its objectives or move toward the vision */
  VISION = "VISION",
  /** Accurately matches or detects differences among colors, including shades of color and brightness */
  VISUAL_COLOR_DISCRIMINATION = "VISUAL_COLOR_DISCRIMINATION",
  /** Accurately identifies people, animals, or objects based on knowledge of their characteristics */
  VISUAL_IDENTIFICATION = "VISUAL_IDENTIFICATION",
  /** Knowledge of the principles, methods, and tools for assessing vulnerabilities, and developing or recommending appropriate mitigation countermeasures */
  VULNERABILITIES_ASSESSMENT = "VULNERABILITIES_ASSESSMENT",
  /** Knowledge of the principles and methods of web technologies, tools, and delivery systems, including web security, privacy policy practices, and user interface issues */
  WEB_TECHNOLOGY = "WEB_TECHNOLOGY",
  /** Knowledge of the concepts, principles, and theories of wildlife, including classification, taxonomy, population dynamics, distribution, habitat requirements, life histories, reproduction, behaviors, conservation, and care of wildlife */
  WILDLIFE_BIOLOGY = "WILDLIFE_BIOLOGY",
  /** Knowledge of HR concepts, principles, and practices related to determining workload projections and current and future competency gaps to align human capital with organizational goals */
  WORKFORCE_PLANNING = "WORKFORCE_PLANNING",
  /** Recognizes or uses correct English grammar, punctuation, and spelling; communicates information (for example, facts, ideas, or messages) in a succinct and organized manner; produces written information, which may include technical material, that is appropriate for the intended audience */
  WRITING = "WRITING",
  /** Writes in a clear, concise, organized, and convincing manner for the intended audience */
  WRITTEN_COMMUNICATION = "WRITTEN_COMMUNICATION",
}
