// This file is autogenerated - Please do not edit 

export enum ComputeCpuArchitecture {
  /** 32-bit ARM */
  ARM = "ARM",
  /** 64-bit ARM */
  ARM64 = "ARM64",
  /** 32-bit x86 (i386, etc) */
  X86_32 = "X86_32",
  /** 64-bit x86 */
  X86_64 = "X86_64",
  /** RISC */
  RISC = "RISC",
  /** MIPS */
  MIPS = "MIPS",
  /** SPARC */
  SPARC = "SPARC",
  /** ALPHA */
  ALPHA = "ALPHA",
}
