// This file is autogenerated - Please do not edit 

export enum CompetencyTerm {
  /** The annual anniversary, calendar day to calendar day (365 days) */
  ANNUAL = "ANNUAL",
  /** The third year anniversary */
  THREE_YEARS = "THREE_YEARS",
  /** End of the current calendar year */
  CURRENT_CALENDAR_YEAR = "CURRENT_CALENDAR_YEAR",
  /** End of the next calendar year */
  NEXT_CALENDAR_YEAR = "NEXT_CALENDAR_YEAR",
}
