// This file is autogenerated - Please do not edit 

export enum ConditionOperation {
  /** Equals == */
  EQ = "EQ",
  /** Not Equals != */
  NE = "NE",
  /** Greater Than > */
  GE = "GE",
  /** Less Than < */
  LT = "LT",
  /** Greater Than or Equal >= */
  GTE = "GTE",
  /** Less Than or Equal <= */
  LTE = "LTE",
  /** In */
  IN = "IN",
  /** Not In */
  NOT_IN = "NOT_IN",
  /** Contains */
  CONTAINS = "CONTAINS",
  /** Does Not Contain */
  NOT_CONTAINS = "NOT_CONTAINS",
  /** Is Null or Empty */
  IS_NULL = "IS_NULL",
  /** Is Not Null or Empty */
  IS_NOT_NULL = "IS_NOT_NULL",
  /** Pattern Match */
  LIKE = "LIKE",
}
