// This file is autogenerated - Please do not edit 

export enum ContactType {
  /** Home */
  HOME = "HOME",
  /** Work/Office */
  WORK = "WORK",
  /** Fax */
  FAX = "FAX",
  /** Mobile/SMS */
  MOBILE = "MOBILE",
  /** VoIP */
  VOIP = "VOIP",
  /** Other */
  OTHER = "OTHER",
  /** School */
  SCHOOL = "SCHOOL",
}
