// This file is autogenerated - Please do not edit 

export enum CryptoModuleType {
  /** Block storage encryption */
  BLOCK = "BLOCK",
  /** Filesystem level encryption */
  FILESYSTEM = "FILESYSTEM",
  /** File level encryption */
  FILE = "FILE",
  /** Object level encryption */
  OBJECT = "OBJECT",
  /** Database level encryption */
  DATABASE = "DATABASE",
  /** Application level encryption */
  APP = "APP",
  /** Transport Layer Encryption (SSL/HTTPS) */
  TLS = "TLS",
  /** Virutal Private Network */
  VPN = "VPN",
  /** Secure shell encryption */
  SSH = "SSH",
  /** Custom encryption */
  OTHER = "OTHER",
}
