// This file is autogenerated - Please do not edit 

export enum Cvss_version {
  /** 4.0 */
  V4_0 = "V4_0",
  /** 3.1 */
  V3_1 = "V3_1",
  /** 3.0 */
  V3_0 = "V3_0",
  /** 2.0 */
  V2_0 = "V2_0",
}
