// This file is autogenerated - Please do not edit 

export enum Cvssv3_scope {
  /** An exploited vulnerability can affect resources beyond the security scope managed by the security authority of the vulnerable component. In this case, the vulnerable component and the impacted component are different and managed by different security authorities. */
  CHANGED = "CHANGED",
  /** An exploited vulnerability can only affect resources managed by the same security authority. In this case, the vulnerable component and the impacted component are either the same, or both are managed by the same security authority. */
  UNCHANGED = "UNCHANGED",
}
