// This file is autogenerated - Please do not edit 

export enum Cvssv4_privilegesRequired {
  /** The attacker is unauthenticated prior to attack, and therefore does not require any access to settings or files of the vulnerable system to carry out an attack. */
  NONE = "NONE",
  /** The attacker requires privileges that provide basic capabilities that are typically limited to settings and resources owned by a single low-privileged user. Alternatively, an attacker with Low privileges has the ability to access only non-sensitive resources. */
  LOW = "LOW",
  /** The attacker requires privileges that provide significant (e.g., administrative) control over the vulnerable system allowing full access to the vulnerable system’s settings and files. */
  HIGH = "HIGH",
}
