// This file is autogenerated - Please do not edit 

export enum Cvssv2_confidentialityImpact {
  /** {"There is no impact to the confidentiality of the system."} */
  NONE = "NONE",
  /** {"There is considerable informational disclosure. Access to some system files is possible, but the attacker does not have control over what is obtained, or the scope of the loss is constrained. An example is a vulnerability that divulges only certain tables in a database."} */
  PARTIAL = "PARTIAL",
  /** {"There is total information disclosure, resulting in all system files being revealed. The attacker is able to read all of the system's data (memory, files, etc.)"} */
  COMPLETE = "COMPLETE",
}
