// This file is autogenerated - Please do not edit 

export enum Cvssv3_userInteraction {
  /** The vulnerable system can be exploited without interaction from any user. */
  NONE = "NONE",
  /** Successful exploitation of this vulnerability requires a user to take some action before the vulnerability can be exploited. For example, a successful exploit may only be possible during the installation of an application by a system administrator. */
  REQUIRED = "REQUIRED",
}
