// This file is autogenerated - Please do not edit 

export enum Cvssv2_availabilityImpact {
  /** There is no impact to the availability of the system. */
  NONE = "NONE",
  /** There is reduced performance or interruptions in resource availability. An example is a network-based flood attack that permits a limited number of successful connections to an Internet service. */
  PARTIAL = "PARTIAL",
  /** There is a total shutdown of the affected resource. The attacker can render the resource completely unavailable. */
  COMPLETE = "COMPLETE",
}
