// This file is autogenerated - Please do not edit 

export enum Cvssv3_confidentialityImpact {
  /** There is a total loss of confidentiality, resulting in all resources within the impacted component being divulged to the attacker. Alternatively, access to only some restricted information is obtained, but the disclosed information presents a direct, serious impact. For example, an attacker steals the administrator's password, or private encryption keys of a web server. */
  HIGH = "HIGH",
  /** There is some loss of confidentiality. Access to some restricted information is obtained, but the attacker does not have control over what information is obtained, or the amount or kind of loss is limited. The information disclosure does not cause a direct, serious loss to the impacted component. */
  LOW = "LOW",
  /** There is no loss of confidentiality within the impacted component. */
  NONE = "NONE",
}
