// This file is autogenerated - Please do not edit 

export enum Cvssv4_subsequentSystemIntegrityImpact {
  /** There is a total loss of integrity, or a complete loss of protection. For example, the attacker is able to modify any/all files protected by the Subsequent System. Alternatively, only some files can be modified, but malicious modification would present a direct, serious consequence to the Subsequent System. */
  HIGH = "HIGH",
  /** Modification of data is possible, but the attacker does not have control over the consequence of a modification, or the amount of modification is limited. The data modification does not have a direct, serious impact to the Subsequent System. */
  LOW = "LOW",
  /** There is no loss of integrity within the Subsequent System or all integrity impact is constrained to the Vulnerable System. */
  NONE = "NONE",
}
