// This file is autogenerated - Please do not edit 

export enum Cvssv2_authentication {
  /** Exploiting the vulnerability requires that the attacker authenticate two or more times, even if the same credentials are used each time. An example is an attacker authenticating to an operating system in addition to providing credentials to access an application hosted on that system. */
  MULTIPLE = "MULTIPLE",
  /** The vulnerability requires an attacker to be logged into the system (such as at a command line or via a desktop session or web interface). */
  SINGLE = "SINGLE",
  /** Authentication is not required to exploit the vulnerability. */
  NONE = "NONE",
}
