// This file is autogenerated - Please do not edit 

export enum Cvssv3_integrityImpact {
  /** There is a total loss of integrity, or a complete loss of protection. For example, the attacker is able to modify any/all files protected by the impacted component. Alternatively, only some files can be modified, but malicious modification would present a direct, serious consequence to the impacted component. */
  HIGH = "HIGH",
  /** Modification of data is possible, but the attacker does not have control over the consequence of a modification, or the amount of modification is limited. The data modification does not have a direct, serious impact on the impacted component. */
  LOW = "LOW",
  /** There is no loss of integrity within the impacted component. */
  NONE = "NONE",
}
