// This file is autogenerated - Please do not edit 

export enum DataClassification {
  /** Public */
  PUBLIC = "PUBLIC",
  /** Private */
  PRIVATE = "PRIVATE",
  /** Restricted */
  RESTRICTED = "RESTRICTED",
  /** Confidential */
  CONFIDENTIAL = "CONFIDENTIAL",
  /** Proprietary */
  PROPRIETARY = "PROPRIETARY",
  /** Internal Use Only */
  INTERNAL = "INTERNAL",
}
