// This file is autogenerated - Please do not edit 

export enum DurationType {
  /** Specific end date */
  ABSOLUTE = "ABSOLUTE",
  /** Relative end date */
  RELATIVE = "RELATIVE",
  /** No end date */
  FOREVER = "FOREVER",
}
