// This file is autogenerated - Please do not edit 

export enum EmploymentType {
  /** Trainee */
  TRAINEE = "TRAINEE",
  /** Seasonal */
  SEASONAL = "SEASONAL",
  /** Internship */
  INTERN = "INTERN",
  /** Full time */
  FULL_TIME = "FULL_TIME",
  /** Part time */
  PART_TIME = "PART_TIME",
  /** Temporary */
  TEMPORARY = "TEMPORARY",
}
