// This file is autogenerated - Please do not edit 

export enum EmploymentStatus {
  /** Long-term disability */
  LT_DISABILITY = "LT_DISABILITY",
  /** Inactive */
  INACTIVE = "INACTIVE",
  /** Active */
  ACTIVE = "ACTIVE",
  /** Terminated */
  TERMINATED = "TERMINATED",
  /** Resigned */
  RESIGNED = "RESIGNED",
  /** Furloughed */
  FURLOUGHED = "FURLOUGHED",
  /** Leave */
  LEAVE = "LEAVE",
  /** Short-term disablity */
  ST_DISABILITY = "ST_DISABILITY",
}
