// This file is autogenerated - Please do not edit 

export enum EndUserDeviceEnrollmentType {
  /** User driven enrollment through BYOD channel */
  USER_BYOD = "USER_BYOD",
  /** User enrollment with a device enrollment manager account */
  DEVICE_MANAGER = "DEVICE_MANAGER",
  /** Apple bulk enrollment with user challenge. (DEP, Apple Configurator) */
  APPLE_USER = "APPLE_USER",
  /** Apple bulk enrollment without user challenge. (DEP, Apple Configurator, Mobile Config) */
  APPLE_BULK = "APPLE_BULK",
  /** Windows 10 Azure AD Join. Windows 10 bulk Azure AD Join */
  DOMAIN_JOIN = "DOMAIN_JOIN",
  /** Windows 10 Bulk enrollment through ICD with certificate */
  WINDOWS_BULK = "WINDOWS_BULK",
  /** Windows 10 automatic enrollment. (Add work account) */
  WINDOWS_AUTO = "WINDOWS_AUTO",
  /** Windows 10 Co-Management triggered by AutoPilot or Group Policy */
  AUTOPILOT = "AUTOPILOT",
  /** Azure AD Join enrollment when an Azure VM is provisioned */
  AZURE_AD_VM = "AZURE_AD_VM",
  /** Android Enterprise Dedicated Device */
  ANDROID_DEDICATED = "ANDROID_DEDICATED",
  /** Android Enterprise Fully Managed */
  ANDROID_MANAGED = "ANDROID_MANAGED",
  /** Android Enterprise Corporate Work Profile */
  ANDROID_WORK_PROFILE = "ANDROID_WORK_PROFILE",
  /** Unknown / value not collected */
  UNKNOWN = "UNKNOWN",
}
