// This file is autogenerated - Please do not edit 

export enum EndUserDeviceRegistrationState {
  /** The device is registered */
  REGISTERED = "REGISTERED",
  /** The device is not registered */
  UNREGISTERED = "UNREGISTERED",
  /** The device has been blocked, wiped or retired. */
  REVOKED = "REVOKED",
  /** The device has a key conflict or another operational error */
  ERROR = "ERROR",
  /** The device is pending approval */
  PENDING_APPROVAL = "PENDING_APPROVAL",
  /** The device certificate has been reset */
  CERTIFICATE_RESET = "CERTIFICATE_RESET",
  /** The device is not registered and pending enrollment */
  PENDING_ENROLLMENT = "PENDING_ENROLLMENT",
  /** Unknown */
  UNKNOWN = "UNKNOWN",
}
