// This file is autogenerated - Please do not edit 

export enum EndUserDeviceType {
  /** Laptop */
  LAPTOP = "LAPTOP",
  /** Desktop */
  DESKTOP = "DESKTOP",
  /** Workstation */
  WORKSTATION = "WORKSTATION",
  /** Server */
  SERVER = "SERVER",
  /** Phone */
  PHONE = "PHONE",
  /** Tablet */
  TABLET = "TABLET",
  /** Unknown */
  UNKNOWN = "UNKNOWN",
}
