// This file is autogenerated - Please do not edit 

export enum EndUserDeviceOwnerType {
  /** Owned by person */
  PERSONAL = "PERSONAL",
  /** Owned by company */
  COMPANY = "COMPANY",
  /** Unknown */
  UNKNOWN = "UNKNOWN",
}
