// This file is autogenerated - Please do not edit 

export enum EnrollmentStatus {
  /** Not Started */
  NOT_STARTED = "NOT_STARTED",
  /** In Progress */
  IN_PROGRESS = "IN_PROGRESS",
  /** Completed */
  COMPLETED = "COMPLETED",
  /** Passed */
  PASSED = "PASSED",
  /** Past Due */
  PAST_DUE = "PAST_DUE",
}
