// This file is autogenerated - Please do not edit 

export enum EnvironmentType {
  /** Internal controlled facility and/or network assets */
  PHYSICAL = "PHYSICAL",
  /** Extnernally controlled facility and network assets */
  VIRTUAL = "VIRTUAL",
  /** Environment that spans internal and external facilites and network assets */
  HYBRID = "HYBRID",
}
