// This file is autogenerated - Please do not edit 

export enum FedrampRoleType {
  /** Cloud Service Provider Operations Center */
  CSP_OPERATIONS_CENTER = "CSP_OPERATIONS_CENTER",
  /** Cloud Service Provider Asessment Point of Contact */
  CSP_ASSESSMENT_POC = "CSP_ASSESSMENT_POC",
  /** Cloud Service Provider End of Testing Point of Contact */
  CSP_END_OF_TESTING_POC = "CSP_END_OF_TESTING_POC",
  /** Cloud Service Provider Results Point of Contact */
  CSP_RESULTS_POC = "CSP_RESULTS_POC",
  /** FedRMAP Program Management Office */
  FEDRAMP_PMO = "FEDRAMP_PMO",
  /** FedRAMP Joint Authorization Board */
  FEDRAMP_JAB = "FEDRAMP_JAB",
  /** Penetration Test Team */
  PENETRATION_TEST_TEAM = "PENETRATION_TEST_TEAM",
  /** Assessor */
  ASSESSOR = "ASSESSOR",
  /** Assessment Team */
  ASSESSMENT_TEAM = "ASSESSMENT_TEAM",
  /** Assessment Lead */
  ASSESSMENT_LEAD = "ASSESSMENT_LEAD",
  /** Assesment Executive */
  ASSESSMENT_EXECUTIVE = "ASSESSMENT_EXECUTIVE",
  /** Cloud Service Provider */
  CSP = "CSP",
  /** Penetration Test Team Lead */
  PENETRATION_TEST_LEAD = "PENETRATION_TEST_LEAD",
  /** Other role not listed */
  OTHER = "OTHER",
}
