// This file is autogenerated - Please do not edit 

export enum FilesystemType {
  /** */
  NILFS = "NILFS",
  /** */
  NTFS = "NTFS",
  /** */
  NETWARE = "NETWARE",
  /** */
  NSS = "NSS",
  /** */
  ONEFS = "ONEFS",
  /** */
  OFS = "OFS",
  /** */
  HFS = "HFS",
  /** */
  HPFS = "HPFS",
  /** */
  HTFS = "HTFS",
  /** */
  ISO_9660 = "ISO_9660",
  /** */
  JFS = "JFS",
  /** */
  LFS = "LFS",
  /** */
  MFS = "MFS",
  /** */
  NEXT3 = "NEXT3",
  /** */
  MINIX_FI = "MINIX_FI",
  /** */
  ADFS = "ADFS",
  /** */
  ADVFS = "ADVFS",
  /** */
  APFS = "APFS",
  /** */
  ATHFS = "ATHFS",
  /** */
  BFS = "BFS",
  /** */
  BRTFS = "BRTFS",
  /** */
  CFS = "CFS",
  /** */
  DOS = "DOS",
  /** */
  EFS = "EFS",
  /** */
  EXT2 = "EXT2",
  /** */
  EXT3 = "EXT3",
  /** */
  EXT4 = "EXT4",
  /** */
  EXT3COW = "EXT3COW",
  /** */
  FAT = "FAT",
  /** */
  VFAT = "VFAT",
  /** */
  FATX = "FATX",
  /** */
  FFS = "FFS",
  /** */
  FOSSIL = "FOSSIL",
  /** */
  FILES11 = "FILES11",
  /** */
  FLEXP_MAC = "FLEXP_MAC",
  /** */
  HAMMER = "HAMMER",
  /** */
  HAMMER2 = "HAMMER2",
  /** */
  Os9 = "Os9",
  /** */
  PFS = "PFS",
  /** */
  PRODOS = "PRODOS",
  /** */
  QNX4FS = "QNX4FS",
  /** */
  REFS = "REFS",
  /** */
  REISERFS = "REISERFS",
  /** */
  REISER4 = "REISER4",
  /** */
  RELIANCE = "RELIANCE",
  /** */
  RFS = "RFS",
  /** */
  SKYFS = "SKYFS",
  /** */
  SFS = "SFS",
  /** */
  TUX3 = "TUX3",
  /** */
  UDF = "UDF",
  /** */
  UFS = "UFS",
  /** */
  UFS2 = "UFS2",
  /** */
  VXFS = "VXFS",
  /** */
  VTOC = "VTOC",
  /** */
  XFS = "XFS",
  /** */
  ZFS = "ZFS",
}
