// This file is autogenerated - Please do not edit 

export enum Finding_state {
  /** Active */
  ACTIVE = "ACTIVE",
  /** Inactive */
  INACTIVE = "INACTIVE",
  /** Resolved */
  RESOLVED = "RESOLVED",
  /** Archived */
  ARCHIVED = "ARCHIVED",
}
