// This file is autogenerated - Please do not edit 

export enum HitrustRoleType {
  /** Certified CSF Practitioner (CCSFP) Assessor */
  CCSFP = "CCSFP",
  /** Certified HITRUST Quality Professional (CHQP) Reviewer */
  CHQP = "CHQP",
  /** Enagement Quality Assurance Reviewer */
  QA_REVIEWER = "QA_REVIEWER",
  /** Engagement Executive */
  ENGAGEMENT_EXECTIVE = "ENGAGEMENT_EXECTIVE",
  /** Engagement Lead */
  ENGAGEMENT_LEAD = "ENGAGEMENT_LEAD",
  /** Other role not defined */
  OTHER = "OTHER",
}
