// This file is autogenerated - Please do not edit 

export enum IdpProtocolType {
  /** Security Assertion Markup Language version (SAML) 1.0 */
  SAML_1_0 = "SAML_1_0",
  /** Security Assertion Markup Language version (SAML) 1.1 */
  SAML_1_1 = "SAML_1_1",
  /** Security Assertion Markup Language version (SAML) 2.0 */
  SAML_2_0 = "SAML_2_0",
  /** Open Authorization */
  OAuth = "OAuth",
  /** OpenID 1.0 */
  OpenID_1_0 = "OpenID_1_0",
  /** OpenID 2.0 */
  OpenID_2_0 = "OpenID_2_0",
  /** OpenID Connect (OIDC) */
  OIDC = "OIDC",
  /** WS-Federation */
  WS_FED = "WS_FED",
}
