// This file is autogenerated - Please do not edit 

export enum IncidentType {
  /** Training/exercises performed for incident handling training purposes */
  TRAINING_AND_EXERCISES = "TRAINING_AND_EXERCISES",
  /** Unauthorized privileged access to an information system */
  ROOT_LEVEL_INTRUSION = "ROOT_LEVEL_INTRUSION",
  /** Unauthorized nonprivileged access to an information system */
  USER_LEVEL_INTRUSION = "USER_LEVEL_INTRUSION",
  /** Deliberate attempts to gain unauthorized access that are defeated by normal defensive mechanisms */
  UNSUCCESSFUL_ACTIVITY_ATTEMPT = "UNSUCCESSFUL_ACTIVITY_ATTEMPT",
  /** Activity that denies, degardes, or disrupts normal functionality */
  DENIAL_OF_SERVICE = "DENIAL_OF_SERVICE",
  /** Noncompliant activities such as action or inaction of authorized users */
  NON_COMPLIANCE_ACTIVITY = "NON_COMPLIANCE_ACTIVITY",
  /** Reconnaissance activity that seeks to gather information such as footprinting networks, devices, or applications */
  RECONNAISSANCE = "RECONNAISSANCE",
  /** Installation of software designed and/or deployed by adversaries with malicious intentions */
  MALICIOUS_LOGIC = "MALICIOUS_LOGIC",
  /** Activity deemed suspicious and warrant, or are undergoing, further review */
  INVESTIGATING = "INVESTIGATING",
  /** Suspicious events that after further investigation are determined to be non-malicious activity and do not fit the criteria for any other categories */
  EXPLAINED_ANOMALY = "EXPLAINED_ANOMALY",
}
