// This file is autogenerated - Please do not edit 

export enum IncidentPhase {
  /** Preparation Phase */
  PREPARATION = "PREPARATION",
  /** Detection and Analysis Phase */
  DETECTION_AND_ANALYSIS = "DETECTION_AND_ANALYSIS",
  /** Mitigation Phase */
  MITIGATION = "MITIGATION",
  /** Containment Phase */
  CONTAINMENT = "CONTAINMENT",
  /** Eradication and Recovery Phase */
  ERADICATION_AND_RECOVERY = "ERADICATION_AND_RECOVERY",
  /** Post Incident Activities Phase */
  POST_INCIDENT_ACTIVITY = "POST_INCIDENT_ACTIVITY",
  /** Reporting Phase */
  REPORTING = "REPORTING",
}
