// This file is autogenerated - Please do not edit 

export enum InvestigationStatus {
  /** Active */
  ACTIVE = "ACTIVE",
  /** Suspended */
  SUSPENDED = "SUSPENDED",
  /** Cancelled */
  CANCELLED = "CANCELLED",
  /** Complete */
  COMPLETE = "COMPLETE",
  /** Reopened */
  REOPENED = "REOPENED",
}
