// This file is autogenerated - Please do not edit 

export enum IpProtocol {
  /** Internet Control Message (1) */
  ICMP = "ICMP",
  /** Internet Group Management (2) */
  IGMP = "IGMP",
  /** Transmission Control (6) */
  TCP = "TCP",
  /** User Datagram (17) */
  UDP = "UDP",
  /** All Protocols (-1) */
  ALL = "ALL",
}
