// This file is autogenerated - Please do not edit 

export enum IpRouteFlag {
  /** Up. Route is valid */
  U = "U",
  /** Gateway. Route is to a gateway router rather than to a directly connected network or host */
  G = "G",
  /** Host name. Route is to a host rather than to a network */
  H = "H",
  /** Reject. Set by ARP when an entry expires */
  R = "R",
  /** Dynamic. Route added by a route redirect or RIP */
  D = "D",
  /** Modified. Route modified by a route redirect */
  M = "M",
  /** Cloning. A new route is cloned from this entry when it is used */
  C = "C",
  /** Link. Link-level information, such as the Ethernet MAC address, is present */
  L = "L",
  /** Static. Route added with the route command */
  S = "S",
}
