// This file is autogenerated - Please do not edit 

export enum ItsmServiceType {
  /** Configuration Management */
  CONFIGURATION = "CONFIGURATION",
  /** Change and Release Management */
  CHANGE = "CHANGE",
  /** Incident Management */
  INCIDENT = "INCIDENT",
  /** Vulnerability Management */
  VULNERABILITY = "VULNERABILITY",
  /** Service Level Agreement (SLA) Management */
  SERVICE_LEVEL = "SERVICE_LEVEL",
  /** Request Management */
  REQUEST = "REQUEST",
  /** Talent Management */
  TALENT = "TALENT",
  /** Workflow Management */
  WORKFLOW = "WORKFLOW",
  /** Process Improvement Management */
  PROCESS_IMPROVEMENT = "PROCESS_IMPROVEMENT",
}
