// This file is autogenerated - Please do not edit 

export enum KeyPair_type {
  /** RSA */
  RSA = "RSA",
  /** ED25519 */
  ED25519 = "ED25519",
  /** ECDSA */
  ECDSA = "ECDSA",
  /** DSA */
  DSA = "DSA",
}
