// This file is autogenerated - Please do not edit 

export enum Link_matchType {
  /** Passing or successfully completing a training module */
  SOURCE = "SOURCE",
  /** Failing or unsuccessfully completing a training module */
  TARGET = "TARGET",
}
