// This file is autogenerated - Please do not edit 

export enum LocationType {
  /** Home */
  HOME = "HOME",
  /** Datacenter */
  DATACENTER = "DATACENTER",
  /** Office */
  OFFICE = "OFFICE",
  /** Lab */
  LAB = "LAB",
  /** Warehouse */
  WAREHOUSE = "WAREHOUSE",
  /** Receiving */
  RECEIVING = "RECEIVING",
  /** Mailing */
  MAILING = "MAILING",
  /** Sensitive Compartmented Information Facility (SCIF) */
  SCIF = "SCIF",
  /** Other */
  OTHER = "OTHER",
}
