// This file is autogenerated - Please do not edit 

export enum NetBiosNodeType {
  /** Unknown node type (0) */
  UNKNOWN = "UNKNOWN",
  /** Broadcast node. Uses NetBIOS name queries. (1) */
  BROADCAST = "BROADCAST",
  /** Peer-to-peer node. Uses NBNB/WINS. (2) */
  PEER = "PEER",
  /** Try NetBIOS name queries then use NBNB. (4) */
  MIXED = "MIXED",
  /** Try to yse NBNS then NetBIOS name queries. (8) */
  HYBRID = "HYBRID",
}
