// This file is autogenerated - Please do not edit 

export enum NetworkInterfaceType {
  /** Ethernet network interface */
  ETHERNET = "ETHERNET",
  /** Virutal Local Area Network (VLAN) */
  VLAN = "VLAN",
  /** WiFi network interface */
  WIFI = "WIFI",
  /** Virutal Private Network (VPN) */
  VPN = "VPN",
  /** Cellular/mobile communication network */
  CELLULAR = "CELLULAR",
  /** Wide Area Network (WAN) */
  WAN = "WAN",
  /** Bluetooth */
  BLUETOOTH = "BLUETOOTH",
  /** Virutal */
  VIRUTAL = "VIRUTAL",
  /** Loopback */
  LOOPBACK = "LOOPBACK",
}
