// This file is autogenerated - Please do not edit 

export enum OperationalStatus {
  /** Up/Active/Available */
  UP = "UP",
  /** Down/Inactive/Unavailable */
  DOWN = "DOWN",
  /** Testing/Information */
  TESTING = "TESTING",
  /** Unknown */
  UNKNOWN = "UNKNOWN",
  /** Dormant/Standby/Sleeping */
  DORMANT = "DORMANT",
  /** Not Present/No Media/Unplugged/Blank/Empty */
  NOT_PRESENT = "NOT_PRESENT",
  /** Impaired/Degraded/Intermittent/Overloaded */
  IMPAIRED = "IMPAIRED",
}
