// This file is autogenerated - Please do not edit 

export enum OrganizationEntityType {
  /** Individual */
  INDIVIDUAL = "INDIVIDUAL",
  /** C Corporation */
  C_CORPORATION = "C_CORPORATION",
  /** S Corporation */
  S_CORPORATION = "S_CORPORATION",
  /** Limited Liability Company (LLC) */
  LLC = "LLC",
  /** Partnership */
  PARTNERSHIP = "PARTNERSHIP",
  /** Trust */
  TRUST = "TRUST",
  /** Estate */
  ESTATE = "ESTATE",
}
