// This file is autogenerated - Please do not edit 

export enum OscalAssetType {
  /** Operating System */
  OPERATING_SYSTEM = "OPERATING_SYSTEM",
  /** Database */
  DATABASE = "DATABASE",
  /** Web Server */
  WEB_SERVER = "WEB_SERVER",
  /** DNS Server */
  DNS_SERVER = "DNS_SERVER",
  /** Email Server */
  EMAIL_SERVER = "EMAIL_SERVER",
  /** Directory Server */
  DIRECTORY_SERVER = "DIRECTORY_SERVER",
  /** PBX */
  PBX = "PBX",
  /** Firewall */
  FIREWALL = "FIREWALL",
  /** Router */
  ROUTER = "ROUTER",
  /** Switch */
  SWITCH = "SWITCH",
  /** Storage Array */
  STORAGE_ARRAY = "STORAGE_ARRAY",
  /** Appliance */
  APPLIANCE = "APPLIANCE",
  /** Application */
  APPLICATION = "APPLICATION",
}
