// This file is autogenerated - Please do not edit 

export enum OscalComponentType {
  /** A connection to something outside this system */
  interconnection = "interconnection",
  /** Any software, operating system, or firmware */
  software = "software",
  /** A physical device */
  hardware = "hardware",
  /** A service that may provide APIs */
  service = "service",
  /** An enforceable policy */
  policy = "policy",
  /** A tangible asset used to provide physical protections or countermeasures */
  physical = "physical",
  /** A list of steps or actions to take to achieve some end result */
  process_procedure = "process_procedure",
  /** An applicable plan */
  plan = "plan",
  /** Any guideline or recommendation */
  guidance = "guidance",
  /** Any organizational or industry standard */
  standard = "standard",
  /** An external assessment performed on some other component, that has been validated by a third-party */
  validation = "validation",
}
