// This file is autogenerated - Please do not edit 

export enum OscalRoleType {
  /** Accountable for ensuring the asset is managed in accordance with organizational policies and procedures */
  ASSET_OWNER = "ASSET_OWNER",
  /** Members of the security operations center (SOC) */
  SECURITY_OPERATIONS = "SECURITY_OPERATIONS",
  /** Members of the network operations center (NOC) */
  NETWORK_OPERATIONS = "NETWORK_OPERATIONS",
  /** Responsible for responding to an event that could lead to loss of, or disruption to, an organization's operations, services or functions */
  INCIDENT_RESPONSE = "INCIDENT_RESPONSE",
  /** Responsible for providing information and support to users */
  HELP_DESK = "HELP_DESK",
  /** Responsible for the configuration management processes governing changes to the asset */
  CONFIGURATION_MANAGEMENT = "CONFIGURATION_MANAGEMENT",
  /** Responsible for the creation and maintenance of a component */
  MAINTAINER = "MAINTAINER",
  /** Organization responsible for providing the component, if this is different from the Maintainer role type */
  PROVIDER = "PROVIDER",
  /** Other */
  OTHER = "OTHER",
}
