// This file is autogenerated - Please do not edit 

export enum PartyType {
  /** Employee */
  EMPLOYEE = "EMPLOYEE",
  /** Contractor */
  CONTRACTOR = "CONTRACTOR",
  /** External Entity/Organization */
  PROVIDER = "PROVIDER",
  /** Vendor/Manufacturer/Publisher/Maintainer */
  VENDOR = "VENDOR",
  /** Value Add Reseller (VAR)/Agent/Distributor */
  VAR = "VAR",
}
