// This file is autogenerated - Please do not edit 

export enum PciDssRoleType {
  /** PCI DSS Qualified Security Assessor (QSA) */
  QSA = "QSA",
  /** Approved Scanning Vendor */
  ASV = "ASV",
  /** Point-to-Point Encryption Qualified Security Assessor */
  P2PE_QSA = "P2PE_QSA",
  /** Point-to-Point Encryption Payment Application Qualified Security Assessor */
  P2PE_PA_QSA = "P2PE_PA_QSA",
  /** Internal Security Assessor */
  ISA = "ISA",
  /** Full-time and part-time employees, temporary employees, contractors, and consultants who are “resident” on the entitys site or otherwise have access to the cardholder data environment */
  PERSONNEL = "PERSONNEL",
  /** Primary person responsible for an assessed entity's security-related matters */
  SECURITY_OFFICER = "SECURITY_OFFICER",
  /** Other */
  OTHER = "OTHER",
}
