// This file is autogenerated - Please do not edit 

export enum PermissionType {
  /** Read */
  READ = "READ",
  /** Write */
  WRITE = "WRITE",
  /** Create */
  CREATE = "CREATE",
  /** Update */
  UPDATE = "UPDATE",
  /** Delete */
  DELETE = "DELETE",
  /** Administrative Access */
  ADMIN = "ADMIN",
  /** Execute */
  EXECUTE = "EXECUTE",
  /** Download */
  DOWNLOAD = "DOWNLOAD",
  /** Import */
  IMPORT = "IMPORT",
  /** Export */
  EXPORT = "EXPORT",
  /** Push */
  PUSH = "PUSH",
  /** Pull */
  PULL = "PULL",
  /** Merge */
  MERGE = "MERGE",
  /** Start */
  START = "START",
  /** Stop */
  STOP = "STOP",
  /** Pause */
  PAUSE = "PAUSE",
  /** Invite */
  INVITE = "INVITE",
  /** Other permission type not listed */
  OTHER = "OTHER",
  /** Enable */
  ENABLE = "ENABLE",
  /** Disable */
  DISABLE = "DISABLE",
  /** Connect */
  CONNECT = "CONNECT",
  /** Disconnect */
  DISCONNECT = "DISCONNECT",
  /** Publish */
  PUBLISH = "PUBLISH",
  /** Retire */
  RETIRE = "RETIRE",
  /** Share */
  SHARE = "SHARE",
  /** Tag or Untag */
  TAG = "TAG",
}
