// This file is autogenerated - Please do not edit 

export enum PhysicalEntry_status {
  /** Entry point is open and accessible */
  OPEN = "OPEN",
  /** Entry point is closed */
  CLOSED = "CLOSED",
  /** Entry point is locked and secured */
  LOCKED = "LOCKED",
  /** Entry point is disabled or out of service */
  DISABLED = "DISABLED",
  /** Entry point is under maintenance */
  MAINTENANCE = "MAINTENANCE",
  /** Entry point is in emergency open mode */
  EMERGENCY_OPEN = "EMERGENCY_OPEN",
  /** Entry point has been forced open (alarm condition) */
  FORCED_OPEN = "FORCED_OPEN",
  /** Status cannot be determined */
  UNKNOWN = "UNKNOWN",
}
