// This file is autogenerated - Please do not edit 

export enum PhysicalEntry_type {
  /** Standard door entry */
  DOOR = "DOOR",
  /** Gate or barrier entry */
  GATE = "GATE",
  /** Turnstile or revolving door */
  TURNSTILE = "TURNSTILE",
  /** Elevator access control */
  ELEVATOR = "ELEVATOR",
  /** Parking garage gate */
  PARKING_GATE = "PARKING_GATE",
  /** Security screening checkpoint */
  SECURITY_CHECKPOINT = "SECURITY_CHECKPOINT",
  /** Emergency exit door */
  EMERGENCY_EXIT = "EMERGENCY_EXIT",
  /** Vehicle access barrier */
  VEHICLE_BARRIER = "VEHICLE_BARRIER",
  /** Security mantrap or airlock */
  MANTRAP = "MANTRAP",
  /** Window access point */
  WINDOW = "WINDOW",
  /** Other or custom entry type */
  OTHER = "OTHER",
}
