// This file is autogenerated - Please do not edit 

export enum PrincipalType {
  /** Built-in administrator / superuser */
  ROOT = "ROOT",
  /** An authenticated person */
  USER = "USER",
  /** A security or user group */
  GROUP = "GROUP",
  /** An identity that may be assumed by another Principal */
  ROLE = "ROLE",
  /** An application or service account */
  SERVICE = "SERVICE",
  /** A physical or digital access token that can be granted permissions */
  CREDENTIAL = "CREDENTIAL",
  /** A local representation of a user defined in another system or application */
  FEDERATED_USER = "FEDERATED_USER",
  /** All members of an authentiated domain */
  DOMAIN = "DOMAIN",
  /** All people regardless of status, or fully anonymous access */
  PUBLIC = "PUBLIC",
  /** All users who have valid accounts and are authenticated */
  AUTHENTICATED_USERS = "AUTHENTICATED_USERS",
  /** An identity assumable by applications/resources to access other resources */
  MANAGED_IDENTITY = "MANAGED_IDENTITY",
  /** Vendor-specific or unmapped Principal type */
  OTHER = "OTHER",
}
