// This file is autogenerated - Please do not edit 

export enum Priority {
  /** Critical */
  CRITICAL = "CRITICAL",
  /** High */
  HIGH = "HIGH",
  /** Medium */
  MEDIUM = "MEDIUM",
  /** Low */
  LOW = "LOW",
  /** None */
  NONE = "NONE",
}
