// This file is autogenerated - Please do not edit 

export enum ResponsibilityType {
  /** Responsible. Those who do the work to achieve a task. There is typically one role with a participation type of Responsible. */
  R = "R",
  /** Accountable. Those who are ultimately accountable for the correct and thorough completion of the deliverable or task, and the one to whom Responsible is accountable. Typically, the Process Owner is Accountable for a process, and there must be only one Accountable specified for each task or deliverable. */
  A = "A",
  /** Support. Resources allocated to Responsible. Unlike Consulted, who may provide input to the task, Support will assist in completing the task. */
  S = "S",
  /** Consulted. Those who are not directly involved in a process but provide inputs and whose opinions are sought. */
  C = "C",
  /** Informed. Those who receive outputs from a process or are kept up-to-date on progress, often only on completion of the task or deliverable */
  I = "I",
  /** Quality Review. Those who check whether the product meets the quality requirements. */
  Q = "Q",
  /** Requestor. Person demanding activity */
  RQ = "RQ",
}
