// This file is autogenerated - Please do not edit 

export enum Role_accessLevel {
  /** Read-only access with no modification rights */
  READ_ONLY = "READ_ONLY",
  /** Standard user access with basic permissions */
  STANDARD = "STANDARD",
  /** Elevated access with additional permissions */
  ELEVATED = "ELEVATED",
  /** Administrative access with management rights */
  ADMINISTRATIVE = "ADMINISTRATIVE",
  /** Super administrator with full system access */
  SUPER_ADMIN = "SUPER_ADMIN",
  /** Custom access level defined by specific permissions */
  CUSTOM = "CUSTOM",
}
