// This file is autogenerated - Please do not edit 

export enum Role_type {
  /** Administrative or management role */
  ADMINISTRATIVE = "ADMINISTRATIVE",
  /** Function-based role (e.g., Developer, Analyst) */
  FUNCTIONAL = "FUNCTIONAL",
  /** Security-focused role */
  SECURITY = "SECURITY",
  /** Service account or system role */
  SERVICE = "SERVICE",
  /** Temporary or time-limited role */
  TEMPORARY = "TEMPORARY",
  /** Project-specific role */
  PROJECT = "PROJECT",
  /** Department or organizational unit role */
  DEPARTMENT = "DEPARTMENT",
  /** External user or contractor role */
  EXTERNAL = "EXTERNAL",
  /** Custom or user-defined role */
  CUSTOM = "CUSTOM",
}
