// This file is autogenerated - Please do not edit 

export enum ServiceEndpoint_tlsVersions {
  /** TLS 1.0 */
  TLS_1_0 = "TLS_1_0",
  /** TLS 1.1 */
  TLS_1_1 = "TLS_1_1",
  /** TLS 1.2 */
  TLS_1_2 = "TLS_1_2",
  /** TLS 1.3 */
  TLS_1_3 = "TLS_1_3",
}
