// This file is autogenerated - Please do not edit 

export enum SnapshotRetentionPolicy {
  /** Hourly */
  HOURLY = "HOURLY",
  /** Daily */
  DAILY = "DAILY",
  /** Weekly */
  WEEKLY = "WEEKLY",
  /** Other configuration */
  OTHER = "OTHER",
}
