// This file is autogenerated - Please do not edit 

export enum TestResult {
  /** Passing or successfully completing a training module */
  PASS = "PASS",
  /** Failing or unsuccessfully completing a training module */
  FAIL = "FAIL",
}
