// This file is autogenerated - Please do not edit 

export enum TicketStatus {
  /** Resolved */
  RESOLVED = "RESOLVED",
  /** Closed */
  CLOSED = "CLOSED",
  /** In Progress */
  IN_PROGRESS = "IN_PROGRESS",
  /** On Hold */
  ON_HOLD = "ON_HOLD",
  /** New */
  NEW = "NEW",
  /** Open */
  OPEN = "OPEN",
  /** Canceled */
  CANCELED = "CANCELED",
}
