// This file is autogenerated - Please do not edit 

export enum TrainingModuleType {
  /** Training Module */
  TRAINING_MODULE = "TRAINING_MODULE",
  /** Video Training Module */
  VIDEO_MODULE = "VIDEO_MODULE",
  /** Gamification and Interactive Training Module */
  GAME = "GAME",
  /** Assessment Training Module */
  ASSESSMENT = "ASSESSMENT",
  /** Other */
  OTHER = "OTHER",
}
