// This file is autogenerated - Please do not edit 

export enum Vm_hypervisor {
  /** Xen */
  XEN = "XEN",
  /** Oracle Virtual Machine */
  OVM = "OVM",
  /** Kernel-based Virtual Machine */
  KVM = "KVM",
  /** VMware */
  VMWARE = "VMWARE",
  /** Microsoft Hyper-V */
  HYPERV = "HYPERV",
  /** Oracle VirtualBox */
  VIRTUALBOX = "VIRTUALBOX",
  /** XenServer */
  XEN_SERVER = "XEN_SERVER",
}
