import { GeoCountryDef } from "@zerobias-org/types-core-js";
import { AddressType } from "../enum/AddressType";

// This file is autogenerated - Please do not edit 

export interface Address {
  /** A line in a phyical address */
  addressLine?: string | Array<string>;
  /** Country for a mailing address */
  country?: GeoCountryDef;
  /** Location description */
  description?: string;
  /** A physical region or subregion (city, state, county, province, etc) */
  locality?: string | Array<string>;
  /** A physical address postal code, postcode, PIN, or ZIP */
  postalCode?: string;
  /** Enumeration indicating the type of address being stored */
  type?: AddressType;
}
