// This file is autogenerated - Please do not edit 

export interface AffectedVersions {
  /** A CPE version affected by the vulnerability */
  affectedVersions?: string | Array<string>;
}

export interface T3_AffectedVersions {
  id: string;
  zerobias_zerobias_platform_schema_affectedVersions: AffectedVersions;
}
