import { BackgroundCheckResult } from "../enum/BackgroundCheckResult";
import { BackgroundCheckType } from "../enum/BackgroundCheckType";
import { InvestigationStatus } from "../enum/InvestigationStatus";

// This file is autogenerated - Please do not edit 

export interface BackgroundCheck {
  /** Date of Completion expressed according ISO 8601/RFC 3339 */
  completionDate?: Date;
  /** Result of a background check */
  result?: BackgroundCheckResult;
  /** Date of Creation */
  startDate?: Date;
  /** Investigation Status */
  status?: InvestigationStatus;
  /** Type of Background Check */
  type?: BackgroundCheckType;
}
