// This file is autogenerated - Please do not edit 

export interface BlockDevice {
  /** The name of the device */
  deviceName?: string;
  /** Whether or not the device is the root device */
  isRoot?: boolean;
}

export interface T3_BlockDevice {
  id: string;
  zerobias_zerobias_base_schema_blockDevice: BlockDevice;
}
