// This file is autogenerated - Please do not edit 

export interface BucketLifecycleRule {
  /** Action to take when a bucket lifecycle rule is triggered */
  action?: string;
  /** The condition of the rule */
  condition?: string;
  /** The state of the bucket lifecycle rule */
  state?: string;
}
