import { PermissionType } from "../enum/PermissionType";

// This file is autogenerated - Please do not edit 

export interface BucketGrant {
  /** Enables a different account/user/group to access a bucket */
  grantee?: string;
  /** Permission types */
  permission?: PermissionType;
}
