import { Email } from "@zerobias-org/types-core-js";

// This file is autogenerated - Please do not edit 

export interface Comment {
  /** Comment Subject or Title */
  title?: string;
  /** Comment Body */
  body?: string;
  /** Date of Creation */
  dateCreated?: Date;
  /** Unique ID of the author of the comment */
  authorId?: string;
  /** The full name of the author of the comment */
  authorName?: string;
  /** Username / Login the author of the comment */
  authorUsername?: string;
  /** A valid email */
  authorEmail?: Email;
}
