import { ComputeCpuArchitecture } from "../enum/ComputeCpuArchitecture";

// This file is autogenerated - Please do not edit 

export interface Compute {
  /** The architecture of the CPU. */
  cpuArchitecture?: ComputeCpuArchitecture;
  /** CPU Logical Core count */
  cpuCoresLogical?: number;
  /** CPU Physical Core count */
  cpuCoresPhysical?: number;
  /** CPU Clock (MHz) */
  cpuMHz?: number;
  /** CPU Model */
  cpuModel?: string;
  /** CPU Vendor */
  cpuVendor?: string;
  /** CPU RAM in */
  memTotalkB?: number;
  /** Socket count */
  socket?: number;
}
