import { FedrampRoleType } from "../enum/FedrampRoleType";
import { HitrustRoleType } from "../enum/HitrustRoleType";
import { OscalRoleType } from "../enum/OscalRoleType";
import { PciDssRoleType } from "../enum/PciDssRoleType";

// This file is autogenerated - Please do not edit 

export interface ComponentRole {
  /** Enumeration indicating the type of FedRAMP role */
  fedrampRole?: FedrampRoleType | Array<FedrampRoleType>;
  /** HITRUST Roles */
  hitrustRole?: HitrustRoleType | Array<HitrustRoleType>;
  /** Type of role as defined by OSCAL */
  oscalRole?: OscalRoleType | Array<OscalRoleType>;
  /** Customer locally defined values */
  other?: string | Array<string>;
  /** Common types of roles as defined by PCI DSS */
  pciDssRole?: PciDssRoleType | Array<PciDssRoleType>;
}

export interface T3_ComponentRole {
  id: string;
  zerobias_zerobias_platform_schema_componentRole: ComponentRole;
}
