import { ConditionOperation } from "../enum/ConditionOperation";

// This file is autogenerated - Please do not edit 

export interface Condition {
  /** Workflow Step Condition Property */
  property?: string;
  /** Condition Operation */
  operation?: ConditionOperation;
  /** Condition Value */
  value?: string | Array<string>;
  /** Description of a Condition */
  expression?: string;
}
