import { Duration, HttpMethodDef } from "@zerobias-org/types-core-js";

// This file is autogenerated - Please do not edit 

export interface CorsRule {
  /** Headers that are specified in the Access-Control-Request-Headers header. In response to any preflight OPTIONS request, the server returns any requested headers that in this list. Use * for all. */
  allowedHeaders?: string | Array<string>;
  /** An HTTP Method as defined by RFC-7231 and RFC-5789 */
  allowedMethods?: HttpMethodDef | Array<HttpMethodDef>;
  /** Referring URLs that are able to use this rule, or * for all */
  allowedOrigins?: string | Array<string>;
  /** One or more headers in the response that callers are able to access from their applications */
  exposeHeaders?: string | Array<string>;
  /** The time in ISO8601 duration that your browser is to cache the preflight response for the specified resource */
  maxAge?: Duration;
}
