import { TlsX509Certificate } from "@zerobias-org/types-core-js";
import { CipherAlgorithm } from "../enum/CipherAlgorithm";
import { CipherKeyAgreement } from "../enum/CipherKeyAgreement";
import { CipherKeyGenerator } from "../enum/CipherKeyGenerator";
import { CipherKeyPairGenerator } from "../enum/CipherKeyPairGenerator";
import { CipherMode } from "../enum/CipherMode";
import { CipherPadding } from "../enum/CipherPadding";
import { CipherSecretKeyFactory } from "../enum/CipherSecretKeyFactory";
import { CryptoModuleType } from "../enum/CryptoModuleType";

// This file is autogenerated - Please do not edit 

export interface CryptoModule {
  /** The type of encryption */
  moduleType?: CryptoModuleType;
  /** A x509 certificate */
  certificate?: TlsX509Certificate | Array<TlsX509Certificate>;
  /** The name of the Cipher Algorithm as prescribed by JCE */
  cipherAlgorithm?: CipherAlgorithm;
  /** The name of the Cipher Key Agreement as prescribed by JCE */
  cipherKeyAgreement?: CipherKeyAgreement;
  /** The name of the Cipher Key Generator as prescribed by JCE */
  cipherKeyGenerator?: CipherKeyGenerator;
  /** The name of the Cipher Key Pair Generator as prescribed by JCE */
  cipherSecretKeyFactory?: CipherSecretKeyFactory;
  /** The name of the Cipher Key Pair Generator as prescribed by JCE */
  cipherKeyPairGenerator?: CipherKeyPairGenerator;
  /** The name of the Cipher Mode as prescribed by JCE */
  cipherMode?: CipherMode;
  /** The name of the Cipher Padding as prescribed by JCE */
  cipherPadding?: CipherPadding;
}
