import { SeverityDef } from "@zerobias-org/types-core-js";
import { Cvss_version } from "../enum/Cvss_version";
import { Cvssv2_accessComplexity } from "../enum/Cvssv2_accessComplexity";
import { Cvssv2_accessVector } from "../enum/Cvssv2_accessVector";
import { Cvssv2_authentication } from "../enum/Cvssv2_authentication";
import { Cvssv2_availabilityImpact } from "../enum/Cvssv2_availabilityImpact";
import { Cvssv2_confidentialityImpact } from "../enum/Cvssv2_confidentialityImpact";
import { Cvssv2_integrityImpact } from "../enum/Cvssv2_integrityImpact";

// This file is autogenerated - Please do not edit 

export interface CvssV2 {
  /** The vector string */
  vectorString?: string;
  /** The base score of the vulnerability, as a floating point value */
  baseScore?: number;
  /** Severity/magnitude of a risk, incident, bug, or vulnerability */
  baseSeverity?: SeverityDef;
  /** CVSS version */
  version?: Cvss_version;
  /** This metric reflects how the vulnerability is exploited. The more remote an attacker can be to attack a host, the greater the vulnerability score. */
  accessVector?: Cvssv2_accessVector;
  /**
   * This metric measures the complexity of the attack required to exploit the vulnerability once an attacker has gained access to the target system. For example, consider a buffer overflow in an Internet service: once the target system is located, the attacker can launch an exploit at will.
   * Other vulnerabilities, however, may require additional steps in order to be exploited. For example, a vulnerability in an email client is only exploited after the user downloads and opens a tainted attachment. The lower the required complexity, the higher the vulnerability score.
   */
  accessComplexity?: Cvssv2_accessComplexity;
  /** This metric measures the number of times an attacker must authenticate to a target in order to exploit a vulnerability. This metric does not gauge the strength or complexity of the authentication process, only that an attacker is required to provide credentials before an exploit may occur. The fewer authentication instances that are required, the higher the vulnerability score. */
  authentication?: Cvssv2_authentication;
  /** This metric measures the impact on confidentiality of a successfully exploited vulnerability. Confidentiality refers to limiting information access and disclosure to only authorized users, as well as preventing access by, or disclosure to, unauthorized ones. Increased confidentiality impact increases the vulnerability score. */
  confidentialityImpact?: Cvssv2_confidentialityImpact;
  /** This metric measures the impact to integrity of a successfully exploited vulnerability. Integrity refers to the trustworthiness and guaranteed veracity of information. Increased integrity impact increases the vulnerability score. */
  integrityImpact?: Cvssv2_integrityImpact;
  /** Thismetric measures the impact to availability of a successfully exploited vulnerability. Availability refers to the accessibility of information resources. Attacks that consume network bandwidth, processor cycles, or disk space all impact the availability of a system. Increased availability impact increases the vulnerability score. */
  availabilityImpact?: Cvssv2_availabilityImpact;
}
