import { SeverityDef } from "@zerobias-org/types-core-js";
import { Cvss_version } from "../enum/Cvss_version";
import { Cvssv4_attackComplexity } from "../enum/Cvssv4_attackComplexity";
import { Cvssv4_attackRequirements } from "../enum/Cvssv4_attackRequirements";
import { Cvssv4_attackVector } from "../enum/Cvssv4_attackVector";
import { Cvssv4_privilegesRequired } from "../enum/Cvssv4_privilegesRequired";
import { Cvssv4_subsequentSystemAvailabilityImpact } from "../enum/Cvssv4_subsequentSystemAvailabilityImpact";
import { Cvssv4_subsequentSystemConfidentialityImpact } from "../enum/Cvssv4_subsequentSystemConfidentialityImpact";
import { Cvssv4_subsequentSystemIntegrityImpact } from "../enum/Cvssv4_subsequentSystemIntegrityImpact";
import { Cvssv4_userInteraction } from "../enum/Cvssv4_userInteraction";
import { Cvssv4_vulnerableSystemAvailabilityImpact } from "../enum/Cvssv4_vulnerableSystemAvailabilityImpact";
import { Cvssv4_vulnerableSystemConfidentialityImpact } from "../enum/Cvssv4_vulnerableSystemConfidentialityImpact";
import { Cvssv4_vulnerableSystemIntegrityImpact } from "../enum/Cvssv4_vulnerableSystemIntegrityImpact";

// This file is autogenerated - Please do not edit 

export interface CvssV4 {
  /** The vector string */
  vectorString?: string;
  /** The base score of the vulnerability, as a floating point value */
  baseScore?: number;
  /** Severity/magnitude of a risk, incident, bug, or vulnerability */
  baseSeverity?: SeverityDef;
  /** CVSS version */
  version?: Cvss_version;
  /** This metric reflects the context by which vulnerability exploitation is possible. This metric value (and consequently the resulting severity) will be larger the more remote (logically, and physically) an attacker can be in order to exploit the vulnerable system. The assumption is that the number of potential attackers for a vulnerability that could be exploited from across a network is larger than the number of potential attackers that could exploit a vulnerability requiring physical access to a device, and therefore warrants a greater severity. */
  attackVector?: Cvssv4_attackVector;
  /**
   * This metric captures measurable actions that must be taken by the attacker to actively evade or circumvent existing built-in security-enhancing conditions in order to obtain a working exploit. These are conditions whose primary purpose is to increase security and/or increase exploit engineering complexity. A vulnerability exploitable without a target-specific variable has a lower complexity than a vulnerability that would require non-trivial customization. This metric is meant to capture security mechanisms utilized by the vulnerable system, and does not relate to the amount of time or attempts it would take for an attacker to succeed, e.g. a race condition. If the attacker does not take action to overcome these conditions, the attack will always fail.
   * The evasion or satisfaction of authentication mechanisms or requisites is included in the Privileges Required assessment and is not considered here as a factor of relevance for Attack Complexity.
   */
  attackComplexity?: Cvssv4_attackComplexity;
  /** This metric captures the prerequisite deployment and execution conditions or variables of the vulnerable system that enable the attack. These differ from security-enhancing techniques/technologies (ref Attack Complexity) as the primary purpose of these conditions is not to explicitly mitigate attacks, but rather, emerge naturally as a consequence of the deployment and execution of the vulnerable system. If the attacker does not take action to overcome these conditions, the attack may succeed only occasionally or not succeed at all. */
  attackRequirements?: Cvssv4_attackRequirements;
  /**
   * This metric describes the level of privileges an attacker must possess prior to successfully exploiting the vulnerability. The method by which the attacker obtains privileged credentials prior to the attack (e.g., free trial accounts), is outside the scope of this metric. Generally, self-service provisioned accounts do not constitute a privilege requirement if the attacker can grant themselves privileges as part of the attack.
   * The resulting score is greatest if no privileges are required.
   */
  privilegesRequired?: Cvssv4_privilegesRequired;
  /** This metric captures the requirement for a human user, other than the attacker, to participate in the successful compromise of the vulnerable system. This metric determines whether the vulnerability can be exploited solely at the will of the attacker, or whether a separate user (or user-initiated process) must participate in some manner. The resulting score is greatest when no user interaction is required. */
  userInteraction?: Cvssv4_userInteraction;
  /** This metric measures the impact to the confidentiality of the information managed by the system due to a successfully exploited vulnerability. Confidentiality refers to limiting information access and disclosure to only authorized users, as well as preventing access by, or disclosure to, unauthorized ones. The resulting score is greatest when the loss to the system is highest. */
  vulnerableSystemConfidentialityImpact?: Cvssv4_vulnerableSystemConfidentialityImpact;
  /** This metric measures the impact to the confidentiality of the information managed by the system due to a successfully exploited vulnerability. Confidentiality refers to limiting information access and disclosure to only authorized users, as well as preventing access by, or disclosure to, unauthorized ones. The resulting score is greatest when the loss to the system is highest. */
  subsequentSystemConfidentialityImpact?: Cvssv4_subsequentSystemConfidentialityImpact;
  /**
   * This metric measures the impact to integrity of a successfully exploited vulnerability. Integrity refers to the trustworthiness and veracity of information. Integrity of a system is impacted when an attacker causes unauthorized modification of system data. Integrity is also impacted when a system user can repudiate critical actions taken in the context of the system (e.g. due to insufficient logging).
   * The resulting score is greatest when the consequence to the system is highest.
   */
  vulnerableSystemIntegrityImpact?: Cvssv4_vulnerableSystemIntegrityImpact;
  /**
   * This metric measures the impact to integrity of a successfully exploited vulnerability. Integrity refers to the trustworthiness and veracity of information. Integrity of a system is impacted when an attacker causes unauthorized modification of system data. Integrity is also impacted when a system user can repudiate critical actions taken in the context of the system (e.g. due to insufficient logging).
   * The resulting score is greatest when the consequence to the system is highest.
   */
  subsequentSystemIntegrityImpact?: Cvssv4_subsequentSystemIntegrityImpact;
  /** This metric measures the impact to the availability of the impacted system resulting from a successfully exploited vulnerability. While the Confidentiality and Integrity impact metrics apply to the loss of confidentiality or integrity of data (e.g., information, files) used by the system, this metric refers to the loss of availability of the impacted system itself, such as a networked service (e.g., web, database, email). Since availability refers to the accessibility of information resources, attacks that consume network bandwidth, processor cycles, or disk space all impact the availability of a system. The resulting score is greatest when the consequence to the system is highest. */
  vulnerableSystemAvailabilityImpact?: Cvssv4_vulnerableSystemAvailabilityImpact;
  /** This metric measures the impact to the availability of the impacted system resulting from a successfully exploited vulnerability. While the Confidentiality and Integrity impact metrics apply to the loss of confidentiality or integrity of data (e.g., information, files) used by the system, this metric refers to the loss of availability of the impacted system itself, such as a networked service (e.g., web, database, email). Since availability refers to the accessibility of information resources, attacks that consume network bandwidth, processor cycles, or disk space all impact the availability of a system. The resulting score is greatest when the consequence to the system is highest. */
  subsequentSystemAvailabilityImpact?: Cvssv4_subsequentSystemAvailabilityImpact;
}
