import { FilesystemType } from "../enum/FilesystemType";

// This file is autogenerated - Please do not edit 

export interface Filesystem {
  /** Commonly used filesystems as defined by NIST SP 800-86 */
  filesystemType?: FilesystemType;
  /** Whether or not a filesystem is encrypted */
  isEncrypted?: boolean;
  /** Filesystem mount point such as path, directory, or drive letter, where the file system may be attached */
  mountPoint?: string;
  /** Total Storage Space in Bytes */
  totalStorageSpace?: number;
}
