import { Cidr } from "@zerobias-org/types-core-js";
import { Acl_action } from "../enum/Acl_action";
import { IpProtocol } from "../enum/IpProtocol";

// This file is autogenerated - Please do not edit 

export interface Firewall_rule {
  /** ACL Action */
  action?: Acl_action;
  /** CIDR block of IP addresses for an ACL rule */
  addresses?: Cidr | Array<Cidr>;
  /** A single port number (0..65535) or a hyphen separated range */
  portRange?: string;
  /** IANA protocol numbers for IP traffic */
  protocol?: IpProtocol;
}
