import { TlsX509Certificate } from "@zerobias-org/types-core-js";

// This file is autogenerated - Please do not edit 

export interface InstalledApp {
  /** Date of installation */
  timeInstalled?: Date;
  /** Timestamp in RFC339/ISO8601 date-time string */
  timeModified?: Date;
  /** Application License Key */
  licenseKey?: string;
  /** Application Installation Path */
  installationPath?: string;
  /** Application Installation Path */
  dataPath?: string;
  /** A line in a phyical address */
  digitalSignature?: string;
  /** A x509 certificate */
  cryptoCertificate?: TlsX509Certificate | Array<TlsX509Certificate>;
  /** Application Publisher */
  publisher?: string;
  /** Application Size in Bytes */
  size?: number;
  /** Application Version */
  version?: string;
  /** Application Name */
  name?: string;
  /** Appliction Id */
  id?: string;
}
