import { IpAddress } from "@zerobias-org/types-core-js";
import { IpVersion } from "../enum/IpVersion";

// This file is autogenerated - Please do not edit 

export interface IpInterface {
  /** An IP Gateway */
  gateway?: IpAddress;
  /** IP interface gateway metric/routing preference */
  gatewayMetric?: number;
  /** DNS domain name for a service or host */
  hostname?: string;
  /** Internet Protocol (IP) Version (IPv4, IPv6) */
  ipVersion?: IpVersion;
  /** Name server address */
  nameServerIp?: IpAddress | Array<IpAddress>;
  /** An IPv4 or IPv6 Address */
  netmask?: IpAddress;
}
