import { IpAddress } from "@zerobias-org/types-core-js";
import { IpRouteFlag } from "../enum/IpRouteFlag";
import { OperationalStatus } from "../enum/OperationalStatus";

// This file is autogenerated - Please do not edit 

export interface IpRoute {
  /** IP addresses for destination network */
  destination?: IpAddress;
  /** The type of location */
  flags?: IpRouteFlag | Array<IpRouteFlag>;
  /** Gateway address or undefined if none set */
  gateway?: IpAddress;
  /** The netmask for the destination net */
  genmask?: IpAddress;
  /** Name of interface where packets will be sent */
  iface?: string;
  /** Initial Round Trip Time */
  irtt?: number;
  /** Distance to target (in hops) */
  metric?: number;
  /** Maximum Segment Size for TCP connections */
  mss?: number;
  /** The origin of a route */
  origin?: string;
  /** Current operational state of a resource or interface. */
  status?: OperationalStatus;
  /** Default window size for TCP connections */
  window?: number;
}

export interface T3_IpRoute {
  id: string;
  zerobias_zerobias_base_schema_ipRoute: IpRoute;
}
