// This file is autogenerated - Please do not edit 

export interface IssuedDate {
  /** Date of Issue */
  dateOfIssue?: Date;
}

export interface T3_IssuedDate {
  id: string;
  zerobias_zerobias_base_schema_issuedDate: IssuedDate;
}
