import { UUID } from "@zerobias-org/types-core-js";
import { ObjectLinkMatchInfo } from "../document/ObjectLinkMatchInfo";

// This file is autogenerated - Please do not edit 

export interface Link {
  /** The edge value of the link */
  edgeValue?: string;
  /** The Link ID */
  id?: UUID;
  /** the link end time */
  linkEndTime?: Date;
  /** the link start time */
  linkStartTime?: Date;
  /** The ID of the link_type associated with this link */
  linkTypeId: UUID;
  /** Describes one side of the link */
  local?: ObjectLinkMatchInfo;
  /** Describes one side of the link */
  remote?: ObjectLinkMatchInfo;
}
