import { GeoPoint, PhoneNumber } from "@zerobias-org/types-core-js";
import { Address } from "../document/Address";
import { LocationType } from "../enum/LocationType";

// This file is autogenerated - Please do not edit 

export interface LocationInfo {
  /** The type of location */
  locationType?: LocationType;
  /** A physical address */
  address?: Address | Array<Address>;
  /** GPS Coordinate in WGS-84 coordinates */
  geoPoint?: GeoPoint;
  /** A valid phone number */
  phoneNumber?: PhoneNumber | Array<PhoneNumber>;
}
