import { Email } from "@zerobias-org/types-core-js";
import { ContactType } from "../enum/ContactType";

// This file is autogenerated - Please do not edit 

export interface MailInfo {
  /** Type of a contact */
  contactType?: ContactType;
  /** A valid email */
  email?: Email;
}
