// This file is autogenerated - Please do not edit 

export interface Metadata_tag {
  /** Tag Name */
  name?: string;
  /** Tag Type */
  type?: string;
  /** Tag Description */
  description?: string;
}
