// This file is autogenerated - Please do not edit 

export interface MitigationStrategy {
  /** The name of the technique */
  techniqueName?: string;
  /** The activity taken with regards to the artifact */
  artifactAction?: string;
  /** The name of the artifact */
  artifactName?: string;
  /** The action to be taken on the tactic */
  tacticAction?: string;
  /** The name of the tactic */
  tacticName?: string;
  /** The id of the technique */
  techniqueId?: string;
  /** A summary of the mitigation strategy */
  summary?: string;
}

export interface T3_MitigationStrategy {
  id: string;
  zerobias_zerobias_base_schema_mitigationStrategy: MitigationStrategy;
}
