import { MacAddress } from "@zerobias-org/types-core-js";
import { IpInterface } from "../document/IpInterface";
import { AdminStatus } from "../enum/AdminStatus";
import { NetworkInterfaceType } from "../enum/NetworkInterfaceType";
import { OperationalStatus } from "../enum/OperationalStatus";

// This file is autogenerated - Please do not edit 

export interface NetworkInterface {
  /** Description for a requirement */
  description?: string;
  /** Official name of device seen by operating system */
  deviceName: string;
  /** A hardware MAC address */
  macAddress?: MacAddress;
  /** Specifies types of network interfaces as defined by the Institute of Electrical and Electronics Engineers (IEEE) standards */
  networkInterfaceType?: NetworkInterfaceType;
  /** Administrative status of the Interface. Available states are: Enabled/Up (1), Disabled/Down (2), and Testing (3) */
  adminStatus?: AdminStatus;
  /** Current operational state of a resource or interface. */
  operationalStatus?: OperationalStatus;
  /** A numeric value indicating speed measured in bits per second (bps) */
  speed?: number;
  /** Boolean value indicating receive permission */
  isReceiveOnly?: boolean;
  /** A broadcast domain that is partitioned and isolated within a network at the data link layer. A single physical local area network (LAN) can be logically partitioned into multiple, independent VLANs; a group of devices on one or more physical LANs can be configured to communicate within the same VLAN, as if they were attached to the same physical LAN. */
  vlanId?: number;
  /** Maximum Transmission Unit (MTU) measured in bytes */
  mtu?: number;
  /** IPv4/v6 Interface Properties */
  ipInterface?: IpInterface | Array<IpInterface>;
}
