import { ParameterApplyType } from "../enum/ParameterApplyType";

// This file is autogenerated - Please do not edit 

export interface Parameter {
  /** The name of the parameter, registry key, environment variable, etc */
  name?: string;
  /** The description of the parameter, registry key, environment variable, etc */
  description?: string;
  /** The origin/source/template from which this parameter was derived */
  source?: string;
  /** The (vendor-specific) data type of this parameter */
  dataType?: string;
  /** Whether a configuration parameter can be udpated immediately or if a restart is required */
  applyType?: ParameterApplyType;
  /** True if a static parameter has been changed but the value not yet applied */
  applyPending?: boolean;
  /** The name of the parameter, registry key, environment variable, etc */
  allowedValues?: string | Array<string>;
  /** True if a parameter allows changes or not */
  mutable?: boolean;
}
