import { ResponsibilityType } from "../enum/ResponsibilityType";

// This file is autogenerated - Please do not edit 

export interface PartyRole {
  /** Enumeration of responsibility assignment associated with Responsibility Matrix, such as RACI, RASCI model to assign responsibilities to processes */
  responsibility?: ResponsibilityType | Array<ResponsibilityType>;
}

export interface T3_PartyRole {
  id: string;
  zerobias_zerobias_base_schema_partyRole: PartyRole;
}
