import { Duration } from "@zerobias-org/types-core-js";
import { AdminStatus } from "../enum/AdminStatus";
import { CipherAlgorithm } from "../enum/CipherAlgorithm";

// This file is autogenerated - Please do not edit 

export interface PasswordPolicy {
  /** The name of the Cipher Algorithm as prescribed by JCE */
  cipherAlgorithm?: CipherAlgorithm;
  /** The maximum age of a password before it expires */
  expirationPeriod?: Duration;
  /** Maximum Length */
  maxLength?: number;
  /** Minimum Length */
  minLength?: number;
  /** The number of saved passwords to prevent re-use */
  passwordHistory?: number;
  /** Number of required digits */
  requiredDigits?: number;
  /** Number of required lower-case letters */
  requiredLower?: number;
  /** Number of required special / non-alphanumeric characters */
  requiredSpecial?: number;
  /** Number of required upper-case letters */
  requiredUpper?: number;
  /** True if the system uses reversible encryption for the password */
  reversible?: boolean;
  /** Administrative status of the Interface. Available states are: Enabled/Up (1), Disabled/Down (2), and Testing (3) */
  status?: AdminStatus;
}
