import { PermissionType } from "../enum/PermissionType";

// This file is autogenerated - Please do not edit 

export interface PermissionSet {
  /** Permission types */
  allow?: PermissionType | Array<PermissionType>;
  /** Permission types */
  deny?: PermissionType | Array<PermissionType>;
}

export interface T3_PermissionSet {
  id: string;
  zerobias_zerobias_base_schema_permissionSet: PermissionSet;
}
