import { PhoneNumber } from "@zerobias-org/types-core-js";
import { ContactType } from "../enum/ContactType";

// This file is autogenerated - Please do not edit 

export interface PhoneInfo {
  /** Type of a contact */
  contactType?: ContactType;
  /** A valid phone number */
  phoneNumber: PhoneNumber;
}
