import { OperationalStatus } from "../enum/OperationalStatus";
import { RouterAssociationType } from "../enum/RouterAssociationType";

// This file is autogenerated - Please do not edit 

export interface RouterAssociation {
  /** Unique ID for this association */
  id?: string;
  /** The type of relationship between a router and subnet */
  type?: RouterAssociationType;
  /** Current operational state of a resource or interface. */
  status?: OperationalStatus;
}

export interface T3_RouterAssociation {
  id: string;
  zerobias_zerobias_base_schema_routerAssociation: RouterAssociation;
}
