// This file is autogenerated - Please do not edit 

export interface Tag {
  /** The Key/ID/Tyoe of a Tag */
  key?: string;
  /** The value or name of a Tag */
  value: string;
  /** The description or meaning of a Tag */
  description?: string;
}
