import { Condition } from "../document/Condition";

// This file is autogenerated - Please do not edit 

export interface Transition {
  /** Conditions required to transition workflow steps */
  condition?: Condition;
  /** Name of a transition beteen workflow steps */
  name?: string;
}

export interface T3_Transition {
  id: string;
  zerobias_zerobias_platform_schema_transition: Transition;
}
