import { URL } from "@zerobias-org/types-core-js";
import { Link } from "../document/Link";
import { ObjectMetadata } from "../document/ObjectMetadata";
import { Tag } from "../document/Tag";
import { Element } from "../interface/Element";
import { Object } from "../interface/Object";

// This file is autogenerated - Please do not edit 

export class AgentSkill implements Element, Object {
  /** An identifier for an object as seen from the external point of view */
  externalId?: string;
  /** A relatively unique identifier for an object */
  code?: string;
  /** The version of an element */
  version?: string;
  /** Markdown text of the background for this test case */
  background?: string;
  /** The external ID that defines this object for joining purposes */
  baselineElements?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  parent?: string;
  /** The external ID that defines this object for joining purposes */
  subElements?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  standard?: string;
  /** The external ID that defines this object for joining purposes */
  elementType?: string;
  /** The external ID that defines this object for joining purposes */
  testCases?: string | Array<string>;
  /** A tag that is applied to an Object */
  tag?: Tag | Array<Tag>;
  /** The (absolute or relative) URL for an icon representing the object */
  icon?: URL;
  /** A URL/link for this Object in its source system */
  url?: URL;
  /** The last time when this object was modified in its source system */
  dateLastModified?: Date;
  /** The ltime when this object was (soft) deleted in its source system */
  dateDeleted?: Date;
  /** The time when this object was created in its source system */
  dateCreated?: Date;
  /** Describes Link attributes in the context of a join */
  _links?: Link | Array<Link>;
  /** The object's external ID in the payload data */
  id: string;
  /** The name of an object */
  name: string;
  /** A generic description */
  description?: string;
  /** A generic note */
  note?: string;
  /** Describes an object stored in other object */
  includes?: string | Array<string>;
  /** An alias for this object */
  aliases?: string | Array<string>;
  /** Metadata Store for Concrete Object Data */
  metadata?: ObjectMetadata;
  /** License name or reference (e.g., "Apache-2.0") */
  license?: string;
  /** Environment requirements (e.g., "Designed for Claude Code") */
  compatibility?: string;
  /** Skill author from metadata */
  author?: string;
  /** Version from metadata */
  skillVersion?: string;
  /** GitHub repository URL */
  sourceRepo?: string;
  /** Path within repo (e.g., "skills/pdf/SKILL.md") */
  sourcePath?: string;
  /** Space-delimited list of pre-approved tools for the skill */
  allowedTools?: string;
  /** The markdown body content of the SKILL.md file */
  bodyContent?: string;

  /** @deprecated Please use Object Literal instead `var foo = { foo: "foo"}` */
  constructor(_id: string, _name: string) {
    this.id = _id
    this.name = _name
  }
}
