import { URL } from "@zerobias-org/types-core-js";
import { Link } from "../document/Link";
import { ObjectMetadata } from "../document/ObjectMetadata";
import { Tag } from "../document/Tag";

// This file is autogenerated - Please do not edit 

export interface Object {
  /** A tag that is applied to an Object */
  tag?: Tag | Array<Tag>;
  /** The (absolute or relative) URL for an icon representing the object */
  icon?: URL;
  /** A URL/link for this Object in its source system */
  url?: URL;
  /** The last time when this object was modified in its source system */
  dateLastModified?: Date;
  /** The ltime when this object was (soft) deleted in its source system */
  dateDeleted?: Date;
  /** The time when this object was created in its source system */
  dateCreated?: Date;
  /** Describes Link attributes in the context of a join */
  _links?: Link | Array<Link>;
  /** The object's external ID in the payload data */
  id: string;
  /** The name of an object */
  name: string;
  /** A generic description */
  description?: string;
  /** A generic note */
  note?: string;
  /** Describes an object stored in other object */
  includes?: string | Array<string>;
  /** An alias for this object */
  aliases?: string | Array<string>;
  /** Metadata Store for Concrete Object Data */
  metadata?: ObjectMetadata;
}
