description: "Security Training Campaign"
extends: 
 - Campaign
icon: images/classes/auditmation/base/Campaign.svg
properties:
  - status:
    field: campaignStatus
  - startDate:
    field: dateStarted
  - endDate: 
    field: dateCompleted
# Links
  - groups:
    multi: true
    linkTo: TrainingGroup
  - modules:
    multi: true
    linkTo: TrainingModule