import { UUID } from "@zerobias-org/types-core-js";
import { Link_matchType } from "../enum/Link_matchType";

// This file is autogenerated - Please do not edit 

export interface ObjectLinkMatchInfo {
  /** The edge value of the link */
  linkClassId?: UUID;
  /** The class name of the object on this side of the link. */
  linkClassName?: UUID;
  /** The name (.ie ['accounts', 'members']) of the property on the local object. */
  linkPropertyName?: string;
  /** The id (.ie id of ['id', 'email']) of the property on this side of the link used to create this link. */
  matchPropertyId?: UUID;
  /** The name (.ie ['id', 'email']) of the property on this side of the link used to create this link. */
  matchPropertyName?: string;
  /** Link match type */
  matchType: Link_matchType;
  /** The local values that matched, when creating the link. * An array of one element on the link match. i.e. [foo@acme.org] * An array of one element or the original array of values that was used to create the link when `multi`. i.e. [foo@acme.org, bar@acme.org] * An empty array otherwise */
  matchValue?: string;
  /** The id of the object on the other side of this link. This is only set on the remote side of the link. */
  objectId?: UUID;
}
