import { UUID } from "@zerobias-org/types-core-js";
import { Metadata_tag } from "../document/Metadata_tag";
import { Metadata_operation } from "../enum/Metadata_operation";

// This file is autogenerated - Please do not edit 

export interface ObjectMetadata {
  /** UUID of the object stored in the database for this object instance */
  objectId: UUID;
  /** Version ID of the current object */
  versionId: UUID;
  /** UUID of the resource stored in the database for this object instance */
  resourceId?: UUID;
  /** Create time for this instance */
  createTime: Date;
  /** Last time this object was modified */
  modifyTime: Date;
  /** Operation for this object: create, modify, or delete */
  operation: Metadata_operation;
  /** The name of the class that this defines this object */
  className: string;
  /** Any tags given to the object based on the Batch ID */
  tags?: Metadata_tag | Array<Metadata_tag>;
  /** UUID of the previous version of this object, calculated automatically */
  previousVersionId?: UUID;
  /** UUID of the next modified version of this object, calculated automatically */
  nextVersionId?: UUID;
  /** The Batch ID associated with this object's import */
  batchId?: UUID;
  /** object_id:app.object_version(object_id):app.object_version(id):ObjectVersion(id) */
  objectVersion?: UUID | Array<UUID>;
  /** The class that this metadata resolves to */
  class?: UUID;
  /** A package code of the VSP linked to this object's schema */
  packageCode: string;
  /** UUID of the boundary this object is attached to */
  boundaryId: UUID;
  /** ID of the group this object was collected in */
  groupId: string;
}
