import { SeverityDef, URL } from "@zerobias-org/types-core-js";
import { Link } from "../document/Link";
import { ObjectMetadata } from "../document/ObjectMetadata";
import { Tag } from "../document/Tag";
import { CapecAbstraction } from "../enum/CapecAbstraction";
import { CapecLikelihoodOfAttack } from "../enum/CapecLikelihoodOfAttack";
import { CapecStatus } from "../enum/CapecStatus";
import { Object } from "../interface/Object";

// This file is autogenerated - Please do not edit 

export class CAPEC implements Object {
  /** A tag that is applied to an Object */
  tag?: Tag | Array<Tag>;
  /** The (absolute or relative) URL for an icon representing the object */
  icon?: URL;
  /** A URL/link for this Object in its source system */
  url?: URL;
  /** The last time when this object was modified in its source system */
  dateLastModified?: Date;
  /** The ltime when this object was (soft) deleted in its source system */
  dateDeleted?: Date;
  /** The time when this object was created in its source system */
  dateCreated?: Date;
  /** Describes Link attributes in the context of a join */
  _links?: Link | Array<Link>;
  /** The object's external ID in the payload data */
  id: string;
  /** The name of an object */
  name: string;
  /** A generic description */
  description?: string;
  /** A generic note */
  note?: string;
  /** Describes an object stored in other object */
  includes?: string | Array<string>;
  /** An alias for this object */
  aliases?: string | Array<string>;
  /** Metadata Store for Concrete Object Data */
  metadata?: ObjectMetadata;
  /** The status of a CAPEC */
  status?: CapecStatus;
  /** The abstraction level of a CAPEC */
  abstraction?: CapecAbstraction;
  /** The status of a CAPEC */
  likelihoodOfAttack?: CapecLikelihoodOfAttack;
  /** Severity/magnitude of a risk, incident, bug, or vulnerability */
  typicalSeverity?: SeverityDef;
  /** The external ID that defines this object for joining purposes */
  canPrecede?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  canFollow?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  categories?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  peerOf?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  peers?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  canAlsoBe?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  similarTo?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  parent?: string;
  /** The external ID that defines this object for joining purposes */
  children?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  weaknesses?: string | Array<string>;

  /** @deprecated Please use Object Literal instead `var foo = { foo: "foo"}` */
  constructor(_id: string, _name: string) {
    this.id = _id
    this.name = _name
  }
}
