import { SeverityDef, URL } from "@zerobias-org/types-core-js";
import { T3_AffectedVersions } from "../document/AffectedVersions";
import { CvssV2 } from "../document/CvssV2";
import { CvssV3 } from "../document/CvssV3";
import { CvssV4 } from "../document/CvssV4";
import { Link } from "../document/Link";
import { ObjectMetadata } from "../document/ObjectMetadata";
import { Tag } from "../document/Tag";
import { Object } from "../interface/Object";
import { Vulnerability } from "../interface/Vulnerability";

// This file is autogenerated - Please do not edit 

export class CVE implements Vulnerability, Object {
  /** CVSS (Common Vulnerability Score System) v3 */
  cvssV3?: CvssV3;
  /** CVSS (Common Vulnerability Score System) v4 */
  cvssV4?: CvssV4;
  /** CVSS (Common Vulnerability Score System) v2 */
  cvssV2?: CvssV2;
  /** Severity/magnitude of a risk, incident, bug, or vulnerability */
  severity?: SeverityDef;
  /** List of CPE versions affected by a vulnerability */
  cpeProducts?: string | Array<string> | T3_AffectedVersions | Array<T3_AffectedVersions>;
  /** The external ID that defines this object for joining purposes */
  testCases?: string | Array<string>;
  /** The external ID that defines this object for joining purposes */
  weaknesses?: string | Array<string>;
  /** A tag that is applied to an Object */
  tag?: Tag | Array<Tag>;
  /** The (absolute or relative) URL for an icon representing the object */
  icon?: URL;
  /** A URL/link for this Object in its source system */
  url?: URL;
  /** The last time when this object was modified in its source system */
  dateLastModified?: Date;
  /** The ltime when this object was (soft) deleted in its source system */
  dateDeleted?: Date;
  /** The time when this object was created in its source system */
  dateCreated?: Date;
  /** Describes Link attributes in the context of a join */
  _links?: Link | Array<Link>;
  /** The object's external ID in the payload data */
  id: string;
  /** The name of an object */
  name: string;
  /** A generic description */
  description?: string;
  /** A generic note */
  note?: string;
  /** Describes an object stored in other object */
  includes?: string | Array<string>;
  /** An alias for this object */
  aliases?: string | Array<string>;
  /** Metadata Store for Concrete Object Data */
  metadata?: ObjectMetadata;
  /** True if the CVE is a KEV (Known Exploited Vulnerability) */
  kev?: boolean;
  /** Date the CVE was discovered as a KEV */
  kevDiscovered?: Date;
  /** Date the CVE is due to be remediated */
  kevDueDate?: Date;
  /** True if the CVE is known to be used by ransomware */
  kevKnownRansomwareUse?: boolean;

  /** @deprecated Please use Object Literal instead `var foo = { foo: "foo"}` */
  constructor(_id: string, _name: string) {
    this.id = _id
    this.name = _name
  }
}
